In [40]:
import pandas as pd
import numpy as np 
import os 
from sklearn.preprocessing import LabelEncoder

In [41]:
root_ds_dir = "/kaggle/input/dseb-64-data-preparation-final-project/dseb63_final_project_DP_dataset/dseb63_final_project_DP_dataset"

In [42]:
app_train = pd.read_csv(os.path.join(root_ds_dir, "dseb63_application_train.csv"))

In [43]:
app_train.iloc[10:20]

,Unnamed: 0,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_CURR
10,10,0,Cash loans,M,Y,Y,0,157500.0,299772.0,20160.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,159669
11,11,0,Revolving loans,F,N,Y,1,81000.0,270000.0,13500.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,211972
12,12,0,Revolving loans,F,N,Y,0,112500.0,157500.0,7875.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,152919
13,13,0,Cash loans,F,N,Y,1,90000.0,544491.0,17563.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,67603
14,14,0,Revolving loans,M,Y,Y,0,135000.0,427500.0,21375.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,290315
15,15,0,Cash loans,F,Y,Y,1,202500.0,1132573.5,37561.5,...,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0,57291
16,16,0,Cash loans,F,N,Y,0,83250.0,239850.0,23850.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,170817
17,17,0,Cash loans,F,N,Y,0,90000.0,225000.0,11074.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,71586
18,18,0,Cash loans,M,N,Y,1,112500.0,327024.0,23827.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,205758
19,19,0,Cash loans,M,Y,Y,0,270000.0,790830.0,57676.5,...,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0,133615

In [44]:
app_train.columns

Index(['Unnamed: 0', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21',
       'AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY',
       'AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_MON',
       'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR',
       'SK_ID_CURR'],
      dtype='object', length=123)

In [45]:
app_train['TARGET'].value_counts()

TARGET
0    226133
1     19876
Name: count, dtype: int64

In [46]:
app_train.shape

(246009, 123)

In [47]:
app_train['SK_ID_CURR'].nunique()

246009

In [48]:
def display_missing_data_info(dataframe, ascending=False):
    missing_values_count = dataframe.isnull().sum()
    missing_values_percentage = (dataframe.isnull().mean() * 100)
    missing_data = pd.DataFrame({
        'Missing Values': missing_values_count,
        'Percentage (%)': missing_values_percentage
    })
    
    missing_data = missing_data[missing_data['Missing Values'] > 0]
    
    sorted_missing_data = missing_data.sort_values(by='Missing Values', ascending=ascending)

    #print(sorted_missing_data)
    return sorted_missing_data

In [49]:
display_missing_data_info(app_train, ascending=False)

                          Missing Values  Percentage (%)
COMMONAREA_MEDI                   171930       69.887687
COMMONAREA_AVG                    171930       69.887687
COMMONAREA_MODE                   171930       69.887687
NONLIVINGAPARTMENTS_MEDI          170869       69.456402
NONLIVINGAPARTMENTS_MODE          170869       69.456402
...                                  ...             ...
EXT_SOURCE_2                         529        0.215033
AMT_GOODS_PRICE                      224        0.091054
AMT_ANNUITY                           10        0.004065
DAYS_LAST_PHONE_CHANGE                 1        0.000406
CNT_FAM_MEMBERS                        1        0.000406

[67 rows x 2 columns]

In [50]:
nan_as_category = True

In [51]:
def OHE(df, nan_as_category = True):
    original_cols = list(df.columns)
    categorical_columns = [col for col in df.columns if df[col].dtype == 'object']
    df = pd.get_dummies(df, columns= categorical_columns,
                        dummy_na= nan_as_category)
    new_columns = [c for c in df.columns if c not in original_cols]
    return df, new_columns

In [52]:
for col in app_train.columns: 
    print(col, app_train[col].dtype)

Unnamed: 0 int64
TARGET int64
NAME_CONTRACT_TYPE object
CODE_GENDER object
FLAG_OWN_CAR object
FLAG_OWN_REALTY object
CNT_CHILDREN int64
AMT_INCOME_TOTAL float64
AMT_CREDIT float64
AMT_ANNUITY float64
AMT_GOODS_PRICE float64
NAME_TYPE_SUITE object
NAME_INCOME_TYPE object
NAME_EDUCATION_TYPE object
NAME_FAMILY_STATUS object
NAME_HOUSING_TYPE object
REGION_POPULATION_RELATIVE float64
DAYS_BIRTH int64
DAYS_EMPLOYED int64
DAYS_REGISTRATION float64
DAYS_ID_PUBLISH int64
OWN_CAR_AGE float64
FLAG_MOBIL int64
FLAG_EMP_PHONE int64
FLAG_WORK_PHONE int64
FLAG_CONT_MOBILE int64
FLAG_PHONE int64
FLAG_EMAIL int64
OCCUPATION_TYPE object
CNT_FAM_MEMBERS float64
REGION_RATING_CLIENT int64
REGION_RATING_CLIENT_W_CITY int64
WEEKDAY_APPR_PROCESS_START object
HOUR_APPR_PROCESS_START int64
REG_REGION_NOT_LIVE_REGION int64
REG_REGION_NOT_WORK_REGION int64
LIVE_REGION_NOT_WORK_REGION int64
REG_CITY_NOT_LIVE_CITY int64
REG_CITY_NOT_WORK_CITY int64
LIVE_CITY_NOT_WORK_CITY int64
ORGANIZATION_TYPE object
EXT_SOURCE_1 float64
EXT_SOURCE_2 float64
EXT_SOURCE_3 float64
APARTMENTS_AVG float64
BASEMENTAREA_AVG float64
YEARS_BEGINEXPLUATATION_AVG float64
YEARS_BUILD_AVG float64
COMMONAREA_AVG float64
ELEVATORS_AVG float64
ENTRANCES_AVG float64
FLOORSMAX_AVG float64
FLOORSMIN_AVG float64
LANDAREA_AVG float64
LIVINGAPARTMENTS_AVG float64
LIVINGAREA_AVG float64
NONLIVINGAPARTMENTS_AVG float64
NONLIVINGAREA_AVG float64
APARTMENTS_MODE float64
BASEMENTAREA_MODE float64
YEARS_BEGINEXPLUATATION_MODE float64
YEARS_BUILD_MODE float64
COMMONAREA_MODE float64
ELEVATORS_MODE float64
ENTRANCES_MODE float64
FLOORSMAX_MODE float64
FLOORSMIN_MODE float64
LANDAREA_MODE float64
LIVINGAPARTMENTS_MODE float64
LIVINGAREA_MODE float64
NONLIVINGAPARTMENTS_MODE float64
NONLIVINGAREA_MODE float64
APARTMENTS_MEDI float64
BASEMENTAREA_MEDI float64
YEARS_BEGINEXPLUATATION_MEDI float64
YEARS_BUILD_MEDI float64
COMMONAREA_MEDI float64
ELEVATORS_MEDI float64
ENTRANCES_MEDI float64
FLOORSMAX_MEDI float64
FLOORSMIN_MEDI float64
LANDAREA_MEDI float64
LIVINGAPARTMENTS_MEDI float64
LIVINGAREA_MEDI float64
NONLIVINGAPARTMENTS_MEDI float64
NONLIVINGAREA_MEDI float64
FONDKAPREMONT_MODE object
HOUSETYPE_MODE object
TOTALAREA_MODE float64
WALLSMATERIAL_MODE object
EMERGENCYSTATE_MODE object
OBS_30_CNT_SOCIAL_CIRCLE float64
DEF_30_CNT_SOCIAL_CIRCLE float64
OBS_60_CNT_SOCIAL_CIRCLE float64
DEF_60_CNT_SOCIAL_CIRCLE float64
DAYS_LAST_PHONE_CHANGE float64
FLAG_DOCUMENT_2 int64
FLAG_DOCUMENT_3 int64
FLAG_DOCUMENT_4 int64
FLAG_DOCUMENT_5 int64
FLAG_DOCUMENT_6 int64
FLAG_DOCUMENT_7 int64
FLAG_DOCUMENT_8 int64
FLAG_DOCUMENT_9 int64
FLAG_DOCUMENT_10 int64
FLAG_DOCUMENT_11 int64
FLAG_DOCUMENT_12 int64
FLAG_DOCUMENT_13 int64
FLAG_DOCUMENT_14 int64
FLAG_DOCUMENT_15 int64
FLAG_DOCUMENT_16 int64
FLAG_DOCUMENT_17 int64
FLAG_DOCUMENT_18 int64
FLAG_DOCUMENT_19 int64
FLAG_DOCUMENT_20 int64
FLAG_DOCUMENT_21 int64
AMT_REQ_CREDIT_BUREAU_HOUR float64
AMT_REQ_CREDIT_BUREAU_DAY float64
AMT_REQ_CREDIT_BUREAU_WEEK float64
AMT_REQ_CREDIT_BUREAU_MON float64
AMT_REQ_CREDIT_BUREAU_QRT float64
AMT_REQ_CREDIT_BUREAU_YEAR float64
SK_ID_CURR int64

In [65]:
app_train.dtypes.value_counts()

float64    83
object     17
int64      12
Name: count, dtype: int64

In [54]:
app_train[app_train['CODE_GENDER'] == 'XNA']

,Unnamed: 0,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_CURR
30847,30847,0,Revolving loans,XNA,N,Y,2,157500.0,270000.0,13500.0,...,0,0,0,0.0,0.0,0.0,3.0,0.0,4.0,274295
66692,66692,0,Revolving loans,XNA,N,Y,1,135000.0,405000.0,20250.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,85587
151498,151498,0,Revolving loans,XNA,Y,Y,0,247500.0,540000.0,27000.0,...,0,0,0,0.0,0.0,0.0,0.0,1.0,6.0,151127

In [55]:
#Drop weird gender
app_train = app_train[app_train['CODE_GENDER'] != 'XNA']

In [57]:
#Document has no meaning -> agg and skip cols
docs = [f for f in app_train.columns if 'FLAG_DOC' in f]
app_train['NEW_DOC_IND_AVG'] = app_train[docs].mean(axis=1)
app_train['NEW_DOC_IND_STD'] = app_train[docs].std(axis=1)
app_train['DOCUMENT_COUNT'] = app_train[docs].sum(axis=1)

#Drop flag document  
app_train = app_train.drop(app_train.filter(regex='^FLAG_DOCUMENT_\d+$').columns, axis = 1)

In [59]:
#Adding new features; percentages
app_train['DAYS_EMPLOYED_PERC'] = app_train['DAYS_EMPLOYED'] / app_train['DAYS_BIRTH']
app_train['INCOME_CREDIT_PERC'] = app_train['AMT_INCOME_TOTAL'] / app_train['AMT_CREDIT']
app_train['INCOME_PER_PERSON'] = app_train['AMT_INCOME_TOTAL'] / app_train['CNT_FAM_MEMBERS']
app_train['ANNUITY_INCOME_PERC'] = app_train['AMT_ANNUITY'] / app_train['AMT_INCOME_TOTAL']
app_train['PAYMENT_RATE'] = app_train['AMT_ANNUITY'] /app_train['AMT_CREDIT']
app_train['DEBT_BURDEN_PER_WORKING_DAY'] = app_train['PAYMENT_RATE'] / app_train['DAYS_EMPLOYED']
app_train['DEBT_BURDEN_PER_LIFE_DAY'] = app_train['PAYMENT_RATE'] / app_train['DAYS_BIRTH']
# ratio of the difference between the loan amount and the value of goods compared to the value of the goods
app_train['CREDIT_GOODS_PRICE_RATIO1'] = (app_train['AMT_CREDIT'] - app_train['AMT_GOODS_PRICE']) /  app_train['AMT_GOODS_PRICE']
# ratio of the difference between the loan amount and the value of goods compared to the loan amount
app_train['CREDIT_GOODS_PRICE_RATIO2'] = (app_train['AMT_CREDIT'] - app_train['AMT_GOODS_PRICE']) /  app_train['AMT_CREDIT']
app_train['DIFF_OBS_30_CNT_SOCIAL_CIRCLE_OBS_60_CNT_SOCIAL_CIRCLE'] = app_train['OBS_30_CNT_SOCIAL_CIRCLE'] - app_train['OBS_60_CNT_SOCIAL_CIRCLE']
app_train['DIFF_DEF_30_CNT_SOCIAL_CIRCLE_DEF_60_CNT_SOCIAL_CIRCLE'] = app_train['DEF_30_CNT_SOCIAL_CIRCLE'] - app_train['DEF_60_CNT_SOCIAL_CIRCLE']

In [60]:
#Separate working hours from off_hours: The same with prev_app
app_train["HOUR_APPR_PROCESS_START"] = app_train["HOUR_APPR_PROCESS_START"].replace([8,9,10,11,12,13,14,15,16,17], 'working_hours')
app_train["HOUR_APPR_PROCESS_START"] = app_train["HOUR_APPR_PROCESS_START"].replace([18,19,20,21,22,23,0,1,2,3,4,5,6,7], 'off_hours')

In [61]:
app_train['RATIO_AMT_GOODS_PRICE_TO_LIVINGAREA_AVG'] = app_train['AMT_GOODS_PRICE'] / app_train['LIVINGAREA_AVG']
app_train['RATIO_AMT_GOODS_PRICE_TO_LANDAREA_AVG'] = app_train['AMT_GOODS_PRICE'] / app_train['LANDAREA_AVG']
app_train['RATIO_AMT_GOODS_PRICE_TO_FLOORSMAX_AVG_AVG'] = app_train['AMT_GOODS_PRICE'] / app_train['FLOORSMAX_AVG']
app_train['RATIO_AMT_GOODS_PRICE_TO_LIVINGAPARTMENTS_AVG'] = app_train['AMT_GOODS_PRICE'] / app_train['LIVINGAPARTMENTS_AVG']
app_train['RATIO_AMT_GOODS_PRICE_TO_YEARS_BUILD_AVG'] = app_train['AMT_GOODS_PRICE'] / app_train['YEARS_BUILD_AVG'] 
app_train['RELIABILITY_IN_CUSTOMER_CITY'] = app_train['REG_CITY_NOT_LIVE_CITY'] + app_train['REG_CITY_NOT_WORK_CITY'] + app_train['REG_REGION_NOT_LIVE_REGION'] + app_train['REG_REGION_NOT_WORK_REGION'] + app_train['LIVE_CITY_NOT_WORK_CITY'] + app_train['LIVE_REGION_NOT_WORK_REGION']
app_train['SUM_CONTACTS'] = app_train['FLAG_MOBIL'] + app_train['FLAG_EMP_PHONE'] + app_train['FLAG_WORK_PHONE'] + app_train['FLAG_CONT_MOBILE'] + app_train['FLAG_PHONE'] + app_train['FLAG_EMAIL']

#Some features from bureau 
app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU'] = app_train[['AMT_REQ_CREDIT_BUREAU_DAY',
                                          'AMT_REQ_CREDIT_BUREAU_HOUR',
                                          'AMT_REQ_CREDIT_BUREAU_WEEK',
                                          'AMT_REQ_CREDIT_BUREAU_MON',
                                          'AMT_REQ_CREDIT_BUREAU_QRT',
                                          'AMT_REQ_CREDIT_BUREAU_YEAR']].sum(axis=1)
    
app_train['PCTG_ENQUIRIES_HOUR'] = app_train['AMT_REQ_CREDIT_BUREAU_HOUR'] / app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU']
app_train['PCTG_ENQUIRIES_DAY'] = app_train['AMT_REQ_CREDIT_BUREAU_DAY'] / app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU']
app_train['PCTG_ENQUIRIES_WEEK'] = app_train['AMT_REQ_CREDIT_BUREAU_WEEK'] / app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU']
app_train['PCTG_ENQUIRIES_MON'] = app_train['AMT_REQ_CREDIT_BUREAU_MON'] / app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU']
app_train['PCTG_ENQUIRIES_QRT'] = app_train['AMT_REQ_CREDIT_BUREAU_QRT'] / app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU']
app_train['PCTG_ENQUIRIES_YEAR'] = app_train['AMT_REQ_CREDIT_BUREAU_YEAR'] / app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU']

In [ ]:
cols_to_drop = ["EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3","REG_CITY_NOT_LIVE_CITY","REG_CITY_NOT_WORK_CITY","REG_REGION_NOT_LIVE_REGION","REG_REGION_NOT_WORK_REGION","LIVE_CITY_NOT_WORK_CITY", "LIVE_REGION_NOT_WORK_REGION", "FLAG_MOBIL","FLAG_EMP_PHONE","FLAG_WORK_PHONE","FLAG_CONT_MOBILE","FLAG_PHONE","FLAG_EMAIL", "AMT_REQ_CREDIT_BUREAU_DAY", "AMT_REQ_CREDIT_BUREAU_HOUR", "AMT_REQ_CREDIT_BUREAU_MON", "AMT_REQ_CREDIT_BUREAU_WEEK"]
app_train.drop(columns=cols_to_drop, inplace=True)
#app_train.drop("index", axis = 1, inplace =  True)

In [66]:
app_train['CODE_GENDER'].dtype

dtype('O')

In [67]:
app_train.shape

(246006, 112)

In [68]:
lbe = LabelEncoder()
for col in ['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY']:
    app_train[col] = lbe.fit_transform(app_train[col])

In [69]:
app_train, cat_cols = OHE(app_train, nan_as_category)

In [70]:
cat_cols

['NAME_CONTRACT_TYPE_Cash loans',
 'NAME_CONTRACT_TYPE_Revolving loans',
 'NAME_CONTRACT_TYPE_nan',
 'NAME_TYPE_SUITE_Children',
 'NAME_TYPE_SUITE_Family',
 'NAME_TYPE_SUITE_Group of people',
 'NAME_TYPE_SUITE_Other_A',
 'NAME_TYPE_SUITE_Other_B',
 'NAME_TYPE_SUITE_Spouse, partner',
 'NAME_TYPE_SUITE_Unaccompanied',
 'NAME_TYPE_SUITE_nan',
 'NAME_INCOME_TYPE_Businessman',
 'NAME_INCOME_TYPE_Commercial associate',
 'NAME_INCOME_TYPE_Maternity leave',
 'NAME_INCOME_TYPE_Pensioner',
 'NAME_INCOME_TYPE_State servant',
 'NAME_INCOME_TYPE_Student',
 'NAME_INCOME_TYPE_Unemployed',
 'NAME_INCOME_TYPE_Working',
 'NAME_INCOME_TYPE_nan',
 'NAME_EDUCATION_TYPE_Academic degree',
 'NAME_EDUCATION_TYPE_Higher education',
 'NAME_EDUCATION_TYPE_Incomplete higher',
 'NAME_EDUCATION_TYPE_Lower secondary',
 'NAME_EDUCATION_TYPE_Secondary / secondary special',
 'NAME_EDUCATION_TYPE_nan',
 'NAME_FAMILY_STATUS_Civil marriage',
 'NAME_FAMILY_STATUS_Married',
 'NAME_FAMILY_STATUS_Separated',
 'NAME_FAMILY_STATUS_Single / not married',
 'NAME_FAMILY_STATUS_Unknown',
 'NAME_FAMILY_STATUS_Widow',
 'NAME_FAMILY_STATUS_nan',
 'NAME_HOUSING_TYPE_Co-op apartment',
 'NAME_HOUSING_TYPE_House / apartment',
 'NAME_HOUSING_TYPE_Municipal apartment',
 'NAME_HOUSING_TYPE_Office apartment',
 'NAME_HOUSING_TYPE_Rented apartment',
 'NAME_HOUSING_TYPE_With parents',
 'NAME_HOUSING_TYPE_nan',
 'OCCUPATION_TYPE_Accountants',
 'OCCUPATION_TYPE_Cleaning staff',
 'OCCUPATION_TYPE_Cooking staff',
 'OCCUPATION_TYPE_Core staff',
 'OCCUPATION_TYPE_Drivers',
 'OCCUPATION_TYPE_HR staff',
 'OCCUPATION_TYPE_High skill tech staff',
 'OCCUPATION_TYPE_IT staff',
 'OCCUPATION_TYPE_Laborers',
 'OCCUPATION_TYPE_Low-skill Laborers',
 'OCCUPATION_TYPE_Managers',
 'OCCUPATION_TYPE_Medicine staff',
 'OCCUPATION_TYPE_Private service staff',
 'OCCUPATION_TYPE_Realty agents',
 'OCCUPATION_TYPE_Sales staff',
 'OCCUPATION_TYPE_Secretaries',
 'OCCUPATION_TYPE_Security staff',
 'OCCUPATION_TYPE_Waiters/barmen staff',
 'OCCUPATION_TYPE_nan',
 'WEEKDAY_APPR_PROCESS_START_FRIDAY',
 'WEEKDAY_APPR_PROCESS_START_MONDAY',
 'WEEKDAY_APPR_PROCESS_START_SATURDAY',
 'WEEKDAY_APPR_PROCESS_START_SUNDAY',
 'WEEKDAY_APPR_PROCESS_START_THURSDAY',
 'WEEKDAY_APPR_PROCESS_START_TUESDAY',
 'WEEKDAY_APPR_PROCESS_START_WEDNESDAY',
 'WEEKDAY_APPR_PROCESS_START_nan',
 'HOUR_APPR_PROCESS_START_off_hours',
 'HOUR_APPR_PROCESS_START_working_hours',
 'HOUR_APPR_PROCESS_START_nan',
 'ORGANIZATION_TYPE_Advertising',
 'ORGANIZATION_TYPE_Agriculture',
 'ORGANIZATION_TYPE_Bank',
 'ORGANIZATION_TYPE_Business Entity Type 1',
 'ORGANIZATION_TYPE_Business Entity Type 2',
 'ORGANIZATION_TYPE_Business Entity Type 3',
 'ORGANIZATION_TYPE_Cleaning',
 'ORGANIZATION_TYPE_Construction',
 'ORGANIZATION_TYPE_Culture',
 'ORGANIZATION_TYPE_Electricity',
 'ORGANIZATION_TYPE_Emergency',
 'ORGANIZATION_TYPE_Government',
 'ORGANIZATION_TYPE_Hotel',
 'ORGANIZATION_TYPE_Housing',
 'ORGANIZATION_TYPE_Industry: type 1',
 'ORGANIZATION_TYPE_Industry: type 10',
 'ORGANIZATION_TYPE_Industry: type 11',
 'ORGANIZATION_TYPE_Industry: type 12',
 'ORGANIZATION_TYPE_Industry: type 13',
 'ORGANIZATION_TYPE_Industry: type 2',
 'ORGANIZATION_TYPE_Industry: type 3',
 'ORGANIZATION_TYPE_Industry: type 4',
 'ORGANIZATION_TYPE_Industry: type 5',
 'ORGANIZATION_TYPE_Industry: type 6',
 'ORGANIZATION_TYPE_Industry: type 7',
 'ORGANIZATION_TYPE_Industry: type 8',
 'ORGANIZATION_TYPE_Industry: type 9',
 'ORGANIZATION_TYPE_Insurance',
 'ORGANIZATION_TYPE_Kindergarten',
 'ORGANIZATION_TYPE_Legal Services',
 'ORGANIZATION_TYPE_Medicine',
 'ORGANIZATION_TYPE_Military',
 'ORGANIZATION_TYPE_Mobile',
 'ORGANIZATION_TYPE_Other',
 'ORGANIZATION_TYPE_Police',
 'ORGANIZATION_TYPE_Postal',
 'ORGANIZATION_TYPE_Realtor',
 'ORGANIZATION_TYPE_Religion',
 'ORGANIZATION_TYPE_Restaurant',
 'ORGANIZATION_TYPE_School',
 'ORGANIZATION_TYPE_Security',
 'ORGANIZATION_TYPE_Security Ministries',
 'ORGANIZATION_TYPE_Self-employed',
 'ORGANIZATION_TYPE_Services',
 'ORGANIZATION_TYPE_Telecom',
 'ORGANIZATION_TYPE_Trade: type 1',
 'ORGANIZATION_TYPE_Trade: type 2',
 'ORGANIZATION_TYPE_Trade: type 3',
 'ORGANIZATION_TYPE_Trade: type 4',
 'ORGANIZATION_TYPE_Trade: type 5',
 'ORGANIZATION_TYPE_Trade: type 6',
 'ORGANIZATION_TYPE_Trade: type 7',
 'ORGANIZATION_TYPE_Transport: type 1',
 'ORGANIZATION_TYPE_Transport: type 2',
 'ORGANIZATION_TYPE_Transport: type 3',
 'ORGANIZATION_TYPE_Transport: type 4',
 'ORGANIZATION_TYPE_University',
 'ORGANIZATION_TYPE_XNA',
 'ORGANIZATION_TYPE_nan',
 'FONDKAPREMONT_MODE_not specified',
 'FONDKAPREMONT_MODE_org spec account',
 'FONDKAPREMONT_MODE_reg oper account',
 'FONDKAPREMONT_MODE_reg oper spec account',
 'FONDKAPREMONT_MODE_nan',
 'HOUSETYPE_MODE_block of flats',
 'HOUSETYPE_MODE_specific housing',
 'HOUSETYPE_MODE_terraced house',
 'HOUSETYPE_MODE_nan',
 'WALLSMATERIAL_MODE_Block',
 'WALLSMATERIAL_MODE_Mixed',
 'WALLSMATERIAL_MODE_Monolithic',
 'WALLSMATERIAL_MODE_Others',
 'WALLSMATERIAL_MODE_Panel',
 'WALLSMATERIAL_MODE_Stone, brick',
 'WALLSMATERIAL_MODE_Wooden',
 'WALLSMATERIAL_MODE_nan',
 'EMERGENCYSTATE_MODE_No',
 'EMERGENCYSTATE_MODE_Yes',
 'EMERGENCYSTATE_MODE_nan']

In [71]:
app_train.shape

(246006, 247)