In [1]:
import pandas as pd
import numpy as np 
import os 
from sklearn.preprocessing import LabelEncoder

In [2]:
app_train = pd.read_csv("../data/dseb63_application_train.csv")

In [142]:
app_train.iloc[10:20]

,Unnamed: 0,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_CURR
10,10,0,Cash loans,M,Y,Y,0,157500.0,299772.0,20160.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,159669
11,11,0,Revolving loans,F,N,Y,1,81000.0,270000.0,13500.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,211972
12,12,0,Revolving loans,F,N,Y,0,112500.0,157500.0,7875.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,152919
13,13,0,Cash loans,F,N,Y,1,90000.0,544491.0,17563.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,67603
14,14,0,Revolving loans,M,Y,Y,0,135000.0,427500.0,21375.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,290315
15,15,0,Cash loans,F,Y,Y,1,202500.0,1132573.5,37561.5,...,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0,57291
16,16,0,Cash loans,F,N,Y,0,83250.0,239850.0,23850.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,170817
17,17,0,Cash loans,F,N,Y,0,90000.0,225000.0,11074.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,71586
18,18,0,Cash loans,M,N,Y,1,112500.0,327024.0,23827.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,205758
19,19,0,Cash loans,M,Y,Y,0,270000.0,790830.0,57676.5,...,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0,133615

In [143]:
app_train.columns

Index(['Unnamed: 0', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21',
       'AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY',
       'AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_MON',
       'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR',
       'SK_ID_CURR'],
      dtype='object', length=123)

In [144]:
app_train['TARGET'].value_counts()

TARGET
0    226133
1     19876
Name: count, dtype: int64

In [145]:
app_train.shape

(246009, 123)

In [146]:
app_train['SK_ID_CURR'].nunique()

246009

In [147]:
def display_missing_data_info(dataframe, ascending=False):
    missing_values_count = dataframe.isnull().sum()
    missing_values_percentage = (dataframe.isnull().mean() * 100)
    missing_data = pd.DataFrame({
        'Missing Values': missing_values_count,
        'Percentage (%)': missing_values_percentage
    })
    
    missing_data = missing_data[missing_data['Missing Values'] > 0]
    
    sorted_missing_data = missing_data.sort_values(by='Missing Values', ascending=ascending)

    #print(sorted_missing_data)
    return sorted_missing_data

In [131]:
display_missing_data_info(app_train, ascending=False)

                          Missing Values  Percentage (%)
COMMONAREA_MEDI                   171930       69.887687
COMMONAREA_AVG                    171930       69.887687
COMMONAREA_MODE                   171930       69.887687
NONLIVINGAPARTMENTS_MEDI          170869       69.456402
NONLIVINGAPARTMENTS_MODE          170869       69.456402
...                                  ...             ...
EXT_SOURCE_2                         529        0.215033
AMT_GOODS_PRICE                      224        0.091054
AMT_ANNUITY                           10        0.004065
DAYS_LAST_PHONE_CHANGE                 1        0.000406
CNT_FAM_MEMBERS                        1        0.000406

[67 rows x 2 columns]

In [132]:
nan_as_category = True

In [133]:
def OHE(df, nan_as_category = True):
    original_cols = list(df.columns)
    categorical_columns = [col for col in df.columns if df[col].dtype == 'object']
    df = pd.get_dummies(df, columns= categorical_columns,
                        dummy_na= nan_as_category)
    new_columns = [c for c in df.columns if c not in original_cols]
    return df, new_columns

In [134]:
for col in app_train.columns: 
    print(col, app_train[col].dtype)

Unnamed: 0 int64
TARGET int64
NAME_CONTRACT_TYPE object
CODE_GENDER object
FLAG_OWN_CAR object
FLAG_OWN_REALTY object
CNT_CHILDREN int64
AMT_INCOME_TOTAL float64
AMT_CREDIT float64
AMT_ANNUITY float64
AMT_GOODS_PRICE float64
NAME_TYPE_SUITE object
NAME_INCOME_TYPE object
NAME_EDUCATION_TYPE object
NAME_FAMILY_STATUS object
NAME_HOUSING_TYPE object
REGION_POPULATION_RELATIVE float64
DAYS_BIRTH int64
DAYS_EMPLOYED int64
DAYS_REGISTRATION float64
DAYS_ID_PUBLISH int64
OWN_CAR_AGE float64
FLAG_MOBIL int64
FLAG_EMP_PHONE int64
FLAG_WORK_PHONE int64
FLAG_CONT_MOBILE int64
FLAG_PHONE int64
FLAG_EMAIL int64
OCCUPATION_TYPE object
CNT_FAM_MEMBERS float64
REGION_RATING_CLIENT int64
REGION_RATING_CLIENT_W_CITY int64
WEEKDAY_APPR_PROCESS_START object
HOUR_APPR_PROCESS_START int64
REG_REGION_NOT_LIVE_REGION int64
REG_REGION_NOT_WORK_REGION int64
LIVE_REGION_NOT_WORK_REGION int64
REG_CITY_NOT_LIVE_CITY int64
REG_CITY_NOT_WORK_CITY int64
LIVE_CITY_NOT_WORK_CITY int64
ORGANIZATION_TYPE object
EXT_SOURCE_1 float64
EXT_SOURCE_2 float64
EXT_SOURCE_3 float64
APARTMENTS_AVG float64
BASEMENTAREA_AVG float64
YEARS_BEGINEXPLUATATION_AVG float64
YEARS_BUILD_AVG float64
COMMONAREA_AVG float64
ELEVATORS_AVG float64
ENTRANCES_AVG float64
FLOORSMAX_AVG float64
FLOORSMIN_AVG float64
LANDAREA_AVG float64
LIVINGAPARTMENTS_AVG float64
LIVINGAREA_AVG float64
NONLIVINGAPARTMENTS_AVG float64
NONLIVINGAREA_AVG float64
APARTMENTS_MODE float64
BASEMENTAREA_MODE float64
YEARS_BEGINEXPLUATATION_MODE float64
YEARS_BUILD_MODE float64
COMMONAREA_MODE float64
ELEVATORS_MODE float64
ENTRANCES_MODE float64
FLOORSMAX_MODE float64
FLOORSMIN_MODE float64
LANDAREA_MODE float64
LIVINGAPARTMENTS_MODE float64
LIVINGAREA_MODE float64
NONLIVINGAPARTMENTS_MODE float64
NONLIVINGAREA_MODE float64
APARTMENTS_MEDI float64
BASEMENTAREA_MEDI float64
YEARS_BEGINEXPLUATATION_MEDI float64
YEARS_BUILD_MEDI float64
COMMONAREA_MEDI float64
ELEVATORS_MEDI float64
ENTRANCES_MEDI float64
FLOORSMAX_MEDI float64
FLOORSMIN_MEDI float64
LANDAREA_MEDI float64
LIVINGAPARTMENTS_MEDI float64
LIVINGAREA_MEDI float64
NONLIVINGAPARTMENTS_MEDI float64
NONLIVINGAREA_MEDI float64
FONDKAPREMONT_MODE object
HOUSETYPE_MODE object
TOTALAREA_MODE float64
WALLSMATERIAL_MODE object
EMERGENCYSTATE_MODE object
OBS_30_CNT_SOCIAL_CIRCLE float64
DEF_30_CNT_SOCIAL_CIRCLE float64
OBS_60_CNT_SOCIAL_CIRCLE float64
DEF_60_CNT_SOCIAL_CIRCLE float64
DAYS_LAST_PHONE_CHANGE float64
FLAG_DOCUMENT_2 int64
FLAG_DOCUMENT_3 int64
FLAG_DOCUMENT_4 int64
FLAG_DOCUMENT_5 int64
FLAG_DOCUMENT_6 int64
FLAG_DOCUMENT_7 int64
FLAG_DOCUMENT_8 int64
FLAG_DOCUMENT_9 int64
FLAG_DOCUMENT_10 int64
FLAG_DOCUMENT_11 int64
FLAG_DOCUMENT_12 int64
FLAG_DOCUMENT_13 int64
FLAG_DOCUMENT_14 int64
FLAG_DOCUMENT_15 int64
FLAG_DOCUMENT_16 int64
FLAG_DOCUMENT_17 int64
FLAG_DOCUMENT_18 int64
FLAG_DOCUMENT_19 int64
FLAG_DOCUMENT_20 int64
FLAG_DOCUMENT_21 int64
AMT_REQ_CREDIT_BUREAU_HOUR float64
AMT_REQ_CREDIT_BUREAU_DAY float64
AMT_REQ_CREDIT_BUREAU_WEEK float64
AMT_REQ_CREDIT_BUREAU_MON float64
AMT_REQ_CREDIT_BUREAU_QRT float64
AMT_REQ_CREDIT_BUREAU_YEAR float64
SK_ID_CURR int64

In [135]:
app_train.dtypes.value_counts()

float64    65
int64      42
object     16
Name: count, dtype: int64

In [136]:
app_train[app_train['CODE_GENDER'] == 'XNA']

,Unnamed: 0,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_CURR
30847,30847,0,Revolving loans,XNA,N,Y,2,157500.0,270000.0,13500.0,...,0,0,0,0.0,0.0,0.0,3.0,0.0,4.0,274295
66692,66692,0,Revolving loans,XNA,N,Y,1,135000.0,405000.0,20250.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,85587
151498,151498,0,Revolving loans,XNA,Y,Y,0,247500.0,540000.0,27000.0,...,0,0,0,0.0,0.0,0.0,0.0,1.0,6.0,151127

In [87]:
#Drop weird gender
#app_train = app_train[app_train['CODE_GENDER'] != 'XNA']

In [137]:
app_train['CNT_CHILDREN'].value_counts()
#Weird, the number of people with more than 7 is pretty strange -> people with more than 7 children are agg grouped together

CNT_CHILDREN
0     172333
1      48929
2      21410
3       2911
4        327
5         64
6         19
7          5
14         3
9          2
10         2
19         2
11         1
8          1
Name: count, dtype: int64

In [89]:
app_train['CNT_CHILDREN'] = app_train['CNT_CHILDREN'].replace([8,9,10,11,14,19],7)

In [90]:
#For name type suite, group other_b with other_a, fill nan with unaccompanied
app_train['NAME_TYPE_SUITE'].value_counts()

NAME_TYPE_SUITE
Unaccompanied      198740
Family              32145
Spouse, partner      9109
Children             2621
Other_B              1412
Other_A               713
Group of people       220
Name: count, dtype: int64

In [91]:
app_train['NAME_TYPE_SUITE'].isnull().sum()

1046

In [92]:
app_train['NAME_TYPE_SUITE'] = app_train['NAME_TYPE_SUITE'].replace(['Other_A', 'Other_B'], 'Other')
app_train['NAME_TYPE_SUITE'] = app_train['NAME_TYPE_SUITE'].fillna('Unaccompanied')

In [93]:
#map education type to int -> output is already converted 
app_train['NAME_EDUCATION_TYPE'].value_counts()

NAME_EDUCATION_TYPE
Secondary / secondary special    174521
Higher education                  60060
Incomplete higher                  8210
Lower secondary                    3085
Academic degree                     130
Name: count, dtype: int64

In [94]:
# Converted so 0 is close to 23
app_train['sin_HOUR_APPR_PROCESS_START'] = np.sin(2 * np.pi * app_train['HOUR_APPR_PROCESS_START'] / 24)
app_train['cos_HOUR_APPR_PROCESS_START'] = np.cos(2 * np.pi * app_train['HOUR_APPR_PROCESS_START'] / 24)

In [96]:
#Drop unknown family status
app_train['NAME_FAMILY_STATUS'].value_counts()

NAME_FAMILY_STATUS
Married                 157318
Single / not married     36271
Civil marriage           23841
Separated                15805
Widow                    12770
Unknown                      1
Name: count, dtype: int64

In [97]:
app_train = app_train[app_train['NAME_FAMILY_STATUS'] != 'Unknown']

In [99]:
def group_organization_type(org_type):
    if 'Trade' in org_type:
        return 'Trade'
    elif 'Industry' in org_type:
        return 'Industry'
    elif 'Business' in org_type:
        return 'Business Entity'
    elif 'Transport' in org_type:
        return 'Transport'
    else:
        return org_type

In [100]:
app_train['ORGANIZATION_TYPE'] = app_train['ORGANIZATION_TYPE'].replace('XNA', 'Unemployed')
app_train['ORGANIZATION_TYPE'] = app_train['ORGANIZATION_TYPE'].apply(group_organization_type)

In [101]:
#Drop outlier with car_age > 91, like who lives that long and still make loans;fillna too 
app_train = app_train[app_train['OWN_CAR_AGE'] != 91.0]
app_train['OWN_CAR_AGE'] = app_train['OWN_CAR_AGE'].fillna(0)

In [102]:
app_train = app_train[app_train['FLAG_MOBIL'] == 1]

In [103]:
#New feat from EXT 
app_train['EXT_SOURCE_SUM'] = app_train[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']].sum(axis=1, skipna=True)
app_train['EXT_SOURCE_PROD'] = app_train[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']].prod(axis=1, skipna=True)
app_train['EXT_SOURCE_MEAN'] = app_train[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']].mean(axis=1, skipna=True)
app_train['EXT_SOURCE_STD'] = app_train[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']].std(axis=1, skipna=True)
app_train['EXT_SOURCE_MISSING_VALUES'] = app_train[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']].isna().sum(axis=1)

In [104]:
app_train['AMT_REQ_CREDIT_BUREAU_YEAR'] = app_train['AMT_REQ_CREDIT_BUREAU_YEAR'].fillna(value = app_train['AMT_REQ_CREDIT_BUREAU_YEAR'].mean())

In [105]:
#Document has no meaning -> agg and skip cols
docs = [f for f in app_train.columns if 'FLAG_DOC' in f]
app_train['NEW_DOC_IND_AVG'] = app_train[docs].mean(axis=1)
app_train['NEW_DOC_IND_STD'] = app_train[docs].std(axis=1)
app_train['DOCUMENT_COUNT'] = app_train[docs].sum(axis=1)
app_train['NEW_DOC_IND_KURT'] = app_train[docs].kurtosis(axis=1)
app_train['HAS_DOCUMENT'] = app_train[docs].max(axis=1)
#Drop flag document  
app_train = app_train.drop(app_train.filter(regex='^FLAG_DOCUMENT_\d+$').columns, axis = 1)

<>:9: SyntaxWarning: invalid escape sequence '\d'
<>:9: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_258590/1412365583.py:9: SyntaxWarning: invalid escape sequence '\d'
  app_train = app_train.drop(app_train.filter(regex='^FLAG_DOCUMENT_\d+$').columns, axis = 1)

In [106]:
#New feat from income and inquiry 
app_train['TOTALAREA_MODE'] = app_train['TOTALAREA_MODE'] ** (1/3)
med_income = app_train.groupby(['ORGANIZATION_TYPE', 'NAME_EDUCATION_TYPE'])['AMT_INCOME_TOTAL'].transform('median')
med_income2 = app_train.groupby('ORGANIZATION_TYPE')['AMT_INCOME_TOTAL'].transform('median')
app_train['income_ratio'] = app_train['AMT_INCOME_TOTAL'] / med_income
app_train['income_ratio2'] = app_train['AMT_INCOME_TOTAL'] / med_income2
app_train['true_annuity_div_income'] = app_train['AMT_ANNUITY'] / med_income
app_train['true_annuity_div_income2'] = app_train['AMT_ANNUITY'] / med_income2
app_train['true_income_div_totalarea'] = med_income / app_train['TOTALAREA_MODE']
app_train['true_income_div_totalarea2'] = med_income2 / app_train['TOTALAREA_MODE']

#New features from bureau 
app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU'] = app_train[['AMT_REQ_CREDIT_BUREAU_DAY',
                                        'AMT_REQ_CREDIT_BUREAU_HOUR',
                                        'AMT_REQ_CREDIT_BUREAU_WEEK',
                                        'AMT_REQ_CREDIT_BUREAU_MON',
                                        'AMT_REQ_CREDIT_BUREAU_QRT',
                                        'AMT_REQ_CREDIT_BUREAU_YEAR']].sum(axis=1)

app_train['PCTG_ENQUIRIES_HOUR'] = app_train['AMT_REQ_CREDIT_BUREAU_HOUR'] / app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU']
app_train['PCTG_ENQUIRIES_DAY'] = app_train['AMT_REQ_CREDIT_BUREAU_DAY'] / app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU']
app_train['PCTG_ENQUIRIES_WEEK'] = app_train['AMT_REQ_CREDIT_BUREAU_WEEK'] / app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU']
app_train['PCTG_ENQUIRIES_MON'] = app_train['AMT_REQ_CREDIT_BUREAU_MON'] / app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU']
app_train['PCTG_ENQUIRIES_QRT'] = app_train['AMT_REQ_CREDIT_BUREAU_QRT'] / app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU']
app_train['PCTG_ENQUIRIES_YEAR'] = app_train['AMT_REQ_CREDIT_BUREAU_YEAR'] / app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU']

In [107]:
#Adding new features; percentages
app_train['DAYS_EMPLOYED_PERC'] = app_train['DAYS_EMPLOYED'] / app_train['DAYS_BIRTH']
app_train['INCOME_CREDIT_PERC'] = app_train['AMT_INCOME_TOTAL'] / app_train['AMT_CREDIT']
app_train['INCOME_PER_PERSON'] = app_train['AMT_INCOME_TOTAL'] / app_train['CNT_FAM_MEMBERS']
app_train['ANNUITY_INCOME_PERC'] = app_train['AMT_ANNUITY'] / app_train['AMT_INCOME_TOTAL']
app_train['PAYMENT_RATE'] = app_train['AMT_ANNUITY'] /app_train['AMT_CREDIT']
app_train['DEBT_BURDEN_PER_WORKING_DAY'] = app_train['PAYMENT_RATE'] / app_train['DAYS_EMPLOYED']
app_train['DEBT_BURDEN_PER_LIFE_DAY'] = app_train['PAYMENT_RATE'] / app_train['DAYS_BIRTH']
# ratio of the difference between the loan amount and the value of goods compared to the value of the goods
app_train['CREDIT_GOODS_PRICE_RATIO1'] = (app_train['AMT_CREDIT'] - app_train['AMT_GOODS_PRICE']) /  app_train['AMT_GOODS_PRICE']
# ratio of the difference between the loan amount and the value of goods compared to the loan amount
app_train['CREDIT_GOODS_PRICE_RATIO2'] = (app_train['AMT_CREDIT'] - app_train['AMT_GOODS_PRICE']) /  app_train['AMT_CREDIT']
app_train['DIFF_OBS_30_CNT_SOCIAL_CIRCLE_OBS_60_CNT_SOCIAL_CIRCLE'] = app_train['OBS_30_CNT_SOCIAL_CIRCLE'] - app_train['OBS_60_CNT_SOCIAL_CIRCLE']
app_train['DIFF_DEF_30_CNT_SOCIAL_CIRCLE_DEF_60_CNT_SOCIAL_CIRCLE'] = app_train['DEF_30_CNT_SOCIAL_CIRCLE'] - app_train['DEF_60_CNT_SOCIAL_CIRCLE']

In [108]:
#Separate working hours from off_hours: The same with prev_app
app_train["HOUR_APPR_PROCESS_START"] = app_train["HOUR_APPR_PROCESS_START"].replace([8,9,10,11,12,13,14,15,16,17], 'working_hours')
app_train["HOUR_APPR_PROCESS_START"] = app_train["HOUR_APPR_PROCESS_START"].replace([18,19,20,21,22,23,0,1,2,3,4,5,6,7], 'off_hours')

In [109]:
missing_columns = ['APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG',
                'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG',
                'FLOORSMAX_AVG', 'FLOORSMIN_AVG', 'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG',
                'LIVINGAREA_AVG', 'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG']
app_train['MISSING_GRADINGS'] = app_train[missing_columns].isna().sum(axis=1)

In [110]:
# some random numerical transformation
app_train['LIVINGAREA_AVG'] = app_train['LIVINGAREA_AVG'] ** (1/3.5)
app_train['NONLIVINGAPARTMENTS_AVG'] = app_train['NONLIVINGAPARTMENTS_AVG'] ** (1/7)
app_train['NONLIVINGAREA_AVG'] = app_train['NONLIVINGAREA_AVG'] ** (1/5)
app_train['OBS_30_CNT_SOCIAL_CIRCLE'] = app_train['OBS_30_CNT_SOCIAL_CIRCLE'] ** (1/7)
app_train['DEF_30_CNT_SOCIAL_CIRCLE'] = app_train['DEF_30_CNT_SOCIAL_CIRCLE'] ** (1/7)
app_train['OBS_60_CNT_SOCIAL_CIRCLE'] = app_train['OBS_60_CNT_SOCIAL_CIRCLE'] ** (1/7)
app_train['DEF_60_CNT_SOCIAL_CIRCLE'] = app_train['DEF_60_CNT_SOCIAL_CIRCLE'] ** (1/7)
app_train['REGION_POPULATION_RELATIVE'] = np.sqrt(app_train['REGION_POPULATION_RELATIVE'])
app_train['APARTMENTS_AVG'] = np.log1p(50 * app_train['APARTMENTS_AVG'])
app_train['YEARS_BEGINEXPLUATATION_AVG'] = app_train['YEARS_BEGINEXPLUATATION_AVG'] ** 30
app_train['YEARS_BUILD_AVG'] = app_train['YEARS_BUILD_AVG'] ** 3
app_train['COMMONAREA_AVG'] = app_train['COMMONAREA_AVG'] ** (-1/200)
app_train['ELEVATORS_AVG'] = app_train['ELEVATORS_AVG'] ** (1/40)
app_train['ENTRANCES_AVG'] = app_train['ENTRANCES_AVG'] ** (1/3)
app_train['FLOORSMAX_AVG'] = app_train['FLOORSMAX_AVG'] ** (1/2.5)
app_train['FLOORSMIN_AVG'] = app_train['FLOORSMIN_AVG'] ** (1/2.2)
app_train['LANDAREA_AVG'] = app_train['LANDAREA_AVG'] ** (1/5)
app_train['LIVINGAPARTMENTS_AVG'] = app_train['LIVINGAPARTMENTS_AVG'] ** (1/3)

In [111]:
#Some new ratio 
app_train['RATIO_AMT_GOODS_PRICE_TO_LIVINGAREA_AVG'] = app_train['AMT_GOODS_PRICE'] / app_train['LIVINGAREA_AVG']
app_train['RATIO_AMT_GOODS_PRICE_TO_LANDAREA_AVG'] = app_train['AMT_GOODS_PRICE'] / app_train['LANDAREA_AVG']
app_train['RATIO_AMT_GOODS_PRICE_TO_FLOORSMAX_AVG_AVG'] = app_train['AMT_GOODS_PRICE'] / app_train['FLOORSMAX_AVG']
app_train['RATIO_AMT_GOODS_PRICE_TO_LIVINGAPARTMENTS_AVG'] = app_train['AMT_GOODS_PRICE'] / app_train['LIVINGAPARTMENTS_AVG']
app_train['RATIO_AMT_GOODS_PRICE_TO_YEARS_BUILD_AVG'] = app_train['AMT_GOODS_PRICE'] / app_train['YEARS_BUILD_AVG'] 
app_train['RELIABILITY_IN_CUSTOMER_CITY'] = app_train['REG_CITY_NOT_LIVE_CITY'] + app_train['REG_CITY_NOT_WORK_CITY'] + app_train['REG_REGION_NOT_LIVE_REGION'] + app_train['REG_REGION_NOT_WORK_REGION'] + app_train['LIVE_CITY_NOT_WORK_CITY'] + app_train['LIVE_REGION_NOT_WORK_REGION']
app_train['SUM_CONTACTS'] = app_train['FLAG_MOBIL'] + app_train['FLAG_EMP_PHONE'] + app_train['FLAG_WORK_PHONE'] + app_train['FLAG_CONT_MOBILE'] + app_train['FLAG_PHONE'] + app_train['FLAG_EMAIL']

In [112]:
cols_to_drop = ["EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3","REG_CITY_NOT_LIVE_CITY","REG_CITY_NOT_WORK_CITY","REG_REGION_NOT_LIVE_REGION","REG_REGION_NOT_WORK_REGION","LIVE_CITY_NOT_WORK_CITY", "LIVE_REGION_NOT_WORK_REGION", "FLAG_MOBIL","FLAG_EMP_PHONE","FLAG_WORK_PHONE","FLAG_CONT_MOBILE","FLAG_PHONE","FLAG_EMAIL", "AMT_REQ_CREDIT_BUREAU_DAY", "AMT_REQ_CREDIT_BUREAU_HOUR", "AMT_REQ_CREDIT_BUREAU_MON", "AMT_REQ_CREDIT_BUREAU_WEEK"]
app_train.drop(columns=cols_to_drop, inplace=True)
#app_train.drop("index", axis = 1, inplace =  True)

In [113]:
app_train['CODE_GENDER'].dtype

dtype('O')

In [114]:
app_train.shape

(246003, 128)

In [115]:
app_train.dtypes.value_counts()

float64    97
object     17
int64      14
Name: count, dtype: int64

In [3]:
def RELU(series):
    return series.apply(lambda x: max(0, x))

In [4]:
#Combine into one cell 

app_train['CODE_GENDER'].replace('XNA',np.nan, inplace=True)
app_train['CNT_CHILDREN'] = app_train['CNT_CHILDREN'].replace([8,9,10,11,14,19],7)
app_train['sin_HOUR_APPR_PROCESS_START'] = np.sin(2 * np.pi * app_train['HOUR_APPR_PROCESS_START'] / 24)
app_train['cos_HOUR_APPR_PROCESS_START'] = np.cos(2 * np.pi * app_train['HOUR_APPR_PROCESS_START'] / 24)
app_train['NAME_FAMILY_STATUS'].replace('Unknown', 'Single / not married', inplace=True)

app_train['EMERGENCYSTATE_MODE'].fillna('No', inplace=True)
app_train['FONDKAPREMONT_MODE'].fillna('Unknown', inplace=True)
app_train['WALLSMATERIAL_MODE'].fillna('Not Specified', inplace=True) 
app_train['OCCUPATION_TYPE'].replace('IT staff', 'High skill tech staff', inplace=True)
app_train['OCCUPATION_TYPE'].replace('Realty agents', 'Sales staff', inplace=True)
app_train['OCCUPATION_TYPE'].replace('HR staff', 'Laborers', inplace=True)
app_train['OCCUPATION_TYPE'].fillna('Unknown', inplace=True)
app_train['OCCUPATION_TYPE'].replace(['Cleaning staff', 'Cooking staff', 'Waiters/barmen staff'], 'F&B staff', inplace=True)
app_train['HOUSETYPE_MODE'].replace(['block of flats', 'specific housing'], 'house', inplace=True)
app_train['WALLSMATERIAL_MODE'].replace(['Others', 'Mixed', 'Monolithic'], 'Others', inplace=True)
app_train['WALLSMATERIAL_MODE'].replace(['Block', 'Stone, brick'], 'Brick', inplace=True)

def group_organization_type(org_type):
    if 'Trade' in org_type:
        return 'Trade'
    elif 'Industry' in org_type:
        return 'Industry'
    elif 'Business' in org_type:
        return 'Business Entity'
    elif 'Transport' in org_type:
        return 'Transport'
    else:
        return org_type
app_train['ORGANIZATION_TYPE'] = app_train['ORGANIZATION_TYPE'].replace('XNA', 'Unknown')
app_train['ORGANIZATION_TYPE'] = app_train['ORGANIZATION_TYPE'].apply(group_organization_type)

#app_train = app_train[app_train['OWN_CAR_AGE'] != 91.0]
app_train['OWN_CAR_AGE'] = app_train['OWN_CAR_AGE'].fillna(-100)
#app_train = app_train[app_train['FLAG_MOBIL'] == 1]

app_train['EXT_SOURCE_SUM'] = app_train[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']].sum(axis=1, skipna=True)
app_train['EXT_SOURCE_PROD'] = app_train[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']].prod(axis=1, skipna=True)
app_train['EXT_SOURCE_MEAN'] = app_train[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']].mean(axis=1, skipna=True)
app_train['EXT_SOURCE_STD'] = app_train[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']].std(axis=1, skipna=True)
app_train['EXT_SOURCE_MISSING_VALUES'] = app_train[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']].isna().sum(axis=1)
app_train['EXT_SOURCE_WEIGHTED'] = app_train.EXT_SOURCE_1 * 2 + app_train.EXT_SOURCE_2 * 3 + app_train.EXT_SOURCE_3 * 4

app_train['AMT_REQ_CREDIT_BUREAU_YEAR'] = app_train['AMT_REQ_CREDIT_BUREAU_YEAR'].fillna(value = app_train['AMT_REQ_CREDIT_BUREAU_YEAR'].mean())

#Documents 
docs = [f for f in app_train.columns if 'FLAG_DOC' in f]
app_train['NEW_DOC_IND_AVG'] = app_train[docs].mean(axis=1)
app_train['NEW_DOC_IND_STD'] = app_train[docs].std(axis=1)
app_train['DOCUMENT_COUNT'] = app_train[docs].sum(axis=1)
app_train['NEW_DOC_IND_KURT'] = app_train[docs].kurtosis(axis=1)
app_train['HAS_DOCUMENT'] = app_train[docs].max(axis=1)
#Drop flag document  
app_train = app_train.drop(app_train.filter(regex='^FLAG_DOCUMENT_\d+$').columns, axis = 1)

#New feat from income and inquiry 
app_train['TOTALAREA_MODE'] = app_train['TOTALAREA_MODE'] ** (1/3)
med_income = app_train.groupby(['ORGANIZATION_TYPE', 'NAME_EDUCATION_TYPE'])['AMT_INCOME_TOTAL'].transform('median')
med_income2 = app_train.groupby('ORGANIZATION_TYPE')['AMT_INCOME_TOTAL'].transform('median')
app_train['income_ratio'] = app_train['AMT_INCOME_TOTAL'] / med_income
app_train['income_ratio2'] = app_train['AMT_INCOME_TOTAL'] / med_income2
app_train['true_annuity_div_income'] = app_train['AMT_ANNUITY'] / med_income
app_train['true_annuity_div_income2'] = app_train['AMT_ANNUITY'] / med_income2
app_train['true_income_div_totalarea'] = med_income / app_train['TOTALAREA_MODE'].clip(0.001,1)
app_train['true_income_div_totalarea2'] = med_income2 / app_train['TOTALAREA_MODE'].clip(0.001,1)

#New features from bureau 
app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU'] = app_train[['AMT_REQ_CREDIT_BUREAU_DAY',
                                        'AMT_REQ_CREDIT_BUREAU_HOUR',
                                        'AMT_REQ_CREDIT_BUREAU_WEEK',
                                        'AMT_REQ_CREDIT_BUREAU_MON',
                                        'AMT_REQ_CREDIT_BUREAU_QRT',
                                        'AMT_REQ_CREDIT_BUREAU_YEAR']].sum(axis=1)

app_train['PCTG_ENQUIRIES_HOUR'] = app_train['AMT_REQ_CREDIT_BUREAU_HOUR'] / app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU']
app_train['PCTG_ENQUIRIES_DAY'] = app_train['AMT_REQ_CREDIT_BUREAU_DAY'] / app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU']
app_train['PCTG_ENQUIRIES_WEEK'] = app_train['AMT_REQ_CREDIT_BUREAU_WEEK'] / app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU']
app_train['PCTG_ENQUIRIES_MON'] = app_train['AMT_REQ_CREDIT_BUREAU_MON'] / app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU']
app_train['PCTG_ENQUIRIES_QRT'] = app_train['AMT_REQ_CREDIT_BUREAU_QRT'] / app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU']
app_train['PCTG_ENQUIRIES_YEAR'] = app_train['AMT_REQ_CREDIT_BUREAU_YEAR'] / app_train['TOTAL_ENQUIRIES_CREDIT_BUREAU']

#Adding new features; percentages
app_train['DAYS_EMPLOYED_PERC'] = app_train['DAYS_EMPLOYED'] / app_train['DAYS_BIRTH']
app_train['INCOME_CREDIT_PERC'] = app_train['AMT_INCOME_TOTAL'] / app_train['AMT_CREDIT']
app_train['INCOME_PER_PERSON'] = app_train['AMT_INCOME_TOTAL'] / app_train['CNT_FAM_MEMBERS']
app_train['ANNUITY_INCOME_PERC'] = app_train['AMT_ANNUITY'] / app_train['AMT_INCOME_TOTAL']
app_train['PAYMENT_RATE'] = app_train['AMT_ANNUITY'] /app_train['AMT_CREDIT']
app_train['DEBT_BURDEN_PER_WORKING_DAY'] = app_train['PAYMENT_RATE'] / (app_train['DAYS_EMPLOYED'] + 1e-5) * (app_train['DAYS_EMPLOYED'] != 0)
app_train['DEBT_BURDEN_PER_LIFE_DAY'] = app_train['PAYMENT_RATE'] / app_train['DAYS_BIRTH']
# ratio of the difference between the loan amount and the value of goods compared to the value of the goods
app_train['CREDIT_GOODS_PRICE_RATIO1'] = (app_train['AMT_CREDIT'] - app_train['AMT_GOODS_PRICE']) /  app_train['AMT_GOODS_PRICE']
# ratio of the difference between the loan amount and the value of goods compared to the loan amount
app_train['CREDIT_GOODS_PRICE_RATIO2'] = (app_train['AMT_CREDIT'] - app_train['AMT_GOODS_PRICE']) /  app_train['AMT_CREDIT']
app_train['DIFF_OBS_30_CNT_SOCIAL_CIRCLE_OBS_60_CNT_SOCIAL_CIRCLE'] = app_train['OBS_30_CNT_SOCIAL_CIRCLE'] - app_train['OBS_60_CNT_SOCIAL_CIRCLE']
app_train['DIFF_DEF_30_CNT_SOCIAL_CIRCLE_DEF_60_CNT_SOCIAL_CIRCLE'] = app_train['DEF_30_CNT_SOCIAL_CIRCLE'] - app_train['DEF_60_CNT_SOCIAL_CIRCLE']

app_train["HOUR_APPR_PROCESS_START"] = app_train["HOUR_APPR_PROCESS_START"].replace([8,9,10,11,12,13,14,15,16,17], 'working_hours')
app_train["HOUR_APPR_PROCESS_START"] = app_train["HOUR_APPR_PROCESS_START"].replace([18,19,20,21,22,23,0,1,2,3,4,5,6,7], 'off_hours')
app_train.drop(columns=['HOUR_APPR_PROCESS_START'], inplace=True)

missing_columns = ['APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG',
            'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG',
            'FLOORSMAX_AVG', 'FLOORSMIN_AVG', 'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG',
            'LIVINGAREA_AVG', 'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG']
app_train['MISSING_GRADINGS'] = app_train[missing_columns].isna().sum(axis=1)
map_week_day = {
'MONDAY': 'week_day',
'TUESDAY': 'week_day',
'WEDNESDAY': 'week_day',
'THURSDAY': 'week_day',
'FRIDAY': 'week_day',
'SATURDAY': 'weekend',
'SUNDAY': 'weekend',
}
app_train['WEEKDAY_APPR_PROCESS_START'] = app_train['WEEKDAY_APPR_PROCESS_START'].map(map_week_day)
map_edu = {
    'Lower secondary': 0,
    'Secondary / secondary special': 1,
    'Incomplete higher': 2,
    'Higher education': 3,
    'Academic degree': 5
}
app_train['NAME_EDUCATION_TYPE'] = app_train['NAME_EDUCATION_TYPE'].map(map_edu, na_action='ignore').astype(int).fillna(0)

#app_train['NAME_FAMILY_STATUS'].replace('Unknown', 'Single / not married', inplace=True)
#df['CODE_GENDER'].replace('XNA', 'F', inplace=True)
app_train['DAYS_EMPLOYED'] = app_train['DAYS_EMPLOYED'].fillna(365243)

others = app_train['NAME_INCOME_TYPE'].value_counts().index[4:]
app_train['NAME_INCOME_TYPE'].replace(others, 'Others', inplace=True)
app_train['NAME_TYPE_SUITE'].fillna('Unaccompanied', inplace=True)
app_train['TOTALAREA_MODE'].fillna(0, inplace=True)
app_train['AGE_INT'] = -app_train['DAYS_BIRTH'] // 365
app_train['DAYS_LAST_PHONE_CHANGE'].replace(0, np.nan, inplace=True)
app_train['car_to_birth_ratio'] = RELU(app_train['OWN_CAR_AGE'] / app_train['DAYS_BIRTH'])
app_train['car_to_employ_ratio'] = RELU(app_train['OWN_CAR_AGE'] / app_train['DAYS_EMPLOYED'])
app_train['children_ratio'] = app_train['CNT_CHILDREN'] / app_train['CNT_FAM_MEMBERS']
app_train['credit_to_annuity_ratio'] = app_train['AMT_CREDIT'] / app_train['AMT_ANNUITY'] 
app_train['credit_to_goods_ratio'] = app_train['AMT_CREDIT'] / app_train['AMT_GOODS_PRICE']
app_train['credit_to_income_ratio'] = app_train['AMT_CREDIT'] / app_train['AMT_INCOME_TOTAL']   

app_train['income_per_child'] = app_train['AMT_INCOME_TOTAL'] / (1 + app_train['CNT_CHILDREN'])
app_train['phone_to_birth_ratio'] = RELU(app_train['DAYS_LAST_PHONE_CHANGE'] / app_train['DAYS_BIRTH'])
app_train['phone_to_employ_ratio'] = RELU(app_train['DAYS_LAST_PHONE_CHANGE'] / (app_train['DAYS_EMPLOYED'] + 1e-5)) * (app_train['DAYS_EMPLOYED'] != 0) 
app_train['cnt_non_child'] = app_train['CNT_FAM_MEMBERS'] - app_train['CNT_CHILDREN']
app_train['child_to_non_child_ratio'] = app_train['CNT_CHILDREN'] / app_train['cnt_non_child'] * (app_train['cnt_non_child'] > 0)
app_train['income_per_non_child'] = app_train['AMT_INCOME_TOTAL'] / app_train['cnt_non_child']* (app_train['cnt_non_child'] > 0)
app_train['credit_per_person'] = app_train['AMT_CREDIT'] / app_train['CNT_FAM_MEMBERS']* (app_train['cnt_non_child'] > 0)
app_train['credit_per_child'] = app_train['AMT_CREDIT'] / (1 + app_train['CNT_CHILDREN'])
app_train['credit_per_non_child'] = app_train['AMT_CREDIT'] / app_train['cnt_non_child']* (app_train['cnt_non_child'] > 0)
app_train['CREDIT_DOWN_PAYMENT'] = app_train['AMT_GOODS_PRICE'] - app_train['AMT_CREDIT']

app_train['LIVINGAREA_AVG'] = app_train['LIVINGAREA_AVG'].fillna(0)
app_train['LANDAREA_AVG'] = app_train['LANDAREA_AVG'].fillna(0)
app_train['FLOORSMAX_AVG'] = app_train['FLOORSMAX_AVG'].fillna(0)
app_train['LIVINGAPARTMENTS_AVG'] = app_train['LIVINGAPARTMENTS_AVG'].fillna(0)
app_train['YEARS_BUILD_AVG'] = app_train['YEARS_BUILD_AVG'].fillna(0)

# some random numerical transformation
app_train['LIVINGAREA_AVG'] = app_train['LIVINGAREA_AVG'] ** (1/3.5)
app_train['NONLIVINGAPARTMENTS_AVG'] = app_train['NONLIVINGAPARTMENTS_AVG'] ** (1/7)
app_train['NONLIVINGAREA_AVG'] = app_train['NONLIVINGAREA_AVG'] ** (1/5)
app_train['OBS_30_CNT_SOCIAL_CIRCLE'] = app_train['OBS_30_CNT_SOCIAL_CIRCLE'] ** (1/7)
app_train['DEF_30_CNT_SOCIAL_CIRCLE'] = app_train['DEF_30_CNT_SOCIAL_CIRCLE'] ** (1/7)
app_train['OBS_60_CNT_SOCIAL_CIRCLE'] = app_train['OBS_60_CNT_SOCIAL_CIRCLE'] ** (1/7)
app_train['DEF_60_CNT_SOCIAL_CIRCLE'] = app_train['DEF_60_CNT_SOCIAL_CIRCLE'] ** (1/7)

app_train['REGION_POPULATION_RELATIVE'] = np.sqrt(app_train['REGION_POPULATION_RELATIVE'])
app_train['APARTMENTS_AVG'] = np.log1p(50 * app_train['APARTMENTS_AVG'])
app_train['YEARS_BEGINEXPLUATATION_AVG'] = app_train['YEARS_BEGINEXPLUATATION_AVG'] ** 30
app_train['YEARS_BUILD_AVG'] = app_train['YEARS_BUILD_AVG'] ** 3
app_train['COMMONAREA_AVG'] = app_train['COMMONAREA_AVG'].clip(0.000001,1) ** (-1/200)
app_train['ELEVATORS_AVG'] = app_train['ELEVATORS_AVG'] ** (1/40)
app_train['ENTRANCES_AVG'] = app_train['ENTRANCES_AVG'] ** (1/3)
app_train['FLOORSMAX_AVG'] = app_train['FLOORSMAX_AVG'] ** (1/2.5)
app_train['FLOORSMIN_AVG'] = app_train['FLOORSMIN_AVG'] ** (1/2.2)
app_train['LANDAREA_AVG'] = app_train['LANDAREA_AVG'] ** (1/5)
app_train['LIVINGAPARTMENTS_AVG'] = app_train['LIVINGAPARTMENTS_AVG'] ** (1/3)

#Some new ratio 
app_train['RATIO_AMT_GOODS_PRICE_TO_LIVINGAREA_AVG'] = app_train['AMT_GOODS_PRICE'] / app_train['LIVINGAREA_AVG'].clip(0.001,1)
app_train['RATIO_AMT_GOODS_PRICE_TO_LANDAREA_AVG'] = app_train['AMT_GOODS_PRICE'] / app_train['LANDAREA_AVG'].clip(0.001,1)
app_train['RATIO_AMT_GOODS_PRICE_TO_FLOORSMAX_AVG_AVG'] = app_train['AMT_GOODS_PRICE'] / app_train['FLOORSMAX_AVG'].clip(0.001,1)
app_train['RATIO_AMT_GOODS_PRICE_TO_LIVINGAPARTMENTS_AVG'] = app_train['AMT_GOODS_PRICE'] / app_train['LIVINGAPARTMENTS_AVG'].clip(0.001,1)
app_train['RATIO_AMT_GOODS_PRICE_TO_YEARS_BUILD_AVG'] = app_train['AMT_GOODS_PRICE'] / app_train['YEARS_BUILD_AVG'].clip(0.001,1)
app_train['RELIABILITY_IN_CUSTOMER_CITY'] = app_train['REG_CITY_NOT_LIVE_CITY'] + app_train['REG_CITY_NOT_WORK_CITY'] + app_train['REG_REGION_NOT_LIVE_REGION'] + app_train['REG_REGION_NOT_WORK_REGION'] + app_train['LIVE_CITY_NOT_WORK_CITY'] + app_train['LIVE_REGION_NOT_WORK_REGION']
app_train['SUM_CONTACTS'] = app_train['FLAG_MOBIL'] + app_train['FLAG_EMP_PHONE'] + app_train['FLAG_WORK_PHONE'] + app_train['FLAG_CONT_MOBILE'] + app_train['FLAG_PHONE'] + app_train['FLAG_EMAIL']

<>:56: SyntaxWarning: invalid escape sequence '\d'
<>:56: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_660542/3505911061.py:56: SyntaxWarning: invalid escape sequence '\d'
  app_train = app_train.drop(app_train.filter(regex='^FLAG_DOCUMENT_\d+$').columns, axis = 1)
/tmp/ipykernel_660542/3505911061.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app_train['CODE_GENDER'].replace('XNA',np.nan, inplace=True)
/tmp/ipykernel_660542/3505911061.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app_train['NAME_FAMILY_STATUS'].replace('Unknown', 'Single / not married', inplace=True)
/tmp/ipykernel_660542/3505911061.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app_train['EMERGENCYSTATE_MODE'].fillna('No', inplace=True)
/tmp/ipykernel_660542/3505911061.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app_train['FONDKAPREMONT_MODE'].fillna('Unknown', inplace=True)
/tmp/ipykernel_660542/3505911061.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app_train['WALLSMATERIAL_MODE'].fillna('Not Specified', inplace=True)
/tmp/ipykernel_660542/3505911061.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app_train['OCCUPATION_TYPE'].replace('IT staff', 'High skill tech staff', inplace=True)
/tmp/ipykernel_660542/3505911061.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app_train['OCCUPATION_TYPE'].replace('Realty agents', 'Sales staff', inplace=True)
/tmp/ipykernel_660542/3505911061.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app_train['OCCUPATION_TYPE'].replace('HR staff', 'Laborers', inplace=True)
/tmp/ipykernel_660542/3505911061.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app_train['OCCUPATION_TYPE'].fillna('Unknown', inplace=True)
/tmp/ipykernel_660542/3505911061.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app_train['HOUSETYPE_MODE'].replace(['block of flats', 'specific housing'], 'house', inplace=True)
/tmp/ipykernel_660542/3505911061.py:132: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app_train['NAME_INCOME_TYPE'].replace(others, 'Others', inplace=True)
/tmp/ipykernel_660542/3505911061.py:133: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app_train['NAME_TYPE_SUITE'].fillna('Unaccompanied', inplace=True)
/tmp/ipykernel_660542/3505911061.py:134: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app_train['TOTALAREA_MODE'].fillna(0, inplace=True)
/tmp/ipykernel_660542/3505911061.py:136: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  app_train['DAYS_LAST_PHONE_CHANGE'].replace(0, np.nan, inplace=True)
/tmp/ipykernel_660542/3505911061.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  app_train['SUM_CONTACTS'] = app_train['FLAG_MOBIL'] + app_train['FLAG_EMP_PHONE'] + app_train['FLAG_WORK_PHONE'] + app_train['FLAG_CONT_MOBILE'] + app_train['FLAG_PHONE'] + app_train['FLAG_EMAIL']

In [6]:
AGGREGATION_RECIPIES = [
    (['CODE_GENDER', 'NAME_EDUCATION_TYPE'], [('AMT_ANNUITY', 'max'),
                                              ('AMT_CREDIT', 'max'),
                                              ('EXT_SOURCE_1', 'mean'),
                                              ('EXT_SOURCE_2', 'mean'),
                                              ('OWN_CAR_AGE', 'max'),
                                              ('OWN_CAR_AGE', 'sum')]),
    (['CODE_GENDER', 'ORGANIZATION_TYPE'], [('AMT_ANNUITY', 'mean'),
                                            ('AMT_INCOME_TOTAL', 'mean'),
                                            ('DAYS_REGISTRATION', 'mean'),
                                            ('EXT_SOURCE_1', 'mean')]),
    (['CODE_GENDER', 'REG_CITY_NOT_WORK_CITY'], [('AMT_ANNUITY', 'mean'),
                                                 ('CNT_CHILDREN', 'mean'),
                                                 ('DAYS_ID_PUBLISH', 'mean')]),
    (['CODE_GENDER', 'NAME_EDUCATION_TYPE', 'OCCUPATION_TYPE', 'REG_CITY_NOT_WORK_CITY'], [('EXT_SOURCE_1', 'mean'),
                                                                                           ('EXT_SOURCE_2', 'mean')]),
    (['NAME_EDUCATION_TYPE', 'OCCUPATION_TYPE'], [('AMT_CREDIT', 'mean'),
                                                  ('AMT_REQ_CREDIT_BUREAU_YEAR', 'mean'),
                                                  ('APARTMENTS_AVG', 'mean'),
                                                  ('BASEMENTAREA_AVG', 'mean'),
                                                  ('EXT_SOURCE_1', 'mean'),
                                                  ('EXT_SOURCE_2', 'mean'),
                                                  ('EXT_SOURCE_3', 'mean'),
                                                  ('NONLIVINGAREA_AVG', 'mean'),
                                                  ('OWN_CAR_AGE', 'mean'),
                                                  ('YEARS_BUILD_AVG', 'mean')]),
    (['NAME_EDUCATION_TYPE', 'OCCUPATION_TYPE', 'REG_CITY_NOT_WORK_CITY'], [('ELEVATORS_AVG', 'mean'),
                                                                            ('EXT_SOURCE_1', 'mean')]),
    (['OCCUPATION_TYPE'], [('AMT_ANNUITY', 'mean'),
                           ('CNT_CHILDREN', 'mean'),
                           ('CNT_FAM_MEMBERS', 'mean'),
                           ('DAYS_BIRTH', 'mean'),
                           ('DAYS_EMPLOYED', 'mean'),
                           ('DAYS_ID_PUBLISH', 'mean'),
                           ('DAYS_REGISTRATION', 'mean'),
                           ('EXT_SOURCE_1', 'mean'),
                           ('EXT_SOURCE_2', 'mean'),
                           ('EXT_SOURCE_3', 'mean')]),
]

In [7]:
from tqdm import tqdm

In [8]:
groupby_aggregate_names = []
for groupby_cols, specs in tqdm(AGGREGATION_RECIPIES):
    group_object = app_train.groupby(groupby_cols)
    for select, agg in tqdm(specs):
        groupby_aggregate_name = '{}_{}_{}'.format('_'.join(groupby_cols), agg, select)
        app_train = app_train.merge(group_object[select]
                              .agg(agg)
                              .reset_index()
                              .rename(index=str,
                                      columns={select: groupby_aggregate_name})
                              [groupby_cols + [groupby_aggregate_name]],
                              on=groupby_cols,
                              how='left')
        groupby_aggregate_names.append(groupby_aggregate_name)

100%|██████████| 6/6 [00:00<00:00,  6.47it/s]
100%|██████████| 4/4 [00:00<00:00,  7.12it/s]
100%|██████████| 3/3 [00:00<00:00,  6.94it/s]
100%|██████████| 2/2 [00:00<00:00,  6.22it/s]
100%|██████████| 10/10 [00:01<00:00,  6.76it/s]
100%|██████████| 2/2 [00:00<00:00,  6.36it/s]
100%|██████████| 10/10 [00:01<00:00,  6.43it/s]
100%|██████████| 7/7 [00:05<00:00,  1.24it/s]

In [10]:
#X_agg = app_train[groupby_aggregate_names + ['TARGET']]

In [14]:
diff_feature_names = []
for groupby_cols, specs in tqdm(AGGREGATION_RECIPIES):
    for select, agg in tqdm(specs):
        if agg in ['mean','median','max','min']:
            groupby_aggregate_name = '{}_{}_{}'.format('_'.join(groupby_cols), agg, select)
            diff_name = '{}_diff'.format(groupby_aggregate_name)
            abs_diff_name = '{}_abs_diff'.format(groupby_aggregate_name)

            app_train[diff_name] = app_train[select] - app_train[groupby_aggregate_name] 
            app_train[abs_diff_name] = np.abs(app_train[select] - app_train[groupby_aggregate_name]) 

            diff_feature_names.append(diff_name)
            diff_feature_names.append(abs_diff_name)

100%|██████████| 6/6 [00:00<00:00, 387.53it/s]
100%|██████████| 4/4 [00:00<00:00, 848.75it/s]
100%|██████████| 3/3 [00:00<00:00, 851.98it/s]
100%|██████████| 2/2 [00:00<00:00, 701.92it/s]
100%|██████████| 10/10 [00:00<00:00, 533.61it/s]
100%|██████████| 2/2 [00:00<00:00, 513.03it/s]
100%|██████████| 10/10 [00:00<00:00, 516.57it/s]
100%|██████████| 7/7 [00:00<00:00, 90.02it/s]

In [15]:
app_train.shape

(246009, 273)

In [116]:
lbe = LabelEncoder()
for col in ['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY']:
    app_train[col] = lbe.fit_transform(app_train[col])

In [117]:
app_train, cat_cols = OHE(app_train, nan_as_category)

In [118]:
cat_cols

['NAME_CONTRACT_TYPE_Cash loans',
 'NAME_CONTRACT_TYPE_Revolving loans',
 'NAME_CONTRACT_TYPE_nan',
 'NAME_TYPE_SUITE_Children',
 'NAME_TYPE_SUITE_Family',
 'NAME_TYPE_SUITE_Group of people',
 'NAME_TYPE_SUITE_Other',
 'NAME_TYPE_SUITE_Spouse, partner',
 'NAME_TYPE_SUITE_Unaccompanied',
 'NAME_TYPE_SUITE_nan',
 'NAME_INCOME_TYPE_Businessman',
 'NAME_INCOME_TYPE_Commercial associate',
 'NAME_INCOME_TYPE_Maternity leave',
 'NAME_INCOME_TYPE_Pensioner',
 'NAME_INCOME_TYPE_State servant',
 'NAME_INCOME_TYPE_Student',
 'NAME_INCOME_TYPE_Unemployed',
 'NAME_INCOME_TYPE_Working',
 'NAME_INCOME_TYPE_nan',
 'NAME_EDUCATION_TYPE_Academic degree',
 'NAME_EDUCATION_TYPE_Higher education',
 'NAME_EDUCATION_TYPE_Incomplete higher',
 'NAME_EDUCATION_TYPE_Lower secondary',
 'NAME_EDUCATION_TYPE_Secondary / secondary special',
 'NAME_EDUCATION_TYPE_nan',
 'NAME_FAMILY_STATUS_Civil marriage',
 'NAME_FAMILY_STATUS_Married',
 'NAME_FAMILY_STATUS_Separated',
 'NAME_FAMILY_STATUS_Single / not married',
 'NAME_FAMILY_STATUS_Widow',
 'NAME_FAMILY_STATUS_nan',
 'NAME_HOUSING_TYPE_Co-op apartment',
 'NAME_HOUSING_TYPE_House / apartment',
 'NAME_HOUSING_TYPE_Municipal apartment',
 'NAME_HOUSING_TYPE_Office apartment',
 'NAME_HOUSING_TYPE_Rented apartment',
 'NAME_HOUSING_TYPE_With parents',
 'NAME_HOUSING_TYPE_nan',
 'OCCUPATION_TYPE_Accountants',
 'OCCUPATION_TYPE_Cleaning staff',
 'OCCUPATION_TYPE_Cooking staff',
 'OCCUPATION_TYPE_Core staff',
 'OCCUPATION_TYPE_Drivers',
 'OCCUPATION_TYPE_HR staff',
 'OCCUPATION_TYPE_High skill tech staff',
 'OCCUPATION_TYPE_IT staff',
 'OCCUPATION_TYPE_Laborers',
 'OCCUPATION_TYPE_Low-skill Laborers',
 'OCCUPATION_TYPE_Managers',
 'OCCUPATION_TYPE_Medicine staff',
 'OCCUPATION_TYPE_Private service staff',
 'OCCUPATION_TYPE_Realty agents',
 'OCCUPATION_TYPE_Sales staff',
 'OCCUPATION_TYPE_Secretaries',
 'OCCUPATION_TYPE_Security staff',
 'OCCUPATION_TYPE_Waiters/barmen staff',
 'OCCUPATION_TYPE_nan',
 'WEEKDAY_APPR_PROCESS_START_FRIDAY',
 'WEEKDAY_APPR_PROCESS_START_MONDAY',
 'WEEKDAY_APPR_PROCESS_START_SATURDAY',
 'WEEKDAY_APPR_PROCESS_START_SUNDAY',
 'WEEKDAY_APPR_PROCESS_START_THURSDAY',
 'WEEKDAY_APPR_PROCESS_START_TUESDAY',
 'WEEKDAY_APPR_PROCESS_START_WEDNESDAY',
 'WEEKDAY_APPR_PROCESS_START_nan',
 'HOUR_APPR_PROCESS_START_off_hours',
 'HOUR_APPR_PROCESS_START_working_hours',
 'HOUR_APPR_PROCESS_START_nan',
 'ORGANIZATION_TYPE_Advertising',
 'ORGANIZATION_TYPE_Agriculture',
 'ORGANIZATION_TYPE_Bank',
 'ORGANIZATION_TYPE_Business Entity',
 'ORGANIZATION_TYPE_Cleaning',
 'ORGANIZATION_TYPE_Construction',
 'ORGANIZATION_TYPE_Culture',
 'ORGANIZATION_TYPE_Electricity',
 'ORGANIZATION_TYPE_Emergency',
 'ORGANIZATION_TYPE_Government',
 'ORGANIZATION_TYPE_Hotel',
 'ORGANIZATION_TYPE_Housing',
 'ORGANIZATION_TYPE_Industry',
 'ORGANIZATION_TYPE_Insurance',
 'ORGANIZATION_TYPE_Kindergarten',
 'ORGANIZATION_TYPE_Legal Services',
 'ORGANIZATION_TYPE_Medicine',
 'ORGANIZATION_TYPE_Military',
 'ORGANIZATION_TYPE_Mobile',
 'ORGANIZATION_TYPE_Other',
 'ORGANIZATION_TYPE_Police',
 'ORGANIZATION_TYPE_Postal',
 'ORGANIZATION_TYPE_Realtor',
 'ORGANIZATION_TYPE_Religion',
 'ORGANIZATION_TYPE_Restaurant',
 'ORGANIZATION_TYPE_School',
 'ORGANIZATION_TYPE_Security',
 'ORGANIZATION_TYPE_Security Ministries',
 'ORGANIZATION_TYPE_Self-employed',
 'ORGANIZATION_TYPE_Services',
 'ORGANIZATION_TYPE_Telecom',
 'ORGANIZATION_TYPE_Trade',
 'ORGANIZATION_TYPE_Transport',
 'ORGANIZATION_TYPE_Unemployed',
 'ORGANIZATION_TYPE_University',
 'ORGANIZATION_TYPE_nan',
 'FONDKAPREMONT_MODE_not specified',
 'FONDKAPREMONT_MODE_org spec account',
 'FONDKAPREMONT_MODE_reg oper account',
 'FONDKAPREMONT_MODE_reg oper spec account',
 'FONDKAPREMONT_MODE_nan',
 'HOUSETYPE_MODE_block of flats',
 'HOUSETYPE_MODE_specific housing',
 'HOUSETYPE_MODE_terraced house',
 'HOUSETYPE_MODE_nan',
 'WALLSMATERIAL_MODE_Block',
 'WALLSMATERIAL_MODE_Mixed',
 'WALLSMATERIAL_MODE_Monolithic',
 'WALLSMATERIAL_MODE_Others',
 'WALLSMATERIAL_MODE_Panel',
 'WALLSMATERIAL_MODE_Stone, brick',
 'WALLSMATERIAL_MODE_Wooden',
 'WALLSMATERIAL_MODE_nan',
 'EMERGENCYSTATE_MODE_No',
 'EMERGENCYSTATE_MODE_Yes',
 'EMERGENCYSTATE_MODE_nan']

In [119]:
app_train.shape

(246003, 238)