In [23]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [105]:
df = pd.read_csv('../data/dseb63_application_train.csv', index_col=0)

In [106]:
bureau = pd.read_csv('../data/dseb63_bureau_general_v2.csv', index_col=0)

In [107]:
bureau_columns = bureau.columns

new_bureau_columns = {col: 'BUREAU_' + col for col in bureau_columns if col != 'SK_ID_CURR'} 
new_bureau_columns
bureau.rename(columns=new_bureau_columns, inplace=True)

In [108]:
bureau

,BUREAU_SK_ID_BUREAU,BUREAU_AMT_CREDIT_SUM,BUREAU_AMT_CREDIT_SUM_DEBT,BUREAU_AMT_CREDIT_SUM_OVERDUE,BUREAU_AMT_CREDIT_SUM_LIMIT,BUREAU_AMT_ANNUITY,BUREAU_CREDIT_CURRENCY,BUREAU_CREDIT_TYPE,BUREAU_CREDIT_ACTIVE,BUREAU_SUM_CREDIT_CAR_LOAN,...,BUREAU_SOLD_FINISHED,BUREAU_SOLD_DURATION,BUREAU_SOLD_SUM_CREDIT,BUREAU_COUNT_BAD_DEBT,BUREAU_BAD_DEBT_LAST_365_DAYS,BUREAU_BAD_DEBT_LAST_730_DAYS,BUREAU_BAD_DEBT_FINISHED,BUREAU_BAD_DEBT_DURATION,BUREAU_BAD_DEBT_SUM_CREDIT,BUREAU_BAD_DEBT_SUM_DEBT
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
0,1,85513.50,77566.5,0.0,NaN,0.000,1,1,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,28350.00,0.0,0.0,0.0000,0.000,1,1,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6,254341.08,96417.0,0.0,0.0000,0.000,1,1,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7,483952.50,198769.5,0.0,0.0000,0.000,1,2,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,2822544.00,1254505.5,0.0,0.0000,0.000,1,2,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307504,4,866153.25,119767.5,0.0,0.0000,0.000,1,1,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307505,2,3618000.00,0.0,0.0,540000.0000,180927.000,1,2,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307506,4,259263.00,0.0,0.0,0.0000,0.000,1,1,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307508,7,5506306.83,251748.0,0.0,300.7875,25476.255,1,3,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307509,2,315000.00,27900.0,0.0,0.0000,0.000,1,2,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [109]:
df = df.merge(bureau, on='SK_ID_CURR', how='left')

In [110]:
df

,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,BUREAU_SOLD_FINISHED,BUREAU_SOLD_DURATION,BUREAU_SOLD_SUM_CREDIT,BUREAU_COUNT_BAD_DEBT,BUREAU_BAD_DEBT_LAST_365_DAYS,BUREAU_BAD_DEBT_LAST_730_DAYS,BUREAU_BAD_DEBT_FINISHED,BUREAU_BAD_DEBT_DURATION,BUREAU_BAD_DEBT_SUM_CREDIT,BUREAU_BAD_DEBT_SUM_DEBT
0,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,Cash loans,M,N,Y,0,99000.0,490495.5,27517.5,454500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,Cash loans,M,Y,Y,0,360000.0,1530000.0,42075.0,1530000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246004,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,225000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246005,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,225000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246006,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,585000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246007,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,319500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246008,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,675000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df.describe()

,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY_x,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,...,SOLD_FINISHED,SOLD_DURATION,SOLD_SUM_CREDIT,COUNT_BAD_DEBT,BAD_DEBT_LAST_365_DAYS,BAD_DEBT_LAST_730_DAYS,BAD_DEBT_FINISHED,BAD_DEBT_DURATION,BAD_DEBT_SUM_CREDIT,BAD_DEBT_SUM_DEBT
count,246009.000000,246009.000000,2.460090e+05,2.460090e+05,245999.000000,2.457850e+05,246009.000000,246009.000000,246009.000000,246009.000000,...,4148.000000,4148.000000,4.148000e+03,1.600000e+01,16.0,16.0,16.000000,16.00000,16.000000,16.000000
mean,0.080794,0.416229,1.684589e+05,5.996410e+05,27120.238129,5.389827e+05,0.020855,-16038.946343,63852.612441,-4985.222248,...,0.282546,226.158241,1.151967e+06,5.764170e+06,0.0,0.0,0.437500,552.75000,140504.236875,22911.477188
std,0.272519,0.720664,1.045297e+05,4.030980e+05,14510.634712,3.700520e+05,0.013818,4361.265483,141306.376949,3521.391396,...,0.483351,491.204373,2.793961e+06,4.333430e+05,0.0,0.0,0.512348,744.11491,137247.960562,61141.100800
min,0.000000,0.000000,2.565000e+04,4.500000e+04,1615.500000,4.050000e+04,0.000290,-25229.000000,-17912.000000,-23416.000000,...,0.000000,0.000000,0.000000e+00,5.173404e+06,0.0,0.0,0.000000,0.00000,14296.500000,0.000000
25%,0.000000,0.000000,1.125000e+05,2.700000e+05,16506.000000,2.385000e+05,0.010006,-19682.000000,-2758.000000,-7482.000000,...,0.000000,0.000000,1.045136e+05,5.439014e+06,0.0,0.0,0.000000,0.00000,53030.250000,0.000000
50%,0.000000,0.000000,1.462500e+05,5.147775e+05,24903.000000,4.500000e+05,0.018850,-15755.000000,-1212.000000,-4504.000000,...,0.000000,0.000000,2.340000e+05,5.637208e+06,0.0,0.0,0.000000,0.00000,109147.500000,0.000000
75%,0.000000,1.000000,2.025000e+05,8.086500e+05,34654.500000,6.795000e+05,0.028663,-12418.000000,-288.000000,-2006.000000,...,1.000000,86.749133,9.000000e+05,6.071199e+06,0.0,0.0,1.000000,1043.75000,167625.000000,0.000000
max,1.000000,19.000000,1.350000e+07,4.050000e+06,258025.500000,4.050000e+06,0.072508,-7489.000000,365243.000000,0.000000,...,3.000000,2846.971530,7.744482e+07,6.446445e+06,0.0,0.0,1.000000,2192.00000,528165.000000,182632.635000

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246009 entries, 0 to 246008
Columns: 210 entries, TARGET to BAD_DEBT_SUM_DEBT
dtypes: float64(153), int64(41), object(16)
memory usage: 394.1+ MB

In [30]:
for col in df.columns:
    print(col, df[col].dtype)

TARGET int64
NAME_CONTRACT_TYPE object
CODE_GENDER object
FLAG_OWN_CAR object
FLAG_OWN_REALTY object
CNT_CHILDREN int64
AMT_INCOME_TOTAL float64
AMT_CREDIT float64
AMT_ANNUITY_x float64
AMT_GOODS_PRICE float64
NAME_TYPE_SUITE object
NAME_INCOME_TYPE object
NAME_EDUCATION_TYPE object
NAME_FAMILY_STATUS object
NAME_HOUSING_TYPE object
REGION_POPULATION_RELATIVE float64
DAYS_BIRTH int64
DAYS_EMPLOYED int64
DAYS_REGISTRATION float64
DAYS_ID_PUBLISH int64
OWN_CAR_AGE float64
FLAG_MOBIL int64
FLAG_EMP_PHONE int64
FLAG_WORK_PHONE int64
FLAG_CONT_MOBILE int64
FLAG_PHONE int64
FLAG_EMAIL int64
OCCUPATION_TYPE object
CNT_FAM_MEMBERS float64
REGION_RATING_CLIENT int64
REGION_RATING_CLIENT_W_CITY int64
WEEKDAY_APPR_PROCESS_START object
HOUR_APPR_PROCESS_START int64
REG_REGION_NOT_LIVE_REGION int64
REG_REGION_NOT_WORK_REGION int64
LIVE_REGION_NOT_WORK_REGION int64
REG_CITY_NOT_LIVE_CITY int64
REG_CITY_NOT_WORK_CITY int64
LIVE_CITY_NOT_WORK_CITY int64
ORGANIZATION_TYPE object
EXT_SOURCE_1 float64
EXT_SOURCE_2 float64
EXT_SOURCE_3 float64
APARTMENTS_AVG float64
BASEMENTAREA_AVG float64
YEARS_BEGINEXPLUATATION_AVG float64
YEARS_BUILD_AVG float64
COMMONAREA_AVG float64
ELEVATORS_AVG float64
ENTRANCES_AVG float64
FLOORSMAX_AVG float64
FLOORSMIN_AVG float64
LANDAREA_AVG float64
LIVINGAPARTMENTS_AVG float64
LIVINGAREA_AVG float64
NONLIVINGAPARTMENTS_AVG float64
NONLIVINGAREA_AVG float64
APARTMENTS_MODE float64
BASEMENTAREA_MODE float64
YEARS_BEGINEXPLUATATION_MODE float64
YEARS_BUILD_MODE float64
COMMONAREA_MODE float64
ELEVATORS_MODE float64
ENTRANCES_MODE float64
FLOORSMAX_MODE float64
FLOORSMIN_MODE float64
LANDAREA_MODE float64
LIVINGAPARTMENTS_MODE float64
LIVINGAREA_MODE float64
NONLIVINGAPARTMENTS_MODE float64
NONLIVINGAREA_MODE float64
APARTMENTS_MEDI float64
BASEMENTAREA_MEDI float64
YEARS_BEGINEXPLUATATION_MEDI float64
YEARS_BUILD_MEDI float64
COMMONAREA_MEDI float64
ELEVATORS_MEDI float64
ENTRANCES_MEDI float64
FLOORSMAX_MEDI float64
FLOORSMIN_MEDI float64
LANDAREA_MEDI float64
LIVINGAPARTMENTS_MEDI float64
LIVINGAREA_MEDI float64
NONLIVINGAPARTMENTS_MEDI float64
NONLIVINGAREA_MEDI float64
FONDKAPREMONT_MODE object
HOUSETYPE_MODE object
TOTALAREA_MODE float64
WALLSMATERIAL_MODE object
EMERGENCYSTATE_MODE object
OBS_30_CNT_SOCIAL_CIRCLE float64
DEF_30_CNT_SOCIAL_CIRCLE float64
OBS_60_CNT_SOCIAL_CIRCLE float64
DEF_60_CNT_SOCIAL_CIRCLE float64
DAYS_LAST_PHONE_CHANGE float64
FLAG_DOCUMENT_2 int64
FLAG_DOCUMENT_3 int64
FLAG_DOCUMENT_4 int64
FLAG_DOCUMENT_5 int64
FLAG_DOCUMENT_6 int64
FLAG_DOCUMENT_7 int64
FLAG_DOCUMENT_8 int64
FLAG_DOCUMENT_9 int64
FLAG_DOCUMENT_10 int64
FLAG_DOCUMENT_11 int64
FLAG_DOCUMENT_12 int64
FLAG_DOCUMENT_13 int64
FLAG_DOCUMENT_14 int64
FLAG_DOCUMENT_15 int64
FLAG_DOCUMENT_16 int64
FLAG_DOCUMENT_17 int64
FLAG_DOCUMENT_18 int64
FLAG_DOCUMENT_19 int64
FLAG_DOCUMENT_20 int64
FLAG_DOCUMENT_21 int64
AMT_REQ_CREDIT_BUREAU_HOUR float64
AMT_REQ_CREDIT_BUREAU_DAY float64
AMT_REQ_CREDIT_BUREAU_WEEK float64
AMT_REQ_CREDIT_BUREAU_MON float64
AMT_REQ_CREDIT_BUREAU_QRT float64
AMT_REQ_CREDIT_BUREAU_YEAR float64
SK_ID_CURR int64
SK_ID_BUREAU float64
AMT_CREDIT_SUM float64
AMT_CREDIT_SUM_DEBT float64
AMT_CREDIT_SUM_OVERDUE float64
AMT_CREDIT_SUM_LIMIT float64
AMT_ANNUITY_y float64
CREDIT_CURRENCY float64
CREDIT_TYPE float64
CREDIT_ACTIVE float64
SUM_CREDIT_CAR_LOAN float64
SUM_DEBT_CAR_LOAN float64
SUM_OVERDUE_CAR_LOAN float64
SUM_CREDIT_CARD float64
SUM_DEBT_CARD float64
SUM_OVERDUE_CARD float64
SUM_MORTGAGE float64
SUM_DEBT_MORTGAGE float64
SUM_OVERDUE_MORTGAGE float64
SUM_CONSUMER_CREDIT float64
SUM_DEBT_CONSUMER_CREDIT float64
SUM_OVERDUE_CONSUMER_CREDIT float64
SUM_MICROLOAN float64
SUM_DEBT_MICROLOAN float64
SUM_OVERDUE_MICROLOAN float64
SUM_BUSINESS_DEVELOPMENT float64
SUM_OVERDUE_BUSINESS_DEVELOPMENT float64
SUM_OTHER float64
ACTIVE float64
ACTIVE_LAST_30_DAYS float64
ACTIVE_LAST_60_DAYS float64
ACTIVE_LAST_90_DAYS float64
ACTIVE_LAST_180_DAYS float64
ACTIVE_LAST_365_DAYS float64
ACTIVE_LAST_730_DAYS float64
ACTIVE_NEXT_30_DAYS float64
ACTIVE_NEXT_180_DAYS float64
ACTIVE_LIFE_TIME_CREDIT float64
ACTIVE_CREDIT_TYPE float64
ACTIVE_AMT_CREDIT_SUM float64
ACTIVE_AMT_CREDIT_SUM_LIMIT float64
ACTIVE_AMT_ANNUITY float64
ACTIVE_SUM_CREDIT_30_DAYS float64
ACTIVE_SUM_DEBT_30_DAYS float64
ACTIVE_SUM_OVERDUE_30_DAYS float64
ACTIVE_SUM_CREDIT_180_DAYS float64
ACTIVE_SUM_DEBT_180_DAYS float64
ACTIVE_SUM_OVERDUE_180_DAYS float64
ACTIVE_SUM_CREDIT_LIFE_TIME float64
ACTIVE_SUM_DEBT_LIFE_TIME float64
ACTIVE_SUM_OVERDUE_LIFE_TIME float64
ACTIVE_MEAN_DURATION_NOT_LIFE_TIME float64
CLOSE float64
CLOSE_LAST_30_DAYS float64
CLOSE_LAST_60_DAYS float64
CLOSE_LAST_90_DAYS float64
CLOSE_LAST_180_DAYS float64
CLOSE_LAST_365_DAYS float64
CLOSE_LAST_730_DAYS float64
CLOSE_LIFE_TIME_CREDIT float64
CLOSE_CREDIT_TYPE float64
CLOSE_AMT_CREDIT_SUM float64
CLOSE_AMT_CREDIT_SUM_LIMIT float64
CLOSE_AMT_ANNUITY float64
CLOSE_SUM_CREDIT_180_DAYS float64
CLOSE_SUM_DEBT_180_DAYS float64
CLOSE_SUM_OVERDUE_180_DAYS float64
CLOSE_SUM_CREDIT_LIFE_TIME float64
CLOSE_SUM_DEBT_LIFE_TIME float64
CLOSE_SUM_OVERDUE_LIFE_TIME float64
CLOSE_MEAN_DURATION_NOT_LIFE_TIME float64
CLOSE_LATENCY_30_DAYS float64
CLOSE_LATENCY_180_DAYS float64
CLOSE_LATENCY_365_DAYS float64
CLOSE_MEAN_LATENCY float64
COUNT_SOLD float64
SOLD_LAST_90_DAYS float64
SOLD_LAST_365_DAYS float64
SOLD_LAST_730_DAYS float64
SOLD_FINISHED float64
SOLD_DURATION float64
SOLD_SUM_CREDIT float64
COUNT_BAD_DEBT float64
BAD_DEBT_LAST_365_DAYS float64
BAD_DEBT_LAST_730_DAYS float64
BAD_DEBT_FINISHED float64
BAD_DEBT_DURATION float64
BAD_DEBT_SUM_CREDIT float64
BAD_DEBT_SUM_DEBT float64

In [31]:
df['EMERGENCYSTATE_MODE'].value_counts()

EMERGENCYSTATE_MODE
No     127434
Yes      1883
Name: count, dtype: int64

In [32]:
df.describe()

,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY_x,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,...,SOLD_FINISHED,SOLD_DURATION,SOLD_SUM_CREDIT,COUNT_BAD_DEBT,BAD_DEBT_LAST_365_DAYS,BAD_DEBT_LAST_730_DAYS,BAD_DEBT_FINISHED,BAD_DEBT_DURATION,BAD_DEBT_SUM_CREDIT,BAD_DEBT_SUM_DEBT
count,246009.000000,246009.000000,2.460090e+05,2.460090e+05,245999.000000,2.457850e+05,246009.000000,246009.000000,246009.000000,246009.000000,...,4148.000000,4148.000000,4.148000e+03,1.600000e+01,16.0,16.0,16.000000,16.00000,16.000000,16.000000
mean,0.080794,0.416229,1.684589e+05,5.996410e+05,27120.238129,5.389827e+05,0.020855,-16038.946343,63852.612441,-4985.222248,...,0.282546,226.158241,1.151967e+06,5.764170e+06,0.0,0.0,0.437500,552.75000,140504.236875,22911.477188
std,0.272519,0.720664,1.045297e+05,4.030980e+05,14510.634712,3.700520e+05,0.013818,4361.265483,141306.376949,3521.391396,...,0.483351,491.204373,2.793961e+06,4.333430e+05,0.0,0.0,0.512348,744.11491,137247.960562,61141.100800
min,0.000000,0.000000,2.565000e+04,4.500000e+04,1615.500000,4.050000e+04,0.000290,-25229.000000,-17912.000000,-23416.000000,...,0.000000,0.000000,0.000000e+00,5.173404e+06,0.0,0.0,0.000000,0.00000,14296.500000,0.000000
25%,0.000000,0.000000,1.125000e+05,2.700000e+05,16506.000000,2.385000e+05,0.010006,-19682.000000,-2758.000000,-7482.000000,...,0.000000,0.000000,1.045136e+05,5.439014e+06,0.0,0.0,0.000000,0.00000,53030.250000,0.000000
50%,0.000000,0.000000,1.462500e+05,5.147775e+05,24903.000000,4.500000e+05,0.018850,-15755.000000,-1212.000000,-4504.000000,...,0.000000,0.000000,2.340000e+05,5.637208e+06,0.0,0.0,0.000000,0.00000,109147.500000,0.000000
75%,0.000000,1.000000,2.025000e+05,8.086500e+05,34654.500000,6.795000e+05,0.028663,-12418.000000,-288.000000,-2006.000000,...,1.000000,86.749133,9.000000e+05,6.071199e+06,0.0,0.0,1.000000,1043.75000,167625.000000,0.000000
max,1.000000,19.000000,1.350000e+07,4.050000e+06,258025.500000,4.050000e+06,0.072508,-7489.000000,365243.000000,0.000000,...,3.000000,2846.971530,7.744482e+07,6.446445e+06,0.0,0.0,1.000000,2192.00000,528165.000000,182632.635000

In [33]:
ordinal_cols = ['FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'EMERGENCYSTATE_MODE']
float_cols = []
int_cols = []
cate_cols = []
for col in df.columns:
    if col not in ordinal_cols:
        if df[col].dtype == 'float64':
            float_cols.append(col)
        elif df[col].dtype == 'int64':
            int_cols.append(col)
        else:
            cate_cols.append(col)

In [34]:
def process_df(df):
    df = df.copy()
    df['EMERGENCYSTATE_MODE'].fillna('No', inplace=True)
    df['FONDKAPREMONT_MODE'].fillna('Unknown', inplace=True)
    df['WALLSMATERIAL_MODE'].fillna('Not Specified', inplace=True)
    df['OCCUPATION_TYPE'].replace('IT staff', 'High skill tech staff', inplace=True)
    df['OCCUPATION_TYPE'].replace('Realty agents', 'Sales staff', inplace=True)
    df['OCCUPATION_TYPE'].replace('HR staff', 'Laborers', inplace=True)
    df['OCCUPATION_TYPE'].fillna('Unknown', inplace=True)
    df['NAME_EDUCATION_TYPE'].replace('Academic degree', 'Higher education', inplace=True)

    others = df['NAME_INCOME_TYPE'].value_counts().index[4:]
    df['NAME_INCOME_TYPE'].replace(others, 'Others', inplace=True)
    df['NAME_TYPE_SUITE'].fillna('Unaccompanied', inplace=True)

    df['OWN_CAR_AGE'].fillna(-100, inplace=True)
    return df
df = process_df(df)

In [35]:
def display_missing_data_info(dataframe, ascending=False):
    missing_values_count = dataframe.isnull().sum()
    missing_values_percentage = (dataframe.isnull().mean() * 100)
    missing_data = pd.DataFrame({
        'Missing Values': missing_values_count,
        'Percentage (%)': missing_values_percentage
    })
    
    missing_data = missing_data[missing_data['Missing Values'] > 0]
    
    sorted_missing_data = missing_data.sort_values(by='Missing Values', ascending=ascending)

    print(sorted_missing_data)
    return sorted_missing_data

In [36]:
display_missing_data_info(df)

                        Missing Values  Percentage (%)
BAD_DEBT_SUM_DEBT               245993       99.993496
BAD_DEBT_FINISHED               245993       99.993496
BAD_DEBT_LAST_365_DAYS          245993       99.993496
COUNT_BAD_DEBT                  245993       99.993496
BAD_DEBT_LAST_730_DAYS          245993       99.993496
...                                ...             ...
EXT_SOURCE_2                       529        0.215033
AMT_GOODS_PRICE                    224        0.091054
AMT_ANNUITY_x                       10        0.004065
DAYS_LAST_PHONE_CHANGE               1        0.000406
CNT_FAM_MEMBERS                      1        0.000406

[149 rows x 2 columns]

                        Missing Values  Percentage (%)
BAD_DEBT_SUM_DEBT               245993       99.993496
BAD_DEBT_FINISHED               245993       99.993496
BAD_DEBT_LAST_365_DAYS          245993       99.993496
COUNT_BAD_DEBT                  245993       99.993496
BAD_DEBT_LAST_730_DAYS          245993       99.993496
...                                ...             ...
EXT_SOURCE_2                       529        0.215033
AMT_GOODS_PRICE                    224        0.091054
AMT_ANNUITY_x                       10        0.004065
DAYS_LAST_PHONE_CHANGE               1        0.000406
CNT_FAM_MEMBERS                      1        0.000406

[149 rows x 2 columns]

In [37]:
from sklearn.preprocessing import OneHotEncoder

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, PowerTransformer, OrdinalEncoder, LabelEncoder
from sklearn.impute import SimpleImputer

In [38]:
df_train = df.copy()
df_train.dropna(subset=['TARGET'], inplace=True)

In [39]:
df_train['TARGET'].value_counts()

TARGET
0    226133
1     19876
Name: count, dtype: int64

In [40]:
X = df_train.drop(columns=['TARGET', 'SK_ID_CURR'])
y = df_train['TARGET']

In [41]:
ordinal_cols = ['FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'EMERGENCYSTATE_MODE']
float_cols = []
int_cols = []
cate_cols = []
flag_cols = []
for col in X.columns:
    if col not in ordinal_cols:
        if X[col].dtype == 'float64':
            float_cols.append(col)
        elif X[col].dtype == 'int64':
            if 'FLAG' in col:
                flag_cols.append(col)
            else:
                int_cols.append(col)
        else:
            cate_cols.append(col)

In [42]:
for col in float_cols:
    X[col].fillna(0, inplace=True)
    
for col in int_cols:
    X[col].fillna(0, inplace=True)
for col in cate_cols:
    X[col].fillna('Unknown', inplace=True)

In [43]:
# Fill missing values in categorical columns

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.1, random_state=42, stratify=y
)

In [45]:
onehot_transformer = OneHotEncoder(handle_unknown='ignore')
power_transformer = PowerTransformer()
ordinal_transformer = OrdinalEncoder()
scaler_transformer = StandardScaler()

preprocessor = ColumnTransformer(
    transformers=[
        ('onehot', onehot_transformer, cate_cols),
        ('power', scaler_transformer, float_cols), # power_transformer
        ('ordinal', ordinal_transformer, ordinal_cols),
        ('scale',scaler_transformer, int_cols),
        ('flag', 'passthrough', flag_cols)
        
    ]
)

In [46]:
X.head()

,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY_x,AMT_GOODS_PRICE,NAME_TYPE_SUITE,...,SOLD_FINISHED,SOLD_DURATION,SOLD_SUM_CREDIT,COUNT_BAD_DEBT,BAD_DEBT_LAST_365_DAYS,BAD_DEBT_LAST_730_DAYS,BAD_DEBT_FINISHED,BAD_DEBT_DURATION,BAD_DEBT_SUM_CREDIT,BAD_DEBT_SUM_DEBT
0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Unaccompanied,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Unaccompanied,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Cash loans,M,N,Y,0,99000.0,490495.5,27517.5,454500.0,"Spouse, partner",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Cash loans,M,Y,Y,0,360000.0,1530000.0,42075.0,1530000.0,Unaccompanied,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [47]:
X_train = preprocessor.fit_transform(X_train)
X_train

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [48]:
X_val = preprocessor.transform(X_val)

In [51]:
cat_feature = preprocessor.named_transformers_['onehot'].get_feature_names_out(cate_cols)
cat_feature

feature_names = np.concatenate([cat_feature, float_cols, ordinal_cols, int_cols, flag_cols])

In [52]:
df_train_preprocessed = pd.DataFrame(X_train, columns=feature_names)
df_train_preprocessed

,NAME_CONTRACT_TYPE_Cash loans,NAME_CONTRACT_TYPE_Revolving loans,CODE_GENDER_F,CODE_GENDER_M,CODE_GENDER_XNA,NAME_TYPE_SUITE_Children,NAME_TYPE_SUITE_Family,NAME_TYPE_SUITE_Group of people,NAME_TYPE_SUITE_Other_A,NAME_TYPE_SUITE_Other_B,...,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21
0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221403,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
221404,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
221405,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
221406,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
221407,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [53]:
display_missing_data_info(df_train_preprocessed)

Empty DataFrame
Columns: [Missing Values, Percentage (%)]
Index: []

Empty DataFrame
Columns: [Missing Values, Percentage (%)]
Index: []

In [ ]:
!pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in /home/quanghung20gg/anaconda3/lib/python3.12/site-packages (0.12.3)
Requirement already satisfied: numpy>=1.17.3 in /home/quanghung20gg/anaconda3/lib/python3.12/site-packages (from imbalanced-learn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in /home/quanghung20gg/anaconda3/lib/python3.12/site-packages (from imbalanced-learn) (1.13.1)
Requirement already satisfied: scikit-learn>=1.0.2 in /home/quanghung20gg/anaconda3/lib/python3.12/site-packages (from imbalanced-learn) (1.4.2)
Requirement already satisfied: joblib>=1.1.1 in /home/quanghung20gg/anaconda3/lib/python3.12/site-packages (from imbalanced-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/quanghung20gg/anaconda3/lib/python3.12/site-packages (from imbalanced-learn) (2.2.0)

## Upsample - Downsample

In [54]:
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import ClusterCentroids, TomekLinks
from sklearn.model_selection import train_test_split

In [55]:
smote = SMOTE(sampling_strategy=0.1, random_state=42, n_jobs=-1)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\imblearn\over_sampling\_smote\base.py:363: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

In [ ]:
# undersampler = TomekLinks(n_jobs=-1)
# X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

### Manual double

In [56]:
y_train

33709     0
142235    0
186109    0
164147    0
161892    0
         ..
179026    0
228875    0
115337    0
97555     0
22646     0
Name: TARGET, Length: 221408, dtype: int64

In [ ]:
# posidx = y_train[y_train == 1].index
# negidx = y_train[y_train == 0].index


# X_train_pos = X_train[posidx]
# y_train_pos = y_train[posidx]

# X_train_neg = X_train[negidx]
# y_train_neg = y_train[negidx]

# X_resampled = np.concatenate([X_train_pos, X_train_neg, X_train_neg])
# y_resampled = np.concatenate([y_train_pos, y_train_neg, y_train_neg])

In [57]:
# X_resampled = X_train
# y_resampled = y_train

In [58]:
X_resampled.shape

(223872, 326)

In [59]:

from sklearn.model_selection import cross_val_score, StratifiedKFold, cross_validate
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [60]:
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np

In [61]:
pca = PCA()
pca.fit(X_train)

PCA()

In [62]:
explained_variance = pca.explained_variance_ratio_

# Get the absolute values of PCA components (loadings)
feature_contributions = np.abs(pca.components_)

# Aggregate feature importance scores
# Weight each feature's contribution by the variance explained by the component
weighted_contributions = feature_contributions * explained_variance[:, np.newaxis]

# Sum weighted contributions across components
feature_importance = weighted_contributions.sum(axis=0)

# Create a DataFrame for ranking
importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': feature_importance
}).sort_values(by='Importance', ascending=False)
importance_df

                        Feature    Importance
240  ACTIVE_SUM_CREDIT_180_DAYS  5.426273e-02
241    ACTIVE_SUM_DEBT_180_DAYS  5.365570e-02
212           SUM_DEBT_MORTGAGE  5.318870e-02
211                SUM_MORTGAGE  5.292645e-02
256        CLOSE_AMT_CREDIT_SUM  5.275871e-02
..                          ...           ...
25   NAME_FAMILY_STATUS_Unknown  2.447351e-06
300                  FLAG_MOBIL  1.926596e-06
278      BAD_DEBT_LAST_365_DAYS  1.664880e-20
279      BAD_DEBT_LAST_730_DAYS  1.522048e-20
316            FLAG_DOCUMENT_12  6.369716e-34

[326 rows x 2 columns]

In [63]:
def select_features_with_pca(X, threshold=0.1):
    """
    Select features contributing to principal components above a certain threshold.

    Parameters:
    X (numpy array or pandas DataFrame): Input feature matrix.
    threshold (float): Contribution threshold for selecting features (default is 0.1).

    Returns:
    selected_columns (list): List of selected feature names or indices.
    selected_data (DataFrame): Data with selected features.
    """
    # Convert to DataFrame if X is a NumPy array
    if isinstance(X, np.ndarray):
        X = pd.DataFrame(X, columns=[f"Feature{i+1}" for i in range(X.shape[1])])
    
    # Apply PCA
    pca = PCA()
    pca.fit(X)
    
    # Calculate absolute loadings (contributions of features to components)
    explained_variance = pca.explained_variance_ratio_
    feature_contributions = np.abs(pca.components_)
    weighted_contributions = feature_contributions * explained_variance[:, np.newaxis]
    # Identify features exceeding the threshold for any component

    feature_mask = (weighted_contributions > threshold).any(axis=0)
    selected_columns = X.columns[feature_mask].tolist()
    
    # Filter the data to keep only selected features
    selected_data = X[selected_columns]
    
    return selected_columns, selected_data

IF USING PCA

In [ ]:
# X_df = pd.DataFrame(X_train, columns=feature_names)
# X_train_selected_columns, X_train_selected = select_features_with_pca(X_df, threshold=0.0001)

,NAME_CONTRACT_TYPE_Cash loans,NAME_CONTRACT_TYPE_Revolving loans,CODE_GENDER_F,CODE_GENDER_M,CODE_GENDER_XNA,NAME_TYPE_SUITE_Children,NAME_TYPE_SUITE_Family,NAME_TYPE_SUITE_Group of people,NAME_TYPE_SUITE_Other_A,NAME_TYPE_SUITE_Other_B,...,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00255,-0.059477,-0.054269,-0.034802,-0.100138,-0.016332,-0.090534,-0.024402,-0.022529,-0.018305
1,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,-0.00255,-0.059477,-0.054269,-0.034802,-0.100138,-0.016332,-0.090534,-0.024402,-0.022529,-0.018305
2,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00255,-0.059477,-0.054269,-0.034802,-0.100138,-0.016332,-0.090534,-0.024402,-0.022529,-0.018305
3,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00255,-0.059477,-0.054269,-0.034802,-0.100138,-0.016332,-0.090534,-0.024402,-0.022529,-0.018305
4,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00255,-0.059477,-0.054269,-0.034802,-0.100138,-0.016332,-0.090534,-0.024402,-0.022529,-0.018305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00255,-0.059477,-0.054269,-0.034802,-0.100138,-0.016332,-0.090534,-0.024402,-0.022529,-0.018305
307507,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00255,-0.059477,-0.054269,-0.034802,-0.100138,-0.016332,-0.090534,-0.024402,-0.022529,-0.018305
307508,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00255,-0.059477,-0.054269,-0.034802,-0.100138,-0.016332,-0.090534,-0.024402,-0.022529,-0.018305
307509,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00255,-0.059477,-0.054269,-0.034802,-0.100138,-0.016332,-0.090534,-0.024402,-0.022529,-0.018305
307510,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.00255,-0.059477,-0.054269,-0.034802,-0.100138,-0.016332,-0.090534,-0.024402,-0.022529,-0.018305

In [64]:
logistic_model = LogisticRegression(random_state=42, max_iter=10000, n_jobs=-1, class_weight='balanced')

In [65]:
dt_model = DecisionTreeClassifier(random_state=42, class_weight = 'balanced')

In [66]:
stacking_model = StackingClassifier(
    estimators=[
        ('lr', logistic_model),
        ('dt', dt_model)
    ],
    final_estimator=LogisticRegression(class_weight='balanced', random_state=42, max_iter=1000),  # Final model for stacking
    cv=4
)

In [67]:
kfold = StratifiedKFold(n_splits=4, shuffle=True, random_state=42)

In [68]:
from sklearn.metrics import make_scorer, roc_auc_score
def gini_coefficient(y_true, y_pred):
    """
    Calculate the Gini coefficient using predictions and true labels.
    
    Parameters:
    y_true (array-like): True binary labels.
    y_pred (array-like): Predicted probabilities.
    
    Returns:
    float: Gini coefficient.
    """
    auc = roc_auc_score(y_true, y_pred)  # AUC calculation
    return 2 * auc - 1  # Gini coefficient

In [69]:
gini_scorer = make_scorer(gini_coefficient, needs_proba=True)

In [71]:
print("Logistic Regression Cross-Validation Scores:")
# gini_scores = cross_val_score(logistic_model, X_resampled, y_resampled, cv=kfold, scoring=gini_scorer)
# logistic_model.fit(X_resampled, y_resampled)
# y_pred = logistic_model.predict_proba(X_val)
# gini_scores = gini_coefficient(y_val, y_pred[:,1])
print(f"Gini Scores for each fold: {gini_scores}")
print(f"Mean Gini Score: {gini_scores.mean():.4f}")

Logistic Regression Cross-Validation Scores:
Gini Scores for each fold: [0.49626946 0.48384437 0.49198377 0.51547106]
Mean Gini Score: 0.4969

Raw

Logistic Regression Cross-Validation Scores:

Gini Scores for each fold: [0.45377758 0.46924275 0.46512525 0.4723335  0.45818808]

Mean Gini Score: 0.4637

In [ ]:
print("Decision Tree Cross-Validation Scores:")
gini_scores = cross_val_score(dt_model, X_resampled, y_resampled, cv=kfold, scoring=gini_scorer)
print(f"Gini Scores for each fold: {gini_scores}")
print(f"Mean Gini Score: {gini_scores.mean():.4f}")

Decision Tree Cross-Validation Scores:
Gini Scores for each fold: [0.07419061 0.07786527 0.06883207 0.07998777 0.07582835]
Mean Gini Score: 0.0753

In [73]:
print("Stacking Cross-Validation Scores:")
stacking_model.fit(X_resampled, y_resampled)
y_pred = stacking_model.predict_proba(X_val)
gini_scores = gini_coefficient(y_val, y_pred[:,1])
print(f"Gini Scores: {gini_scores}")

Stacking Cross-Validation Scores:
Gini Scores: 0.4903653558017278

In [72]:
print("Stacking Cross-Validation Scores:")
results = cross_validate(stacking_model, X_resampled, y_resampled, cv=4, scoring=gini_scorer, n_jobs=-1,return_estimator=True)
print(f"Gini Scores for each fold: {results['test_score']}")
print(f"Mean Gini Score: {results['test_score'].mean():.4f}")

Stacking Cross-Validation Scores:

KeyboardInterrupt:

In [ ]:
for i, estimator in enumerate(results['estimator']):
    y_pred = estimator.predict_proba(X_val)
    gini_scores = gini_coefficient(y_val, y_pred[:,1])
    print(f"Gini Score for fold {i}: {gini_scores:.4f}")

Gini Score for fold 0: 0.4647
Gini Score for fold 1: 0.4664
Gini Score for fold 2: 0.4658
Gini Score for fold 3: 0.4704

Stacking Cross-Validation Scores:

Gini Scores for each fold: [0.45493243 0.47045351 0.46576538 0.47327105 0.45963799]

Mean Gini Score: 0.4648

In [74]:
df_test = pd.read_csv('../data/dseb63_application_test.csv')

In [75]:
df_test = df_test.merge(bureau, on='SK_ID_CURR', how='left')

In [76]:
df_test = process_df(df_test)

In [77]:
df_test

,Unnamed: 0,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY_x,AMT_GOODS_PRICE,...,SOLD_FINISHED,SOLD_DURATION,SOLD_SUM_CREDIT,COUNT_BAD_DEBT,BAD_DEBT_LAST_365_DAYS,BAD_DEBT_LAST_730_DAYS,BAD_DEBT_FINISHED,BAD_DEBT_DURATION,BAD_DEBT_SUM_CREDIT,BAD_DEBT_SUM_DEBT
0,0,Cash loans,M,Y,N,2,207000.0,465457.5,52641.0,418500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Cash loans,F,Y,Y,0,247500.0,1281712.5,48946.5,1179000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Cash loans,F,Y,N,0,202500.0,495000.0,39109.5,495000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Cash loans,F,N,Y,0,247500.0,254700.0,24939.0,225000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Cash loans,M,N,Y,0,112500.0,308133.0,15862.5,234000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61497,61497,Cash loans,M,Y,Y,0,171000.0,521280.0,23089.5,450000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61498,61498,Revolving loans,M,Y,Y,2,450000.0,900000.0,45000.0,900000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61499,61499,Cash loans,F,N,Y,0,225000.0,202500.0,24030.0,202500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61500,61500,Cash loans,M,N,Y,0,121500.0,254700.0,30357.0,225000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61501,61501,Cash loans,M,Y,Y,1,112500.0,1314117.0,38551.5,1147500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
for col in float_cols:
    df_test[col].fillna(0, inplace=True)
    
for col in int_cols:
    df_test[col].fillna(0, inplace=True)
for col in cate_cols:
    df_test[col].fillna('Unknown', inplace=True)

In [79]:
X_test = df_test.drop(columns=['SK_ID_CURR'])

In [80]:
X_test = preprocessor.transform(X_test)

In [81]:
X_all = np.concatenate([X_resampled, X_val])
y_all = np.concatenate([y_resampled, y_val])

In [82]:
stacking_model.fit(X_all, y_all)

StackingClassifier(cv=4,
                   estimators=[('lr',
                                LogisticRegression(class_weight='balanced',
                                                   max_iter=10000, n_jobs=-1,
                                                   random_state=42)),
                               ('dt',
                                DecisionTreeClassifier(class_weight='balanced',
                                                       random_state=42))],
                   final_estimator=LogisticRegression(class_weight='balanced',
                                                      max_iter=1000,
                                                      random_state=42))

In [83]:
y_pred = stacking_model.predict_proba(X_test)

In [ ]:
# gini_coefficient(y, y_pred[:, 1])

In [84]:
submission = pd.DataFrame({
    'SK_ID_CURR': df_test['SK_ID_CURR'],
    'TARGET': y_pred[:, 1]
})
submission.to_csv('../submission/dseb63_stacking_bureau.csv', index=False)