In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
def display_missing_data_info(dataframe, ascending=False):
    missing_values_count = dataframe.isnull().sum()
    missing_values_percentage = (dataframe.isnull().mean() * 100)
    missing_data = pd.DataFrame({
        'Missing Values': missing_values_count,
        'Percentage (%)': missing_values_percentage
    })
    
    missing_data = missing_data[missing_data['Missing Values'] > 0]
    
    sorted_missing_data = missing_data.sort_values(by='Missing Values', ascending=ascending)

    print(sorted_missing_data)
    return sorted_missing_data

In [ ]:
installment = pd.read_csv('../data/dseb63_installments_payments.csv')

In [5]:
installment['SK_ID_PREV'].nunique()

549020

In [6]:
installment.shape

(7744758, 9)

In [26]:
installment_sample = installment[installment['SK_ID_CURR'] == 283333]
installment_sample

,SK_ID_PREV,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT,SK_ID_CURR,TARGET,DIFF,...,LAST_90_DAYS,LAST_180_DAYS,LAST_365_DAYS,LAST_730_DAYS,PAYMENT_LAST_30_DAYS,PAYMENT_LAST_60_DAYS,PAYMENT_LAST_90_DAYS,PAYMENT_LAST_180_DAYS,PAYMENT_LAST_365_DAYS,PAYMENT_LAST_730_DAYS
947579,1194097,0.0,10,-460.0,-460.0,31.365,31.365,283333.0,0.0,0.0,...,False,False,False,True,0.0,0.0,0.0,0.000,0.000,31.365
947580,1194097,0.0,35,-59.0,-60.0,15745.500,15745.500,283333.0,0.0,1.0,...,True,True,True,True,0.0,15745.5,15745.5,15745.500,15745.500,15745.500
947581,1194097,0.0,15,-365.0,-374.0,11030.580,11030.580,283333.0,0.0,9.0,...,False,False,False,True,0.0,0.0,0.0,0.000,0.000,11030.580
947582,1194097,0.0,19,-304.0,-307.0,11847.015,11847.015,283333.0,0.0,3.0,...,False,False,True,True,0.0,0.0,0.0,0.000,11847.015,11847.015
947583,1001465,1.0,9,-231.0,-251.0,2459.565,2459.565,283333.0,0.0,20.0,...,False,False,True,True,0.0,0.0,0.0,0.000,2459.565,2459.565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
947635,1194097,0.0,13,-393.0,-403.0,6710.490,6710.490,283333.0,0.0,10.0,...,False,False,False,True,0.0,0.0,0.0,0.000,0.000,6710.490
947636,2763332,1.0,5,-199.0,-214.0,4854.510,4854.510,283333.0,0.0,15.0,...,False,False,True,True,0.0,0.0,0.0,0.000,4854.510,4854.510
947637,2763332,1.0,4,-229.0,-236.0,4854.510,4854.510,283333.0,0.0,7.0,...,False,False,True,True,0.0,0.0,0.0,0.000,4854.510,4854.510
947638,1194097,0.0,17,-334.0,-337.0,11890.215,11890.215,283333.0,0.0,3.0,...,False,False,True,True,0.0,0.0,0.0,0.000,11890.215,11890.215
947639,1194097,0.0,30,-153.0,-153.0,129.105,129.105,283333.0,0.0,0.0,...,False,True,True,True,0.0,0.0,0.0,129.105,129.105,129.105

In [27]:
installment_sample.sort_values(by=['SK_ID_PREV', 'NUM_INSTALMENT_NUMBER'], ascending=False, inplace=True)
# installment_185737.sort_values(by=, ascending=False, inplace=True)
installment_sample.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_20324\1388967542.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  installment_sample.sort_values(by=['SK_ID_PREV', 'NUM_INSTALMENT_NUMBER'], ascending=False, inplace=True)

,SK_ID_PREV,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT,SK_ID_CURR,TARGET,DIFF,...,LAST_90_DAYS,LAST_180_DAYS,LAST_365_DAYS,LAST_730_DAYS,PAYMENT_LAST_30_DAYS,PAYMENT_LAST_60_DAYS,PAYMENT_LAST_90_DAYS,PAYMENT_LAST_180_DAYS,PAYMENT_LAST_365_DAYS,PAYMENT_LAST_730_DAYS
947585,2763332,2.0,8,-109.0,-112.0,14223.51,14223.51,283333.0,0.0,3.0,...,False,True,True,True,0.0,0.0,0.0,14223.51,14223.51,14223.51
947605,2763332,1.0,7,-139.0,-159.0,4854.51,4854.51,283333.0,0.0,20.0,...,False,True,True,True,0.0,0.0,0.0,4854.51,4854.51,4854.51
947595,2763332,1.0,6,-169.0,-188.0,4854.51,4854.51,283333.0,0.0,19.0,...,False,False,True,True,0.0,0.0,0.0,0.00,4854.51,4854.51
947636,2763332,1.0,5,-199.0,-214.0,4854.51,4854.51,283333.0,0.0,15.0,...,False,False,True,True,0.0,0.0,0.0,0.00,4854.51,4854.51
947637,2763332,1.0,4,-229.0,-236.0,4854.51,4854.51,283333.0,0.0,7.0,...,False,False,True,True,0.0,0.0,0.0,0.00,4854.51,4854.51

## Feature for installments payment
- Group by id prev 
- Count num install
- version: max
- Late: mean
- Early: mean
- Last payment date
- Total money
- mean

## Group by id curr
- Count install
- Sum money
- Mean early
- Mean late
- Mean value each payment
- Count last payment 3-6-9-12-24

### Sep by duration (less than 12 and more than 12) (ngan han / trung han)
- Count install 
- Sum money
- Mean early
- Mean late
- Mean value each payment
- Variance each payment
- Count payment 3-12-24
- Sum payment 3-12-24

In [ ]:
installment['DIFF'] = installment['DAYS_INSTALMENT'] - installment['DAYS_ENTRY_PAYMENT']
installment['LATE'] = installment['DIFF'] > 0
installment['EARLY'] = installment['DIFF'] <= 0

installment['LATE'] *= installment['DIFF']
installment['EARLY'] *= -installment['DIFF']

installment["LAST_30_DAYS"] = installment["DAYS_ENTRY_PAYMENT"] >= -30
installment["LAST_60_DAYS"] = installment["DAYS_ENTRY_PAYMENT"] >= -60
installment["LAST_90_DAYS"] = installment["DAYS_ENTRY_PAYMENT"] >= -90
installment["LAST_180_DAYS"] = installment["DAYS_ENTRY_PAYMENT"] >= -180
installment["LAST_365_DAYS"] = installment["DAYS_ENTRY_PAYMENT"] >= -365
installment["LAST_730_DAYS"] = installment["DAYS_ENTRY_PAYMENT"] >= -365*3 # 3 years

installment["PAYMENT_LAST_30_DAYS"] = installment["LAST_30_DAYS"] * installment["AMT_PAYMENT"]
installment["PAYMENT_LAST_60_DAYS"] = installment["LAST_60_DAYS"] * installment["AMT_PAYMENT"]
installment["PAYMENT_LAST_90_DAYS"] = installment["LAST_90_DAYS"] * installment["AMT_PAYMENT"]
installment["PAYMENT_LAST_180_DAYS"] = installment["LAST_180_DAYS"] * installment["AMT_PAYMENT"]
installment["PAYMENT_LAST_365_DAYS"] = installment["LAST_365_DAYS"] * installment["AMT_PAYMENT"]
installment["PAYMENT_LAST_730_DAYS"] = installment["LAST_730_DAYS"] * installment["AMT_PAYMENT"]

In [ ]:
installment["LATENESS_LAST_90_DAYS"] = installment["LAST_90_DAYS"] * installment["LATE"]
installment["LATENESS_LAST_180_DAYS"] = installment["LAST_180_DAYS"] * installment["LATE"]
installment["LATENESS_LAST_365_DAYS"] = installment["LAST_365_DAYS"] * installment["LATE"]
installment["LATENESS_LAST_730_DAYS"] = installment["LAST_730_DAYS"] * installment["LATE"]

installment["EARLYNESS_LAST_90_DAYS"] = installment["LAST_90_DAYS"] * installment["EARLY"]
installment["EARLYNESS_LAST_180_DAYS"] = installment["LAST_180_DAYS"] * installment["EARLY"]
installment["EARLYNESS_LAST_365_DAYS"] = installment["LAST_365_DAYS"] * installment["EARLY"]
installment["EARLYNESS_LAST_730_DAYS"] = installment["LAST_730_DAYS"] * installment["EARLY"]

installment["PAYMENT_LATENESS_LAST_180_DAYS"] = installment["LAST_180_DAYS"] * installment["LATENESS_LAST_180_DAYS"]
installment["PAYMENT_LATENESS_LAST_365_DAYS"] = installment["LAST_365_DAYS"] * installment["LATENESS_LAST_365_DAYS"]
installment["PAYMENT_LATENESS_LAST_730_DAYS"] = installment["LAST_730_DAYS"] * installment["LATENESS_LAST_730_DAYS"]

installment["PAYMENT_EARLYNESS_LAST_180_DAYS"] = installment["LAST_180_DAYS"] * installment["EARLYNESS_LAST_180_DAYS"]
installment["PAYMENT_EARLYNESS_LAST_365_DAYS"] = installment["LAST_365_DAYS"] * installment["EARLYNESS_LAST_365_DAYS"]
installment["PAYMENT_EARLYNESS_LAST_730_DAYS"] = installment["LAST_730_DAYS"] * installment["EARLYNESS_LAST_730_DAYS"]

In [14]:
installment['COUNT'] = 1

In [ ]:
gb_installment = installment.groupby('SK_ID_PREV').agg({'SK_ID_CURR':'first', 
                                                        'NUM_INSTALMENT_NUMBER':'max', 
                                                        'COUNT':'sum', 
                                                        'DIFF':['sum', 'mean', 'std'],
                                                        'LATE': ['sum', 'mean', 'std'], 
                                                        'EARLY': ['sum', 'mean', 'std'], 
                                                        'DAYS_ENTRY_PAYMENT':'max', 
                                                        'AMT_PAYMENT':'sum',
                                                          
                                                        'LAST_30_DAYS':'sum', 
                                                        'LAST_60_DAYS':'sum', 
                                                        'LAST_90_DAYS':'sum', 
                                                        'LAST_180_DAYS':'sum', 
                                                        'LAST_365_DAYS':'sum', 
                                                        'LAST_730_DAYS':'sum', 
                                                        
                                                        'PAYMENT_LAST_30_DAYS':['sum', 'mean', 'std',], 
                                                        'PAYMENT_LAST_60_DAYS':['sum', 'mean', 'std'], 
                                                        'PAYMENT_LAST_90_DAYS':['sum', 'mean', 'std', 'max','min'], 
                                                        'PAYMENT_LAST_180_DAYS':['sum', 'mean', 'std'], 
                                                        'PAYMENT_LAST_365_DAYS':['sum', 'mean', 'std', 'max','min'], 
                                                        'PAYMENT_LAST_730_DAYS':['sum', 'mean', 'std']
                                                        
                                                        'LATENESS_LAST_90_DAYS':['sum', 'mean'],
                                                        'LATENESS_LAST_180_DAYS':['sum', 'mean', 'std'],
                                                        'LATENESS_LAST_365_DAYS':['sum', 'mean'],
                                                        'LATENESS_LAST_730_DAYS':['sum', 'mean', 'std'],
                                                        
                                                        'EARLYNESS_LAST_90_DAYS':['sum', 'mean'],
                                                        'EARLYNESS_LAST_180_DAYS':['sum', 'mean', 'std'],
                                                        'EARLYNESS_LAST_365_DAYS':['sum', 'mean'],
                                                        'EARLYNESS_LAST_730_DAYS':['sum', 'mean', 'std'],
                                                        
                                                        'PAYMENT_LATENESS_LAST_180_DAYS':['sum', 'mean'],
                                                        'PAYMENT_LATENESS_LAST_365_DAYS':['sum', 'mean', 'std'],
                                                        'PAYMENT_LATENESS_LAST_730_DAYS':['sum', 'mean', 'std'],
                                                        
                                                        'PAYMENT_EARLYNESS_LAST_180_DAYS':['sum', 'mean'],
                                                        'PAYMENT_EARLYNESS_LAST_365_DAYS':['sum', 'mean', 'std'],
                                                        'PAYMENT_EARLYNESS_LAST_730_DAYS':['sum', 'mean', 'std'],
                                                        
                                                        }).reset_index()

gb_installment.rename(columns={'COUNT':'NUM_INSTALMENT', 'LATE':'LATE_PAYMENT', 'EARLY':'EARLY_PAYMENT', 'DAYS_ENTRY_PAYMENT':'LASTEST_PAYMENT_DATE', 'AMT_PAYMENT':'TOTAL_PAYMENT'}, inplace=True)
gb_installment['MEAN_INSTALLMENT'] = gb_installment['TOTAL_PAYMENT'] / gb_installment['NUM_INSTALMENT_NUMBER']

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT,LATE_PAYMENT,EARLY_PAYMENT,LASTEST_PAYMENT_DATE,TOTAL_PAYMENT,TARGET,LAST_30_DAYS,LAST_60_DAYS,LAST_90_DAYS,LAST_180_DAYS,LAST_365_DAYS,LAST_730_DAYS,PAYMENT_LAST_30_DAYS,PAYMENT_LAST_60_DAYS,PAYMENT_LAST_90_DAYS,PAYMENT_LAST_180_DAYS,PAYMENT_LAST_365_DAYS,PAYMENT_LAST_730_DAYS
0,1000001,117953.0,2,16.000000,0.000000,-244.0,68443.425,0.0,0,0,0,0,2,2,0.000,0.000,0.000,0.000,68443.425,68443.425
1,1000003,6707.0,3,15.333333,0.000000,-49.0,14854.050,0.0,0,1,2,3,3,3,0.000,4951.350,9902.700,14854.050,14854.050,14854.050
2,1000004,187620.0,7,26.714286,0.000000,-695.0,33523.155,NaN,0,0,0,0,0,1,0.000,0.000,0.000,0.000,0.000,13176.495
3,1000005,83759.0,11,8.818182,0.363636,-1433.0,147021.705,0.0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000
4,1000007,25033.0,5,16.800000,0.000000,-10.0,56234.025,NaN,1,2,3,5,5,5,11246.805,22493.610,33740.415,56234.025,56234.025,56234.025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549015,2843490,158969.0,4,0.000000,2.750000,-2616.0,16157.745,0.0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000
549016,2843491,277329.0,10,14.200000,0.000000,-35.0,254219.850,0.0,0,1,2,6,10,10,0.000,25421.985,50843.970,152531.910,254219.850,254219.850
549017,2843492,36159.0,12,6.250000,0.000000,-344.0,262990.800,NaN,0,0,0,0,1,12,0.000,0.000,0.000,0.000,21876.300,262990.800
549018,2843494,70155.0,2,10.000000,0.000000,-770.0,982794.465,0.0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000
549019,2843495,274857.0,7,4.000000,0.142857,-264.0,797530.185,1.0,0,0,0,0,4,7,0.000,0.000,0.000,0.000,726861.600,797530.185

In [22]:
gb_installment_short_term = gb_installment[gb_installment['NUM_INSTALMENT_NUMBER'] <= 12]
gb_installment_long_term = gb_installment[gb_installment['NUM_INSTALMENT_NUMBER'] > 12]

In [ ]:
gb_installment_by_curr = gb_installment.groupby('SK_ID_CURR').agg({'NUM_INSTALMENT':'sum', 'NUM_INSTALMENT_NUMBER':'mean', 'MEAN_INSTALLMENT':'mean', 'LATE_PAYMENT':'mean', 'EARLY_PAYMENT':'mean', 'LASTEST_PAYMENT_DATE':'max', 'TOTAL_PAYMENT':'sum',  'LAST_30_DAYS':'sum', 'LAST_60_DAYS':'sum', 'LAST_90_DAYS':'sum', 'LAST_180_DAYS':'sum', 'LAST_365_DAYS':'sum', 'LAST_730_DAYS':'sum', 'PAYMENT_LAST_30_DAYS':'sum', 'PAYMENT_LAST_60_DAYS':'sum', 'PAYMENT_LAST_90_DAYS':'sum', 'PAYMENT_LAST_180_DAYS':'sum', 'PAYMENT_LAST_365_DAYS':'sum', 'PAYMENT_LAST_730_DAYS':'sum'}).reset_index()
gb_installment_short_term_by_curr = gb_installment_short_term.groupby('SK_ID_CURR').agg({'NUM_INSTALMENT':'sum', 'NUM_INSTALMENT_NUMBER':'mean', 'MEAN_INSTALLMENT':'mean', 'LATE_PAYMENT':'mean', 'EARLY_PAYMENT':'mean', 'LASTEST_PAYMENT_DATE':'max', 'TOTAL_PAYMENT':'sum',  'LAST_30_DAYS':'sum', 'LAST_60_DAYS':'sum', 'LAST_90_DAYS':'sum', 'LAST_180_DAYS':'sum', 'LAST_365_DAYS':'sum', 'LAST_730_DAYS':'sum', 'PAYMENT_LAST_30_DAYS':'sum', 'PAYMENT_LAST_60_DAYS':'sum', 'PAYMENT_LAST_90_DAYS':'sum', 'PAYMENT_LAST_180_DAYS':'sum', 'PAYMENT_LAST_365_DAYS':'sum', 'PAYMENT_LAST_730_DAYS':'sum'}).reset_index()
gb_installment_short_term_by_curr.rename({ col: col + '_SHORT_TERM' for col in gb_installment_short_term_by_curr.columns if col != 'SK_ID_CURR' }, axis=1, inplace=True)
gb_installment_long_term_by_curr = gb_installment_long_term.groupby('SK_ID_CURR').agg({'NUM_INSTALMENT':'sum', 'NUM_INSTALMENT_NUMBER':'mean', 'MEAN_INSTALLMENT':'mean', 'LATE_PAYMENT':'mean', 'EARLY_PAYMENT':'mean', 'LASTEST_PAYMENT_DATE':'max', 'TOTAL_PAYMENT':'sum',  'LAST_30_DAYS':'sum', 'LAST_60_DAYS':'sum', 'LAST_90_DAYS':'sum', 'LAST_180_DAYS':'sum', 'LAST_365_DAYS':'sum', 'LAST_730_DAYS':'sum', 'PAYMENT_LAST_30_DAYS':'sum', 'PAYMENT_LAST_60_DAYS':'sum', 'PAYMENT_LAST_90_DAYS':'sum', 'PAYMENT_LAST_180_DAYS':'sum', 'PAYMENT_LAST_365_DAYS':'sum', 'PAYMENT_LAST_730_DAYS':'sum'}).reset_index()
gb_installment_long_term_by_curr.rename({ col: col + '_LONG_TERM' for col in gb_installment_long_term_by_curr.columns if col != 'SK_ID_CURR' }, axis=1, inplace=True)

In [24]:
gb_installment_by_curr = gb_installment_by_curr.merge(gb_installment_short_term_by_curr, on='SK_ID_CURR', how='left')
gb_installment_by_curr = gb_installment_by_curr.merge(gb_installment_long_term_by_curr, on='SK_ID_CURR', how='left')
gb_installment_by_curr

,SK_ID_CURR,NUM_INSTALMENT,NUM_INSTALMENT_NUMBER,MEAN_INSTALLMENT,LATE_PAYMENT,EARLY_PAYMENT,LASTEST_PAYMENT_DATE,TOTAL_PAYMENT,TARGET,LAST_30_DAYS,...,LAST_90_DAYS_LONG_TERM,LAST_180_DAYS_LONG_TERM,LAST_365_DAYS_LONG_TERM,LAST_730_DAYS_LONG_TERM,PAYMENT_LAST_30_DAYS_LONG_TERM,PAYMENT_LAST_60_DAYS_LONG_TERM,PAYMENT_LAST_90_DAYS_LONG_TERM,PAYMENT_LAST_180_DAYS_LONG_TERM,PAYMENT_LAST_365_DAYS_LONG_TERM,PAYMENT_LAST_730_DAYS_LONG_TERM
0,0.0,30,7.750000,17453.164821,20.433333,0.000000,-5.0,310942.395,0.0,4,...,13.0,17.0,20.0,20.0,10572.345,21047.265,93047.265,94653.045,102424.545,102424.545
1,1.0,40,11.333333,23890.779545,3.477074,1.779487,-18.0,787366.575,1.0,2,...,6.0,11.0,13.0,13.0,11700.000,23400.000,33750.000,56925.000,61425.000,61425.000
2,3.0,43,10.500000,11732.189135,25.498387,0.000000,-5.0,253501.605,0.0,3,...,9.0,17.0,31.0,31.0,7309.575,16388.010,23897.160,47760.435,107919.720,107919.720
3,4.0,6,6.000000,8953.522500,17.166667,0.000000,-2230.0,53721.135,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,10,10.000000,9818.644500,9.200000,0.000000,-1808.0,98186.445,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180728,307501.0,33,8.250000,9476.366562,11.180556,0.000000,-503.0,311748.975,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180729,307503.0,10,10.000000,4494.393000,11.300000,0.000000,-2013.0,44943.930,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180730,307504.0,133,60.250000,1946.446675,9.985352,5.013072,-22.0,218359.305,0.0,1,...,3.0,6.0,12.0,24.0,118.935,237.870,356.805,713.610,1427.220,2854.440
180731,307506.0,42,10.500000,11162.210625,7.645833,2.083333,-66.0,518373.360,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180732,307508.0,52,10.750000,21886.105875,15.749874,1.146591,-25.0,936723.645,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
gb_installment_by_curr.to_csv('../data/dseb63_installment_gb.csv', index=False)