In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
def display_missing_data_info(dataframe, ascending=False):
    missing_values_count = dataframe.isnull().sum()
    missing_values_percentage = (dataframe.isnull().mean() * 100)
    missing_data = pd.DataFrame({
        'Missing Values': missing_values_count,
        'Percentage (%)': missing_values_percentage
    })
    
    missing_data = missing_data[missing_data['Missing Values'] > 0]
    
    sorted_missing_data = missing_data.sort_values(by='Missing Values', ascending=ascending)

    print(sorted_missing_data)
    return sorted_missing_data

In [3]:
installment = pd.read_csv('../data/installments_payments.csv')
y_train = pd.read_csv('../data/application_train.csv')

In [4]:
installment = installment.merge(y_train[['SK_ID_CURR', 'TARGET']], on='SK_ID_CURR', how='left')

In [5]:
installment['SK_ID_CURR'].value_counts()[:204]

SK_ID_CURR
145728    372
296205    350
453103    347
189699    344
186851    337
         ...
324949    262
210753    262
419326    262
203283    262
185737    262
Name: count, Length: 204, dtype: int64

In [8]:
installment.shape

(13605401, 9)

In [6]:
installment_sample = installment[installment['SK_ID_CURR'] == 265042]
installment_sample

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT,TARGET
3799962,1776290,265042,1.0,13,-631.0,-635.0,33643.845,33643.845,0.0
3809100,1295333,265042,1.0,11,-2084.0,-2089.0,9166.500,9166.500,0.0
3813298,1776290,265042,1.0,31,-91.0,-91.0,33643.845,33643.845,0.0
3834389,1776290,265042,1.0,32,-61.0,-61.0,33643.845,33643.845,0.0
3841443,1776290,265042,1.0,27,-211.0,-211.0,33643.845,33643.845,0.0
...,...,...,...,...,...,...,...,...,...
7485399,2244271,265042,1.0,1,-556.0,-557.0,16639.875,16639.875,0.0
7505984,1570060,265042,1.0,2,-1579.0,-1581.0,8679.870,8679.870,0.0
7514020,1295333,265042,1.0,18,-1874.0,-1875.0,9005.400,9005.400,0.0
7545170,2535912,265042,1.0,28,-495.0,-496.0,39915.540,39915.540,0.0
7592843,2505150,265042,1.0,8,-1519.0,-1519.0,17077.815,17077.815,0.0

In [7]:
installment_sample.sort_values(by=['SK_ID_PREV', 'NUM_INSTALMENT_NUMBER'], ascending=False, inplace=True)
# installment_185737.sort_values(by=, ascending=False, inplace=True)
installment_sample.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_25784\1388967542.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  installment_sample.sort_values(by=['SK_ID_PREV', 'NUM_INSTALMENT_NUMBER'], ascending=False, inplace=True)

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT,TARGET
5796409,2605449,265042,1.0,6,-616.0,-635.0,18017.145,18017.145,0.0
3856666,2605449,265042,1.0,5,-646.0,-646.0,18091.035,18091.035,0.0
6579292,2605449,265042,1.0,4,-676.0,-677.0,18091.035,18091.035,0.0
6042322,2605449,265042,1.0,3,-706.0,-752.0,18091.035,18091.035,0.0
7330865,2605449,265042,1.0,2,-736.0,-752.0,18091.035,18091.035,0.0