In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
def display_missing_data_info(dataframe, ascending=False):
    missing_values_count = dataframe.isnull().sum()
    missing_values_percentage = (dataframe.isnull().mean() * 100)
    missing_data = pd.DataFrame({
        'Missing Values': missing_values_count,
        'Percentage (%)': missing_values_percentage
    })
    
    missing_data = missing_data[missing_data['Missing Values'] > 0]
    
    sorted_missing_data = missing_data.sort_values(by='Missing Values', ascending=ascending)

    print(sorted_missing_data)
    return sorted_missing_data

In [3]:
installment = pd.read_csv('../data/installments_payments.csv')
y_train = pd.read_csv('../data/application_train.csv')

In [ ]:
installment = installment.merge(y_train[['SK_ID_CURR', 'TARGET']], on='SK_ID_CURR', how='left')

In [8]:
installment['SK_ID_CURR'].value_counts()[:204]

SK_ID_CURR
145728    372
296205    350
453103    347
189699    344
186851    337
         ...
324949    262
210753    262
419326    262
203283    262
185737    262
Name: count, Length: 204, dtype: int64

In [9]:
installment_185737 = installment[installment['SK_ID_CURR'] == 185737]
installment_185737

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT,TARGET
29434,1051569,185737,0.0,128,-946.0,-946.0,1125.000,1125.000,1.0
30646,1051569,185737,0.0,110,-1218.0,-1218.0,1125.000,1125.000,1.0
71502,1051569,185737,0.0,50,-2175.0,-2175.0,1125.000,1125.000,1.0
135104,1051569,185737,0.0,141,-696.0,-695.0,7875.000,7875.000,1.0
162227,1051569,185737,0.0,87,-1549.0,-1549.0,7875.000,7875.000,1.0
...,...,...,...,...,...,...,...,...,...
3736507,1051569,185737,0.0,89,-1519.0,-1523.0,7875.000,7875.000,1.0
3743428,1051569,185737,0.0,72,-1792.0,-1797.0,7875.000,7875.000,1.0
3752454,1051569,185737,0.0,142,-665.0,-695.0,7875.000,1125.000,1.0
3784972,2842113,185737,1.0,5,-1405.0,-1437.0,5444.955,3.555,1.0
3795343,1051569,185737,0.0,176,-123.0,-123.0,1125.000,1125.000,1.0

In [12]:
installment_185737.sort_values(by=['SK_ID_PREV', 'NUM_INSTALMENT_NUMBER'], ascending=False, inplace=True)
# installment_185737.sort_values(by=, ascending=False, inplace=True)
installment_185737.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_19984\2137984213.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  installment_185737.sort_values(by=['SK_ID_PREV', 'NUM_INSTALMENT_NUMBER'], ascending=False, inplace=True)

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT,TARGET
2929616,2842113,185737,2.0,17,-1045.0,-1045.0,10457.550,10457.550,1.0
2055987,2842113,185737,1.0,16,-1075.0,-1073.0,5444.955,400.905,1.0
3318274,2842113,185737,1.0,16,-1075.0,-1105.0,5444.955,5044.050,1.0
3460377,2842113,185737,1.0,15,-1105.0,-1105.0,5444.955,5444.955,1.0
3421017,2842113,185737,1.0,14,-1135.0,-1137.0,5444.955,5444.955,1.0