In [1]:
import pandas as pd
import numpy as np

In [2]:
all_data = pd.read_csv('../data/application_train.csv')

In [8]:
all_data

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,GROUND_TRUTH
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,1
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0,0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0,0

In [19]:
dseb63_all_data = pd.read_csv('../data/dseb63_application_train.csv', index_col=0)
dseb63_all_data

,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_CURR
0,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,278621
1,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,139008
2,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,138348
3,0,Cash loans,M,N,Y,0,99000.0,490495.5,27517.5,454500.0,...,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0,64140
4,0,Cash loans,M,Y,Y,0,360000.0,1530000.0,42075.0,1530000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,219374
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246004,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,225000.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,90253
246005,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,225000.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,9027
246006,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,585000.0,...,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0,163598
246007,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,319500.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,300375
246008,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,675000.0,...,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0,258328

In [28]:
not_containted = []
check_col = set(dseb63_all_data.SK_ID_CURR)

for col in check_col:
    if col not in all_data.SK_ID_CURR:
        not_containted.append(col)
        
not_containted

[]

In [30]:
submissions = pd.read_csv('../submission/stacking_2.csv')

In [31]:
all_data['GROUND_TRUTH'] = all_data['TARGET']

In [32]:
submissions = submissions.merge(all_data[['SK_ID_CURR', 'GROUND_TRUTH']], on='SK_ID_CURR', how='left')

In [33]:
submissions

       SK_ID_CURR    TARGET  GROUND_TRUTH
0           83659  0.643848           NaN
1          174814  0.388921           0.0
2          179486  0.571501           NaN
3           57038  0.165856           NaN
4           25672  0.510052           NaN
...           ...       ...           ...
61497      150442  0.305741           0.0
61498        5217  0.344414           NaN
61499      260741  0.442308           0.0
61500      284794  0.237466           0.0
61501      258643  0.532437           0.0

[61502 rows x 3 columns]

In [34]:
submissions['GROUND_TRUTH'].isnull().sum()

25441

In [35]:
from sklearn.metrics import make_scorer, roc_auc_score
def gini_coefficient(y_true, y_pred):
    """
    Calculate the Gini coefficient using predictions and true labels.
    
    Parameters:
    y_true (array-like): True binary labels.
    y_pred (array-like): Predicted probabilities.
    
    Returns:
    float: Gini coefficient.
    """
    auc = roc_auc_score(y_true, y_pred)  # AUC calculation
    return 2 * auc - 1  # Gini coefficient

In [36]:
duplicate_sub = submissions[~submissions['GROUND_TRUTH'].isnull()]

In [37]:
duplicate_sub

       SK_ID_CURR    TARGET  GROUND_TRUTH
1          174814  0.388921           0.0
5          302672  0.571234           0.0
7          178370  0.699579           0.0
9          185100  0.609166           0.0
11         242167  0.762163           0.0
...           ...       ...           ...
61489      110986  0.524259           0.0
61497      150442  0.305741           0.0
61499      260741  0.442308           0.0
61500      284794  0.237466           0.0
61501      258643  0.532437           0.0

[36061 rows x 3 columns]

In [38]:
duplicate_sub['GROUND_TRUTH'].sum()

2901.0

In [39]:
duplicate_sub['GROUND_TRUTH'] = duplicate_sub['GROUND_TRUTH'].astype(int)

C:\Users\Admin\AppData\Local\Temp\ipykernel_43948\2521483845.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  duplicate_sub['GROUND_TRUTH'] = duplicate_sub['GROUND_TRUTH'].astype(int)

In [40]:
gini_coefficient(duplicate_sub['GROUND_TRUTH'], duplicate_sub['TARGET'])

-0.01956519298490722

In [41]:
y_true = duplicate_sub['GROUND_TRUTH'].values 
y_pred = duplicate_sub['TARGET'].values

y_true = np.concatenate([y_true, np.zeros(20000), np.ones(5000)])
y_pred = np.concatenate([y_pred, np.zeros(20000), np.ones(5000)])

gini_coefficient(y_true, y_pred)

0.7664874549411267