In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
def display_missing_data_info(dataframe, ascending=False):
    missing_values_count = dataframe.isnull().sum()
    missing_values_percentage = (dataframe.isnull().mean() * 100)
    missing_data = pd.DataFrame({
        'Missing Values': missing_values_count,
        'Percentage (%)': missing_values_percentage
    })
    
    missing_data = missing_data[missing_data['Missing Values'] > 0]
    
    sorted_missing_data = missing_data.sort_values(by='Missing Values', ascending=ascending)

    print(sorted_missing_data)
    return sorted_missing_data

In [3]:
pos_cash = pd.read_csv('../data/dseb63_POS_CASH_balance.csv')

In [4]:
pos_cash.head()

,SK_ID_PREV,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
0,1803195,-31,48.0,45.0,Active,0,0,185279
1,1803195,-17,48.0,31.0,Active,0,0,185279
2,1803195,-21,48.0,35.0,Active,0,0,185279
3,1803195,-8,48.0,21.0,Active,0,0,185279
4,1803195,-4,48.0,17.0,Active,0,0,185279

In [5]:
pos_cash['SK_ID_PREV'].nunique()

800337

In [6]:
pos_cash.shape

(8543375, 8)

In [7]:
pos_cash['SK_ID_CURR'].value_counts()

SK_ID_CURR
246424    295
275886    246
120716    245
211252    245
27849     245
         ...
300257      1
184344      1
148274      1
280216      1
265502      1
Name: count, Length: 289444, dtype: int64

In [8]:
sample =  pos_cash[pos_cash['SK_ID_CURR'] == 81403]
sample

,SK_ID_PREV,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
10800,1192377,-36,15.0,0.0,Completed,0,0,81403
10801,2356760,-37,48.0,48.0,Active,0,0,81403
10802,2356760,-12,48.0,23.0,Active,0,0,81403
10803,2188627,-16,10.0,4.0,Active,0,0,81403
10804,2356760,-13,48.0,24.0,Active,0,0,81403
...,...,...,...,...,...,...,...,...
10870,2356760,-36,48.0,47.0,Active,0,0,81403
10871,1567282,-74,5.0,4.0,Active,0,0,81403
10872,1192377,-38,24.0,11.0,Active,0,0,81403
10873,1192377,-51,24.0,24.0,Active,0,0,81403
10874,2188627,-22,10.0,10.0,Active,0,0,81403

In [9]:
pos_cash.shape

(8543375, 8)

In [10]:
sample.sort_values(by=['SK_ID_PREV','MONTHS_BALANCE'], ascending=False, inplace=True)
sample

/tmp/ipykernel_503091/3119951421.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample.sort_values(by=['SK_ID_PREV','MONTHS_BALANCE'], ascending=False, inplace=True)

,SK_ID_PREV,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
10869,2356760,-1,48.0,12.0,Active,0,0,81403
10853,2356760,-2,48.0,13.0,Active,0,0,81403
10846,2356760,-3,48.0,14.0,Active,0,0,81403
10834,2356760,-4,48.0,15.0,Active,0,0,81403
10826,2356760,-5,48.0,16.0,Active,0,0,81403
...,...,...,...,...,...,...,...,...
10861,1034909,-4,10.0,7.0,Active,0,0,81403
10868,1034909,-5,10.0,8.0,Active,0,0,81403
10862,1034909,-6,10.0,9.0,Active,0,0,81403
10863,1034909,-7,10.0,10.0,Active,0,0,81403
10857,1034909,-9,NaN,NaN,Returned to the store,0,0,81403

In [11]:
pos_cash['NAME_CONTRACT_STATUS'].value_counts()

NAME_CONTRACT_STATUS
Active                   7818577
Completed                 634872
Signed                     74625
Demand                      6110
Returned to the store       4591
Approved                    4221
Amortized debt               365
Canceled                      12
XNA                            2
Name: count, dtype: int64

Explain

Signed, approve mean the same (start)

ignore cancel, xna
amortized debt is when they pay the premium

In [12]:
pos_cash = pos_cash[pos_cash['NAME_CONTRACT_STATUS'] != 'XNA']
pos_cash = pos_cash[pos_cash['NAME_CONTRACT_STATUS'] != 'Canceled']

In [13]:
pos_cash[pos_cash['NAME_CONTRACT_STATUS'] == 'Returned to the store']

,SK_ID_PREV,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
2268,1057204,-48,9.0,9.0,Returned to the store,0,0,50135
2312,2466272,-48,9.0,9.0,Returned to the store,0,0,44148
10857,1034909,-9,NaN,NaN,Returned to the store,0,0,81403
10937,2310290,-13,NaN,NaN,Returned to the store,0,0,43381
12608,2320737,-41,14.0,14.0,Returned to the store,0,0,274824
...,...,...,...,...,...,...,...,...
8543101,1100545,-4,NaN,NaN,Returned to the store,0,0,166931
8543135,1769702,-1,NaN,NaN,Returned to the store,0,0,42387
8543136,2522548,-1,8.0,8.0,Returned to the store,0,0,73277
8543288,1613089,-3,NaN,NaN,Returned to the store,0,0,35719
8543351,2382493,-1,NaN,NaN,Returned to the store,0,0,270542

In [14]:
pos_cash['SK_DPD_DEF'].value_counts()

SK_DPD_DEF
0       8444251
1         19080
2         12710
3         10134
4          8285
         ...
2494          1
1278          1
2221          1
1337          1
1505          1
Name: count, Length: 1987, dtype: int64

## Feature to collect
- Group by id prev
- total installment
- Get complete
- original installment
- mean SK_DPD
- mean SK_DPD_DEF
- Count Demand
- Count Returned to the store
- Count Approved
- Count Amortized debt
- Lastest payment month
- Flag short-term (<=12 month)
- Future
- Payment last 3 month
- Payment last 6 month
- Payment last 12 month
- Payment last 24 month

In [15]:
pos_cash['COMPLETED'] = pos_cash['NAME_CONTRACT_STATUS'] == 'Completed'
pos_cash['COUNT_DEMAND'] = pos_cash['NAME_CONTRACT_STATUS'] == 'Demand'
pos_cash['COUNT_SIGNED'] = pos_cash['NAME_CONTRACT_STATUS'] == 'Signed'
pos_cash['COUNT_APPROVED'] = pos_cash['NAME_CONTRACT_STATUS'] == 'Approved'
pos_cash['COUNT_RETURNED'] = pos_cash['NAME_CONTRACT_STATUS'] == 'Returned to the store'

In [16]:
pos_cash['LAST_3_MONTHS'] = pos_cash['MONTHS_BALANCE'] >= -3
pos_cash['LAST_6_MONTHS'] = pos_cash['MONTHS_BALANCE'] >= -6
pos_cash['LAST_12_MONTHS'] = pos_cash['MONTHS_BALANCE'] >= -12
pos_cash['LAST_36_MONTHS'] = pos_cash['MONTHS_BALANCE'] >= -36

In [17]:
pos_cash['NUM_INSTALMENT'] = 1

In [18]:
pos_cash['COUNT_SK_DPD'] = pos_cash['SK_DPD'] > 0
pos_cash['COUNT_SK_DPD_DEF'] = pos_cash['SK_DPD_DEF'] > 0

pos_cash['MEAN_SK_DPD'] = pos_cash['SK_DPD']
pos_cash['MEAN_SK_DPD_DEF'] = pos_cash['SK_DPD_DEF']

In [19]:
gb_pos_cash = pos_cash.groupby('SK_ID_PREV').agg({
    'SK_ID_CURR': 'first',
    'NUM_INSTALMENT': 'sum',
    'COMPLETED': 'sum',
    'COUNT_DEMAND': 'sum',
    'COUNT_SIGNED': 'sum',
    'COUNT_APPROVED': 'sum',
    'COUNT_RETURNED': 'sum',
    'CNT_INSTALMENT': 'max',
    'MONTHS_BALANCE': 'max',
    
    'COUNT_SK_DPD':'sum',
    'COUNT_SK_DPD_DEF':'sum',
    
    'SK_DPD':'sum',
    'SK_DPD_DEF':'sum',
    
    'MEAN_SK_DPD':'mean',
    'MEAN_SK_DPD_DEF':'mean',
    
    'CNT_INSTALMENT_FUTURE':'min',
    'LAST_3_MONTHS':'sum',
    'LAST_6_MONTHS':'sum',
    'LAST_12_MONTHS':'sum',
    'LAST_36_MONTHS':'sum',
}).reset_index()

gb_pos_cash

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT,COMPLETED,COUNT_DEMAND,COUNT_SIGNED,COUNT_APPROVED,COUNT_RETURNED,CNT_INSTALMENT,MONTHS_BALANCE,...,COUNT_SK_DPD_DEF,SK_DPD,SK_DPD_DEF,MEAN_SK_DPD,MEAN_SK_DPD_DEF,CNT_INSTALMENT_FUTURE,LAST_3_MONTHS,LAST_6_MONTHS,LAST_12_MONTHS,LAST_36_MONTHS
0,1000001,117953,3,1,0,0,0,0,12.0,-8,...,0,0,0,0.0,0.0,0.0,0,0,3,3
1,1000003,6707,4,0,0,0,0,0,12.0,-1,...,0,0,0,0.0,0.0,9.0,3,4,4,4
2,1000004,187620,8,1,0,0,0,0,10.0,-22,...,0,0,0,0.0,0.0,0.0,0,0,0,8
3,1000005,83759,11,1,0,0,0,0,10.0,-46,...,0,0,0,0.0,0.0,0.0,0,0,0,0
4,1000007,25033,5,0,0,0,0,0,6.0,-1,...,0,0,0,0.0,0.0,2.0,3,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
800331,2843494,70155,3,1,0,0,0,0,48.0,-24,...,0,0,0,0.0,0.0,0.0,0,0,0,3
800332,2843495,274857,8,1,0,0,0,0,60.0,-9,...,0,0,0,0.0,0.0,0.0,0,0,4,8
800333,2843497,50590,21,0,0,0,0,0,24.0,-1,...,0,0,0,0.0,0.0,4.0,3,6,12,21
800334,2843498,12906,7,1,0,0,0,0,36.0,-42,...,0,0,0,0.0,0.0,0.0,0,0,0,0
800335,2843499,237534,11,1,0,0,0,0,60.0,-30,...,0,0,0,0.0,0.0,0.0,0,0,0,7

In [20]:
gb_pos_cash['LONG_TERM'] = gb_pos_cash['CNT_INSTALMENT'] > 24
gb_pos_cash['SHORT_TERM'] = gb_pos_cash['CNT_INSTALMENT'] <= 24

## Group by id_curr

- total installment
- Get complete
- mean SK_DPD
- mean SK_DPD_DEF
- Duration (max - min)
- Count Demand
- Count Returned to the store
- Count Approved
- Count Amortized debt
- Lastest payment month
- Payment last 3 month
- Payment last 6 month
- Payment last 12 month
- Payment last 36 month


# Completed 
- Count short/long
- Average duration short/long
- rate installment (actual paid/supposed paid) short/long
- Complete last 12 month short/long
- Complete last 36 month short/long

# Other 
- Count short/long
- Average duration short/long
- Sum upcoming future
- Payment last 6 month
- Payment last 12 month

In [21]:
gb_pos_cash_by_curr = gb_pos_cash.groupby('SK_ID_CURR').agg({
    'NUM_INSTALMENT': 'sum',
    'COMPLETED': ['sum', 'mean'],
    'COUNT_DEMAND': 'sum',
    'COUNT_SIGNED': 'sum',
    'COUNT_APPROVED': ['sum', 'mean'],
    'COUNT_RETURNED': 'sum',
    'CNT_INSTALMENT': ['sum', 'mean', 'var'],
    'MONTHS_BALANCE': 'max',
    
    'SK_DPD':['sum', 'mean', 'max', 'var'],
    'SK_DPD_DEF':['sum', 'mean', 'max', 'var'],
    
    'COUNT_SK_DPD':['sum', 'max', 'mean', 'var'],
    'COUNT_SK_DPD_DEF':['sum', 'max', 'mean', 'var'],
    
    'MEAN_SK_DPD':['sum', 'mean', 'max', 'var'],
    'MEAN_SK_DPD_DEF':['sum', 'mean', 'max', 'var'],
    
    'CNT_INSTALMENT_FUTURE':'sum',
    
    'LAST_3_MONTHS':'sum',
    'LAST_6_MONTHS':'sum',
    'LAST_12_MONTHS':'sum',
    'LAST_36_MONTHS':'sum',
}).reset_index()

gb_pos_cash_by_curr.columns = ['GENERAL_'+'_'.join(col).strip() for col in gb_pos_cash_by_curr.columns.values]
gb_pos_cash_by_curr.rename(columns={'GENERAL_SK_ID_CURR_':'SK_ID_CURR'}, inplace=True)

In [22]:
gb_pos_cash_complete = gb_pos_cash[gb_pos_cash['COMPLETED'] > 0]
gb_pos_cash_not_complete = gb_pos_cash[gb_pos_cash['COMPLETED'] == 0]

In [23]:
gb_pos_cash_complete['RATE_COMPLETED'] = gb_pos_cash_complete['CNT_INSTALMENT'] / gb_pos_cash_complete['NUM_INSTALMENT']

/tmp/ipykernel_503091/3735522127.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gb_pos_cash_complete['RATE_COMPLETED'] = gb_pos_cash_complete['CNT_INSTALMENT'] / gb_pos_cash_complete['NUM_INSTALMENT']

In [24]:
gb_pos_cash_complete_long_term = gb_pos_cash_complete[gb_pos_cash_complete['LONG_TERM'] == 1]
gb_pos_cash_complete_short_term = gb_pos_cash_complete[gb_pos_cash_complete['LONG_TERM'] == 0]

In [25]:
gb_pos_cash_complete_long_term_by_curr = gb_pos_cash_complete_long_term.groupby('SK_ID_CURR').agg({
    'CNT_INSTALMENT': 'mean',
    'RATE_COMPLETED': 'mean',
    'SK_ID_PREV': 'count',
    'NUM_INSTALMENT': 'sum',
    'LONG_TERM': 'sum',
    'LAST_12_MONTHS': 'sum',
    'LAST_36_MONTHS': 'sum',
    'SK_DPD':'sum',
    'SK_DPD_DEF':'sum',
}).reset_index()

In [26]:
gb_pos_cash_complete_long_term_by_curr.rename(columns={col: 'LONG_TERM_' + col for col in gb_pos_cash_complete_long_term_by_curr.columns if col != 'SK_ID_CURR'}, inplace=True)

In [27]:
gb_pos_cash_complete_short_term_by_curr = gb_pos_cash_complete_short_term.groupby('SK_ID_CURR').agg({
    'CNT_INSTALMENT': 'mean',
    'RATE_COMPLETED': 'mean',
    'SK_ID_PREV': 'count',
    'NUM_INSTALMENT': 'sum',
    'LAST_12_MONTHS': 'sum',
    'LAST_36_MONTHS': 'sum',
    'SK_DPD':'sum',
    'SK_DPD_DEF':'sum',
}).reset_index()

In [28]:
gb_pos_cash_complete_short_term_by_curr.rename(columns={col: 'SHORT_TERM_' + col for col in gb_pos_cash_complete_short_term_by_curr.columns if col != 'SK_ID_CURR'}, inplace=True)

In [29]:
gb_pos_cash_not_complete['SHORT_CNT_INSTALMENT'] = gb_pos_cash_complete_short_term['CNT_INSTALMENT'] * gb_pos_cash_complete_short_term['SHORT_TERM']
gb_pos_cash_not_complete['LONG_CNT_INSTALMENT'] = gb_pos_cash_complete_long_term['CNT_INSTALMENT'] * gb_pos_cash_complete_long_term['LONG_TERM']

gb_pos_cash_not_complete_by_curr = gb_pos_cash_not_complete.groupby('SK_ID_CURR').agg({
    'SHORT_CNT_INSTALMENT': 'sum',
    'LONG_CNT_INSTALMENT' : 'sum',
    'LAST_12_MONTHS': 'sum',
    'LAST_36_MONTHS': 'sum',
    'CNT_INSTALMENT_FUTURE': 'sum',
    'SK_DPD':'sum',
    'SK_DPD_DEF':'sum',
}).reset_index()

/tmp/ipykernel_503091/3390220829.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gb_pos_cash_not_complete['SHORT_CNT_INSTALMENT'] = gb_pos_cash_complete_short_term['CNT_INSTALMENT'] * gb_pos_cash_complete_short_term['SHORT_TERM']
/tmp/ipykernel_503091/3390220829.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gb_pos_cash_not_complete['LONG_CNT_INSTALMENT'] = gb_pos_cash_complete_long_term['CNT_INSTALMENT'] * gb_pos_cash_complete_long_term['LONG_TERM']

In [30]:
gb_pos_cash_not_complete_by_curr.rename(columns={col: 'NOT_COMPLETED_' + col for col in gb_pos_cash_not_complete_by_curr.columns if col != 'SK_ID_CURR'}, inplace=True)

In [31]:
gb_pos_cash_by_curr = gb_pos_cash_by_curr.merge(gb_pos_cash_complete_long_term_by_curr, on='SK_ID_CURR', how='left')
gb_pos_cash_by_curr = gb_pos_cash_by_curr.merge(gb_pos_cash_complete_short_term_by_curr, on='SK_ID_CURR', how='left')
gb_pos_cash_by_curr = gb_pos_cash_by_curr.merge(gb_pos_cash_not_complete_by_curr, on='SK_ID_CURR', how='left')

In [32]:
gb_pos_cash_by_curr

,SK_ID_CURR,GENERAL_NUM_INSTALMENT_sum,GENERAL_COMPLETED_sum,GENERAL_COMPLETED_mean,GENERAL_COUNT_DEMAND_sum,GENERAL_COUNT_SIGNED_sum,GENERAL_COUNT_APPROVED_sum,GENERAL_COUNT_APPROVED_mean,GENERAL_COUNT_RETURNED_sum,GENERAL_CNT_INSTALMENT_sum,...,SHORT_TERM_LAST_36_MONTHS,SHORT_TERM_SK_DPD,SHORT_TERM_SK_DPD_DEF,NOT_COMPLETED_SHORT_CNT_INSTALMENT,NOT_COMPLETED_LONG_CNT_INSTALMENT,NOT_COMPLETED_LAST_12_MONTHS,NOT_COMPLETED_LAST_36_MONTHS,NOT_COMPLETED_CNT_INSTALMENT_FUTURE,NOT_COMPLETED_SK_DPD,NOT_COMPLETED_SK_DPD_DEF
0,0,15,3,0.75,0,0,0,0.0,0,40.0,...,14.0,0.0,0.0,0.0,0.0,1.0,1.0,12.0,0.0,0.0
1,1,23,2,1.00,0,0,0,0.0,0,46.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,34,3,0.75,0,0,0,0.0,0,30.0,...,13.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,3,14,3,1.00,0,0,0,0.0,0,34.0,...,14.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,7,0,0.00,0,0,0,0.0,0,6.0,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289439,307505,20,2,1.00,0,0,0,0.0,0,18.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289440,307506,47,4,1.00,0,0,0,0.0,0,42.0,...,39.0,38.0,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289441,307508,46,2,0.50,0,1,0,0.0,0,44.0,...,25.0,0.0,0.0,0.0,0.0,9.0,9.0,3.0,0.0,0.0
289442,307509,16,2,1.00,0,0,0,0.0,0,18.0,...,7.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289443,307510,11,1,1.00,0,0,0,0.0,0,10.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
gb_pos_cash_by_curr.to_parquet('../data/dseb63_pos_cash_gb_v2.parquet', index=False)

In [34]:
import pandas as pd
df = pd.read_csv('../data/dseb63_pos_cash_gb.csv')
df

,SK_ID_CURR,NUM_INSTALMENT,COMPLETED,COUNT_DEMAND,COUNT_SIGNED,COUNT_APPROVED,COUNT_RETURNED,CNT_INSTALMENT,MONTHS_BALANCE,SK_DPD,...,SHORT_TERM_RATE_COMPLETED,SHORT_TERM_SK_ID_PREV,SHORT_TERM_NUM_INSTALMENT,SHORT_TERM_LAST_12_MONTHS,SHORT_TERM_LAST_36_MONTHS,NOT_COMPLETED_SHORT_CNT_INSTALMENT,NOT_COMPLETED_LONG_CNT_INSTALMENT,NOT_COMPLETED_LAST_6_MONTHS,NOT_COMPLETED_LAST_12_MONTHS,NOT_COMPLETED_CNT_INSTALMENT_FUTURE
0,0,15,3,0,0,0,0,40.0,-1,0.000000,...,2.055556,3.0,14.0,11.0,14.0,0.0,0.0,1.0,1.0,12.0
1,1,23,2,0,0,0,0,46.0,-12,1.208333,...,0.909091,1.0,11.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
2,2,34,3,0,0,0,0,30.0,-23,0.000000,...,0.841026,3.0,28.0,0.0,13.0,0.0,0.0,0.0,0.0,1.0
3,3,14,3,0,0,0,0,34.0,-5,0.000000,...,2.577778,3.0,14.0,9.0,14.0,NaN,NaN,NaN,NaN,NaN
4,4,7,0,0,0,0,0,6.0,-73,0.000000,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289439,307505,20,2,0,0,0,0,18.0,-40,0.000000,...,0.898990,2.0,20.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
289440,307506,47,4,0,0,0,0,42.0,-2,1.187500,...,0.879808,4.0,47.0,11.0,39.0,NaN,NaN,NaN,NaN,NaN
289441,307508,46,2,0,1,0,0,44.0,-1,0.000000,...,0.883117,2.0,25.0,8.0,25.0,0.0,0.0,6.0,9.0,3.0
289442,307509,16,2,0,0,0,0,18.0,-25,0.000000,...,1.095238,2.0,16.0,0.0,7.0,NaN,NaN,NaN,NaN,NaN
289443,307510,11,1,0,0,0,0,10.0,-72,0.000000,...,0.909091,1.0,11.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN