In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
def display_missing_data_info(dataframe, ascending=False):
    missing_values_count = dataframe.isnull().sum()
    missing_values_percentage = (dataframe.isnull().mean() * 100)
    missing_data = pd.DataFrame({
        'Missing Values': missing_values_count,
        'Percentage (%)': missing_values_percentage
    })
    
    missing_data = missing_data[missing_data['Missing Values'] > 0]
    
    sorted_missing_data = missing_data.sort_values(by='Missing Values', ascending=ascending)

    print(sorted_missing_data)
    return sorted_missing_data

In [3]:
pos_cash = pd.read_csv('../data/dseb63_POS_CASH_balance.csv')

In [4]:
pos_cash.head()

,SK_ID_PREV,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
0,1803195,-31,48.0,45.0,Active,0,0,185279
1,1803195,-17,48.0,31.0,Active,0,0,185279
2,1803195,-21,48.0,35.0,Active,0,0,185279
3,1803195,-8,48.0,21.0,Active,0,0,185279
4,1803195,-4,48.0,17.0,Active,0,0,185279

In [5]:
pos_cash['SK_ID_PREV'].nunique()

800337

In [6]:
pos_cash.shape

(8543375, 8)

In [7]:
pos_cash['SK_ID_CURR'].value_counts()

SK_ID_CURR
246424    295
275886    246
120716    245
211252    245
27849     245
         ...
300257      1
184344      1
148274      1
280216      1
265502      1
Name: count, Length: 289444, dtype: int64

In [32]:
sample =  pos_cash[pos_cash['SK_ID_CURR'] == 14101]
sample

,SK_ID_PREV,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
4777,1752714,-39,24.0,8.0,Active,0,0,14101
4778,2225558,-14,42.0,39.0,Active,0,0,14101
4779,2225558,-15,42.0,40.0,Active,0,0,14101
4780,1752714,-45,24.0,14.0,Active,0,0,14101
4781,2225558,-16,42.0,41.0,Active,0,0,14101
...,...,...,...,...,...,...,...,...
4867,2293530,-41,10.0,4.0,Active,0,0,14101
4868,2726628,-63,6.0,4.0,Active,0,0,14101
4869,1874404,-94,12.0,1.0,Active,0,0,14101
4870,1752714,-54,24.0,23.0,Active,0,0,14101
4871,1874404,-91,12.0,0.0,Completed,0,0,14101

In [9]:
pos_cash.shape

(8543375, 8)

In [33]:
sample.sort_values(by=['SK_ID_PREV','MONTHS_BALANCE'], ascending=False, inplace=True)
sample

C:\Users\Admin\AppData\Local\Temp\ipykernel_23208\3119951421.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample.sort_values(by=['SK_ID_PREV','MONTHS_BALANCE'], ascending=False, inplace=True)

,SK_ID_PREV,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
4812,2726628,-59,6.0,0.0,Completed,0,0,14101
4809,2726628,-60,6.0,1.0,Active,0,0,14101
4819,2726628,-61,6.0,1.0,Active,0,0,14101
4791,2726628,-62,6.0,2.0,Active,0,0,14101
4868,2726628,-63,6.0,4.0,Active,0,0,14101
...,...,...,...,...,...,...,...,...
4854,1520456,-40,4.0,0.0,Completed,0,0,14101
4834,1520456,-41,4.0,1.0,Active,0,0,14101
4833,1520456,-42,4.0,2.0,Active,0,0,14101
4853,1520456,-43,4.0,3.0,Active,0,0,14101
4801,1520456,-44,4.0,4.0,Active,0,0,14101

In [19]:
pos_cash['NAME_CONTRACT_STATUS'].value_counts()

NAME_CONTRACT_STATUS
Active                   7818577
Completed                 634872
Signed                     74625
Demand                      6110
Returned to the store       4591
Approved                    4221
Amortized debt               365
Canceled                      12
XNA                            2
Name: count, dtype: int64

Explain

Signed, approve mean the same (start)

ignore cancel, xna
amortized debt is when they pay the premium

In [31]:
pos_cash[pos_cash['NAME_CONTRACT_STATUS'] == 'Approved']

,SK_ID_PREV,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
133,1233945,-60,8.0,8.0,Approved,0,0,272857
4806,2225558,-17,42.0,42.0,Approved,0,0,14101
5264,1775090,-16,NaN,NaN,Approved,0,0,294163
7696,2643924,-10,NaN,NaN,Approved,0,0,16342
7725,2522531,-16,NaN,NaN,Approved,0,0,16342
...,...,...,...,...,...,...,...,...
8534154,1596298,-10,NaN,NaN,Approved,0,0,216129
8538261,2334497,-5,NaN,NaN,Approved,0,0,121876
8542623,2291473,-2,NaN,NaN,Approved,0,0,117912
8542785,1223338,-1,NaN,NaN,Approved,0,0,67123
8543138,2429149,-2,NaN,NaN,Approved,0,0,170700

In [18]:
pos_cash['SK_DPD_DEF'].value_counts()

SK_DPD_DEF
0       8444265
1         19080
2         12710
3         10134
4          8285
         ...
2494          1
1278          1
2221          1
1337          1
1505          1
Name: count, Length: 1987, dtype: int64

## Feature to collect
- Group by id prev
- total installment
- Get complete
- original installment
- sum