In [2]:
import pandas as pd 
import os 
import numpy as np

In [3]:
ds_root_dir = "/kaggle/input/dseb-64-data-preparation-final-project/dseb63_final_project_DP_dataset/dseb63_final_project_DP_dataset"

In [4]:
prev_app = pd.read_csv(os.path.join(ds_root_dir, "dseb63_previous_application.csv"))

In [5]:
prev_app.head()

,SK_ID_PREV,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,...,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL,SK_ID_CURR
0,2030495,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,Y,...,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0,293189
1,1696966,Consumer loans,68258.655,1800000.0,1754721.0,180000.0,1800000.0,SATURDAY,18,Y,...,36.0,low_normal,POS industry with interest,NaN,NaN,NaN,NaN,NaN,NaN,293189
2,2154916,Consumer loans,12417.390,108400.5,119848.5,0.0,108400.5,SUNDAY,14,Y,...,12.0,middle,POS industry with interest,365243.0,-512.0,-182.0,-392.0,-387.0,0.0,293189
3,2802425,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,Y,...,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0,91587
4,1536272,Cash loans,21709.125,450000.0,512370.0,NaN,450000.0,WEDNESDAY,9,Y,...,36.0,low_normal,Cash X-Sell: low,365243.0,-485.0,565.0,-155.0,-147.0,1.0,91587

In [7]:
prev_app.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1413701 entries, 0 to 1413700
Data columns (total 37 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   SK_ID_PREV                   1413701 non-null  int64
 1   NAME_CONTRACT_TYPE           1413701 non-null  object
 2   AMT_ANNUITY                  1106483 non-null  float64
 3   AMT_APPLICATION              1413701 non-null  float64
 4   AMT_CREDIT                   1413700 non-null  float64
 5   AMT_DOWN_PAYMENT             664161 non-null   float64
 6   AMT_GOODS_PRICE              1094176 non-null  float64
 7   WEEKDAY_APPR_PROCESS_START   1413701 non-null  object
 8   HOUR_APPR_PROCESS_START      1413701 non-null  int64
 9   FLAG_LAST_APPL_PER_CONTRACT  1413701 non-null  object
 10  NFLAG_LAST_APPL_IN_DAY       1413701 non-null  int64
 11  RATE_DOWN_PAYMENT            664161 non-null   float64
 12  RATE_INTEREST_PRIMARY        4791 non-null     float64
 13  RATE_INTEREST_PRIVILEGED     4791 non-null     float64
 14  NAME_CASH_LOAN_PURPOSE       1413701 non-null  object
 15  NAME_CONTRACT_STATUS         1413701 non-null  object
 16  DAYS_DECISION                1413701 non-null  int64
 17  NAME_PAYMENT_TYPE            1413701 non-null  object
 18  CODE_REJECT_REASON           1413701 non-null  object
 19  NAME_TYPE_SUITE              719029 non-null   object
 20  NAME_CLIENT_TYPE             1413701 non-null  object
 21  NAME_GOODS_CATEGORY          1413701 non-null  object
 22  NAME_PORTFOLIO               1413701 non-null  object
 23  NAME_PRODUCT_TYPE            1413701 non-null  object
 24  CHANNEL_TYPE                 1413701 non-null  object
 25  SELLERPLACE_AREA             1413701 non-null  int64
 26  NAME_SELLER_INDUSTRY         1413701 non-null  object
 27  CNT_PAYMENT                  1106488 non-null  float64
 28  NAME_YIELD_GROUP             1413701 non-null  object
 29  PRODUCT_COMBINATION          1413388 non-null  object
 30  DAYS_FIRST_DRAWING           852595 non-null   float64
 31  DAYS_FIRST_DUE               852595 non-null   float64
 32  DAYS_LAST_DUE_1ST_VERSION    852595 non-null   float64
 33  DAYS_LAST_DUE                852595 non-null   float64
 34  DAYS_TERMINATION             852595 non-null   float64
 35  NFLAG_INSURED_ON_APPROVAL    852595 non-null   float64
 36  SK_ID_CURR                   1413701 non-null  int64
dtypes: float64(15), int64(6), object(16)
memory usage: 399.1+ MB

In [8]:
def display_missing_data_info(dataframe, ascending=False):
    missing_values_count = dataframe.isnull().sum()
    missing_values_percentage = (dataframe.isnull().mean() * 100)
    missing_data = pd.DataFrame({
        'Missing Values': missing_values_count,
        'Percentage (%)': missing_values_percentage
    })
    
    missing_data = missing_data[missing_data['Missing Values'] > 0]
    
    sorted_missing_data = missing_data.sort_values(by='Missing Values', ascending=ascending)

    #print(sorted_missing_data)
    return sorted_missing_data

In [10]:
display_missing_data_info(prev_app)

                           Missing Values  Percentage (%)
RATE_INTEREST_PRIMARY             1408910       99.661102
RATE_INTEREST_PRIVILEGED          1408910       99.661102
AMT_DOWN_PAYMENT                   749540       53.019698
RATE_DOWN_PAYMENT                  749540       53.019698
NAME_TYPE_SUITE                    694672       49.138538
DAYS_FIRST_DRAWING                 561106       39.690571
DAYS_FIRST_DUE                     561106       39.690571
DAYS_LAST_DUE_1ST_VERSION          561106       39.690571
DAYS_LAST_DUE                      561106       39.690571
DAYS_TERMINATION                   561106       39.690571
NFLAG_INSURED_ON_APPROVAL          561106       39.690571
AMT_GOODS_PRICE                    319525       22.602021
AMT_ANNUITY                        307218       21.731469
CNT_PAYMENT                        307213       21.731116
PRODUCT_COMBINATION                   313        0.022140
AMT_CREDIT                              1        0.000071

                           Missing Values  Percentage (%)
RATE_INTEREST_PRIMARY             1408910       99.661102
RATE_INTEREST_PRIVILEGED          1408910       99.661102
AMT_DOWN_PAYMENT                   749540       53.019698
RATE_DOWN_PAYMENT                  749540       53.019698
NAME_TYPE_SUITE                    694672       49.138538
DAYS_FIRST_DRAWING                 561106       39.690571
DAYS_FIRST_DUE                     561106       39.690571
DAYS_LAST_DUE_1ST_VERSION          561106       39.690571
DAYS_LAST_DUE                      561106       39.690571
DAYS_TERMINATION                   561106       39.690571
NFLAG_INSURED_ON_APPROVAL          561106       39.690571
AMT_GOODS_PRICE                    319525       22.602021
AMT_ANNUITY                        307218       21.731469
CNT_PAYMENT                        307213       21.731116
PRODUCT_COMBINATION                   313        0.022140
AMT_CREDIT                              1        0.000071

In [11]:
prev_app.shape

(1413701, 37)

In [12]:
prev_app.columns

Index(['SK_ID_PREV', 'NAME_CONTRACT_TYPE', 'AMT_ANNUITY', 'AMT_APPLICATION',
       'AMT_CREDIT', 'AMT_DOWN_PAYMENT', 'AMT_GOODS_PRICE',
       'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START',
       'FLAG_LAST_APPL_PER_CONTRACT', 'NFLAG_LAST_APPL_IN_DAY',
       'RATE_DOWN_PAYMENT', 'RATE_INTEREST_PRIMARY',
       'RATE_INTEREST_PRIVILEGED', 'NAME_CASH_LOAN_PURPOSE',
       'NAME_CONTRACT_STATUS', 'DAYS_DECISION', 'NAME_PAYMENT_TYPE',
       'CODE_REJECT_REASON', 'NAME_TYPE_SUITE', 'NAME_CLIENT_TYPE',
       'NAME_GOODS_CATEGORY', 'NAME_PORTFOLIO', 'NAME_PRODUCT_TYPE',
       'CHANNEL_TYPE', 'SELLERPLACE_AREA', 'NAME_SELLER_INDUSTRY',
       'CNT_PAYMENT', 'NAME_YIELD_GROUP', 'PRODUCT_COMBINATION',
       'DAYS_FIRST_DRAWING', 'DAYS_FIRST_DUE', 'DAYS_LAST_DUE_1ST_VERSION',
       'DAYS_LAST_DUE', 'DAYS_TERMINATION', 'NFLAG_INSURED_ON_APPROVAL',
       'SK_ID_CURR'],
      dtype='object')

In [13]:
print(prev_app['SK_ID_CURR'].nunique())
print(prev_app['SK_ID_PREV'].nunique())

291057
1413701

There are repetitions in IDs in prev applications -> need to agg; prev id is unique

In [14]:
nan_as_category = True 
num_rows = None

In [15]:
def OHE(df, nan_as_category = True):
    original_cols = list(df.columns)
    categorical_columns = [col for col in df.columns if df[col].dtype == 'object']
    df = pd.get_dummies(df, columns= categorical_columns,
                        dummy_na= nan_as_category)
    new_columns = [c for c in df.columns if c not in original_cols]
    return df, new_columns

In [ ]:
#New features from old features

#Ratio: value ask / value received percentage
prev_app = prev_app.drop(prev_app[prev_app['AMT_CREDIT'].isnull() == True].index)  
prev_app['APP_CREDIT_PERC'] = prev_app['AMT_APPLICATION'] / prev_app['AMT_CREDIT']

#Churn_prev: Whether the payment date is late 
# 1= delayed, 0 = not delayed, NaN = null
k = prev_app.DAYS_LAST_DUE_1ST_VERSION - prev_app.DAYS_LAST_DUE
prev_app["CHURN_PREV"] = [1 if i >= 0 else (0 if i < 0  else "NaN") for i in k]

prev_app['AMT_DIFF_PERCENT'] = ((prev_app['AMT_CREDIT'] - prev_app['AMT_APPLICATION']) / prev_app['AMT_APPLICATION']) * 100
prev_app['ADJUSTMENT_DIRECTION'] = (prev_app['AMT_CREDIT'] - prev_app['AMT_APPLICATION']) >= 0
prev_app['ADJUSTMENT_DIRECTION'] = prev_app['ADJUSTMENT_DIRECTION'].map({'True': 1, 'False': 0}) #whether final credit amount is equal clients' application 

#Interest rate
prev_app['INTEREST'] = prev_app['CNT_PAYMENT']*prev_app['AMT_ANNUITY'] - prev_app['AMT_CREDIT']
prev_app['INTEREST_RATE'] = 2*12*prev_app['INTEREST']/(prev_app['AMT_CREDIT']*(prev_app['CNT_PAYMENT']+1))
prev_app['INTEREST_SHARE'] = prev_app['INTEREST']/prev_app['AMT_CREDIT']


prev_app["DAYS_DECISION"] = [1 if abs(i/(12*30)) <=1 else 0 for i in prev_app.DAYS_DECISION]

#Separate weekend from weekdays
prev_app["WEEKDAY_APPR_PROCESS_START"] = prev_app["WEEKDAY_APPR_PROCESS_START"].replace(['MONDAY','TUESDAY', 'WEDNESDAY','THURSDAY','FRIDAY'], 'WEEK_DAY')
prev_app["WEEKDAY_APPR_PROCESS_START"] = prev_app["WEEKDAY_APPR_PROCESS_START"].replace(['SATURDAY', 'SUNDAY'], 'WEEKEND')

#Separate working hours from off_hours
prev_app["HOUR_APPR_PROCESS_START"] = prev_app["HOUR_APPR_PROCESS_START"].replace([8,9,10,11,12,13,14,15,16,17], 'working_hours')
prev_app["HOUR_APPR_PROCESS_START"] = prev_app["HOUR_APPR_PROCESS_START"].replace([18,19,20,21,22,23,0,1,2,3,4,5,6,7], 'off_hours')

In [ ]:
 # NEW_INSURANCE variable has been defined to be used instead of NFLAG_INSURED_ON_APPROVAL variable.
#    df_prev[(df_prev['AMT_CREDIT'] == 0) | (df_prev['AMT_GOODS_PRICE'] == 0)]['NEW_INSURANCE'] = np.nan
 #   df_prev['sigorta_miktari'] = df_prev['AMT_CREDIT'] - df_prev['AMT_GOODS_PRICE']
 #   df_prev["NEW_INSURANCE"] = df_prev['sigorta_miktari'].apply(lambda x: 1 if x > 0 else (0 if x <= 0 else np.nan))
 #   df_prev.drop('sigorta_miktari', axis=1, inplace=True)

In [20]:
prev_app, cat_cols = OHE(prev_app, nan_as_category=True)

In [22]:
print(len(cat_cols))
print(cat_cols)

160
['NAME_CONTRACT_TYPE_Cash loans', 'NAME_CONTRACT_TYPE_Consumer loans', 'NAME_CONTRACT_TYPE_Revolving loans', 'NAME_CONTRACT_TYPE_XNA', 'NAME_CONTRACT_TYPE_nan', 'WEEKDAY_APPR_PROCESS_START_WEEKEND', 'WEEKDAY_APPR_PROCESS_START_WEEK_DAY', 'WEEKDAY_APPR_PROCESS_START_nan', 'HOUR_APPR_PROCESS_START_off_hours', 'HOUR_APPR_PROCESS_START_working_hours', 'HOUR_APPR_PROCESS_START_nan', 'FLAG_LAST_APPL_PER_CONTRACT_N', 'FLAG_LAST_APPL_PER_CONTRACT_Y', 'FLAG_LAST_APPL_PER_CONTRACT_nan', 'NAME_CASH_LOAN_PURPOSE_Building a house or an annex', 'NAME_CASH_LOAN_PURPOSE_Business development', 'NAME_CASH_LOAN_PURPOSE_Buying a garage', 'NAME_CASH_LOAN_PURPOSE_Buying a holiday home / land', 'NAME_CASH_LOAN_PURPOSE_Buying a home', 'NAME_CASH_LOAN_PURPOSE_Buying a new car', 'NAME_CASH_LOAN_PURPOSE_Buying a used car', 'NAME_CASH_LOAN_PURPOSE_Car repairs', 'NAME_CASH_LOAN_PURPOSE_Education', 'NAME_CASH_LOAN_PURPOSE_Everyday expenses', 'NAME_CASH_LOAN_PURPOSE_Furniture', 'NAME_CASH_LOAN_PURPOSE_Gasification / water supply', 'NAME_CASH_LOAN_PURPOSE_Hobby', 'NAME_CASH_LOAN_PURPOSE_Journey', 'NAME_CASH_LOAN_PURPOSE_Medicine', 'NAME_CASH_LOAN_PURPOSE_Money for a third person', 'NAME_CASH_LOAN_PURPOSE_Other', 'NAME_CASH_LOAN_PURPOSE_Payments on other loans', 'NAME_CASH_LOAN_PURPOSE_Purchase of electronic equipment', 'NAME_CASH_LOAN_PURPOSE_Refusal to name the goal', 'NAME_CASH_LOAN_PURPOSE_Repairs', 'NAME_CASH_LOAN_PURPOSE_Urgent needs', 'NAME_CASH_LOAN_PURPOSE_Wedding / gift / holiday', 'NAME_CASH_LOAN_PURPOSE_XAP', 'NAME_CASH_LOAN_PURPOSE_XNA', 'NAME_CASH_LOAN_PURPOSE_nan', 'NAME_CONTRACT_STATUS_Approved', 'NAME_CONTRACT_STATUS_Canceled', 'NAME_CONTRACT_STATUS_Refused', 'NAME_CONTRACT_STATUS_Unused offer', 'NAME_CONTRACT_STATUS_nan', 'NAME_PAYMENT_TYPE_Cash through the bank', 'NAME_PAYMENT_TYPE_Cashless from the account of the employer', 'NAME_PAYMENT_TYPE_Non-cash from your account', 'NAME_PAYMENT_TYPE_XNA', 'NAME_PAYMENT_TYPE_nan', 'CODE_REJECT_REASON_CLIENT', 'CODE_REJECT_REASON_HC', 'CODE_REJECT_REASON_LIMIT', 'CODE_REJECT_REASON_SCO', 'CODE_REJECT_REASON_SCOFR', 'CODE_REJECT_REASON_SYSTEM', 'CODE_REJECT_REASON_VERIF', 'CODE_REJECT_REASON_XAP', 'CODE_REJECT_REASON_XNA', 'CODE_REJECT_REASON_nan', 'NAME_TYPE_SUITE_Children', 'NAME_TYPE_SUITE_Family', 'NAME_TYPE_SUITE_Group of people', 'NAME_TYPE_SUITE_Other_A', 'NAME_TYPE_SUITE_Other_B', 'NAME_TYPE_SUITE_Spouse, partner', 'NAME_TYPE_SUITE_Unaccompanied', 'NAME_TYPE_SUITE_nan', 'NAME_CLIENT_TYPE_New', 'NAME_CLIENT_TYPE_Refreshed', 'NAME_CLIENT_TYPE_Repeater', 'NAME_CLIENT_TYPE_XNA', 'NAME_CLIENT_TYPE_nan', 'NAME_GOODS_CATEGORY_Additional Service', 'NAME_GOODS_CATEGORY_Animals', 'NAME_GOODS_CATEGORY_Audio/Video', 'NAME_GOODS_CATEGORY_Auto Accessories', 'NAME_GOODS_CATEGORY_Clothing and Accessories', 'NAME_GOODS_CATEGORY_Computers', 'NAME_GOODS_CATEGORY_Construction Materials', 'NAME_GOODS_CATEGORY_Consumer Electronics', 'NAME_GOODS_CATEGORY_Direct Sales', 'NAME_GOODS_CATEGORY_Education', 'NAME_GOODS_CATEGORY_Fitness', 'NAME_GOODS_CATEGORY_Furniture', 'NAME_GOODS_CATEGORY_Gardening', 'NAME_GOODS_CATEGORY_Homewares', 'NAME_GOODS_CATEGORY_Insurance', 'NAME_GOODS_CATEGORY_Jewelry', 'NAME_GOODS_CATEGORY_Medical Supplies', 'NAME_GOODS_CATEGORY_Medicine', 'NAME_GOODS_CATEGORY_Mobile', 'NAME_GOODS_CATEGORY_Office Appliances', 'NAME_GOODS_CATEGORY_Other', 'NAME_GOODS_CATEGORY_Photo / Cinema Equipment', 'NAME_GOODS_CATEGORY_Sport and Leisure', 'NAME_GOODS_CATEGORY_Tourism', 'NAME_GOODS_CATEGORY_Vehicles', 'NAME_GOODS_CATEGORY_Weapon', 'NAME_GOODS_CATEGORY_XNA', 'NAME_GOODS_CATEGORY_nan', 'NAME_PORTFOLIO_Cards', 'NAME_PORTFOLIO_Cars', 'NAME_PORTFOLIO_Cash', 'NAME_PORTFOLIO_POS', 'NAME_PORTFOLIO_XNA', 'NAME_PORTFOLIO_nan', 'NAME_PRODUCT_TYPE_XNA', 'NAME_PRODUCT_TYPE_walk-in', 'NAME_PRODUCT_TYPE_x-sell', 'NAME_PRODUCT_TYPE_nan', 'CHANNEL_TYPE_AP+ (Cash loan)', 'CHANNEL_TYPE_Car dealer', 'CHANNEL_TYPE_Channel of corporate sales', 'CHANNEL_TYPE_Contact center', 'CHANNEL_TYPE_Country-wide', 'CHANNEL_TYPE_Credit and cash offices', 'CHANNEL_TYPE_Regional / Local', 'CHANNEL_TYPE_Stone', 'CHANNEL_TYPE_nan', 'NAME_SELLER_INDUSTRY_Auto technology', 'NAME_SELLER_INDUSTRY_Clothing', 'NAME_SELLER_INDUSTRY_Connectivity', 'NAME_SELLER_INDUSTRY_Construction', 'NAME_SELLER_INDUSTRY_Consumer electronics', 'NAME_SELLER_INDUSTRY_Furniture', 'NAME_SELLER_INDUSTRY_Industry', 'NAME_SELLER_INDUSTRY_Jewelry', 'NAME_SELLER_INDUSTRY_MLM partners', 'NAME_SELLER_INDUSTRY_Tourism', 'NAME_SELLER_INDUSTRY_XNA', 'NAME_SELLER_INDUSTRY_nan', 'NAME_YIELD_GROUP_XNA', 'NAME_YIELD_GROUP_high', 'NAME_YIELD_GROUP_low_action', 'NAME_YIELD_GROUP_low_normal', 'NAME_YIELD_GROUP_middle', 'NAME_YIELD_GROUP_nan', 'PRODUCT_COMBINATION_Card Street', 'PRODUCT_COMBINATION_Card X-Sell', 'PRODUCT_COMBINATION_Cash', 'PRODUCT_COMBINATION_Cash Street: high', 'PRODUCT_COMBINATION_Cash Street: low', 'PRODUCT_COMBINATION_Cash Street: middle', 'PRODUCT_COMBINATION_Cash X-Sell: high', 'PRODUCT_COMBINATION_Cash X-Sell: low', 'PRODUCT_COMBINATION_Cash X-Sell: middle', 'PRODUCT_COMBINATION_POS household with interest', 'PRODUCT_COMBINATION_POS household without interest', 'PRODUCT_COMBINATION_POS industry with interest', 'PRODUCT_COMBINATION_POS industry without interest', 'PRODUCT_COMBINATION_POS mobile with interest', 'PRODUCT_COMBINATION_POS mobile without interest', 'PRODUCT_COMBINATION_POS other with interest', 'PRODUCT_COMBINATION_POS others without interest', 'PRODUCT_COMBINATION_nan', 'CHURN_PREV_0', 'CHURN_PREV_1', 'CHURN_PREV_NaN', 'CHURN_PREV_nan']

In [19]:
prev_app.dtypes.value_counts()

float64    21
object     18
int64       5
Name: count, dtype: int64

Aggregations

In [23]:
num_aggregations = {
                     'AMT_ANNUITY':             ['min', 'max', 'mean'],
                     'AMT_APPLICATION':         ['min', 'max', 'mean'],
                     'AMT_CREDIT':              ['min', 'max', 'mean'],
                     'APP_CREDIT_PERC':         ['min', 'max', 'mean', 'var'],
                     'AMT_DOWN_PAYMENT':        ['min', 'max', 'mean'],
                     'AMT_GOODS_PRICE':         ['min', 'max', 'mean'],
                     #'HOUR_APPR_PROCESS_START': ['min', 'max', 'mean'],
                     'RATE_DOWN_PAYMENT':       ['min', 'max', 'mean'],
                     'DAYS_DECISION':           ['min', 'max', 'mean'],
                     'CNT_PAYMENT':             ['mean', 'sum'],
                    }

In [24]:
cat_aggregations = {}
for cat in cat_cols:
    cat_aggregations[cat] = ['mean']  
cat_aggregations

{'NAME_CONTRACT_TYPE_Cash loans': ['mean'],
 'NAME_CONTRACT_TYPE_Consumer loans': ['mean'],
 'NAME_CONTRACT_TYPE_Revolving loans': ['mean'],
 'NAME_CONTRACT_TYPE_XNA': ['mean'],
 'NAME_CONTRACT_TYPE_nan': ['mean'],
 'WEEKDAY_APPR_PROCESS_START_WEEKEND': ['mean'],
 'WEEKDAY_APPR_PROCESS_START_WEEK_DAY': ['mean'],
 'WEEKDAY_APPR_PROCESS_START_nan': ['mean'],
 'HOUR_APPR_PROCESS_START_off_hours': ['mean'],
 'HOUR_APPR_PROCESS_START_working_hours': ['mean'],
 'HOUR_APPR_PROCESS_START_nan': ['mean'],
 'FLAG_LAST_APPL_PER_CONTRACT_N': ['mean'],
 'FLAG_LAST_APPL_PER_CONTRACT_Y': ['mean'],
 'FLAG_LAST_APPL_PER_CONTRACT_nan': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Building a house or an annex': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Business development': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Buying a garage': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Buying a holiday home / land': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Buying a home': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Buying a new car': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Buying a used car': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Car repairs': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Education': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Everyday expenses': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Furniture': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Gasification / water supply': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Hobby': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Journey': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Medicine': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Money for a third person': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Other': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Payments on other loans': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Purchase of electronic equipment': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Refusal to name the goal': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Repairs': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Urgent needs': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_Wedding / gift / holiday': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_XAP': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_XNA': ['mean'],
 'NAME_CASH_LOAN_PURPOSE_nan': ['mean'],
 'NAME_CONTRACT_STATUS_Approved': ['mean'],
 'NAME_CONTRACT_STATUS_Canceled': ['mean'],
 'NAME_CONTRACT_STATUS_Refused': ['mean'],
 'NAME_CONTRACT_STATUS_Unused offer': ['mean'],
 'NAME_CONTRACT_STATUS_nan': ['mean'],
 'NAME_PAYMENT_TYPE_Cash through the bank': ['mean'],
 'NAME_PAYMENT_TYPE_Cashless from the account of the employer': ['mean'],
 'NAME_PAYMENT_TYPE_Non-cash from your account': ['mean'],
 'NAME_PAYMENT_TYPE_XNA': ['mean'],
 'NAME_PAYMENT_TYPE_nan': ['mean'],
 'CODE_REJECT_REASON_CLIENT': ['mean'],
 'CODE_REJECT_REASON_HC': ['mean'],
 'CODE_REJECT_REASON_LIMIT': ['mean'],
 'CODE_REJECT_REASON_SCO': ['mean'],
 'CODE_REJECT_REASON_SCOFR': ['mean'],
 'CODE_REJECT_REASON_SYSTEM': ['mean'],
 'CODE_REJECT_REASON_VERIF': ['mean'],
 'CODE_REJECT_REASON_XAP': ['mean'],
 'CODE_REJECT_REASON_XNA': ['mean'],
 'CODE_REJECT_REASON_nan': ['mean'],
 'NAME_TYPE_SUITE_Children': ['mean'],
 'NAME_TYPE_SUITE_Family': ['mean'],
 'NAME_TYPE_SUITE_Group of people': ['mean'],
 'NAME_TYPE_SUITE_Other_A': ['mean'],
 'NAME_TYPE_SUITE_Other_B': ['mean'],
 'NAME_TYPE_SUITE_Spouse, partner': ['mean'],
 'NAME_TYPE_SUITE_Unaccompanied': ['mean'],
 'NAME_TYPE_SUITE_nan': ['mean'],
 'NAME_CLIENT_TYPE_New': ['mean'],
 'NAME_CLIENT_TYPE_Refreshed': ['mean'],
 'NAME_CLIENT_TYPE_Repeater': ['mean'],
 'NAME_CLIENT_TYPE_XNA': ['mean'],
 'NAME_CLIENT_TYPE_nan': ['mean'],
 'NAME_GOODS_CATEGORY_Additional Service': ['mean'],
 'NAME_GOODS_CATEGORY_Animals': ['mean'],
 'NAME_GOODS_CATEGORY_Audio/Video': ['mean'],
 'NAME_GOODS_CATEGORY_Auto Accessories': ['mean'],
 'NAME_GOODS_CATEGORY_Clothing and Accessories': ['mean'],
 'NAME_GOODS_CATEGORY_Computers': ['mean'],
 'NAME_GOODS_CATEGORY_Construction Materials': ['mean'],
 'NAME_GOODS_CATEGORY_Consumer Electronics': ['mean'],
 'NAME_GOODS_CATEGORY_Direct Sales': ['mean'],
 'NAME_GOODS_CATEGORY_Education': ['mean'],
 'NAME_GOODS_CATEGORY_Fitness': ['mean'],
 'NAME_GOODS_CATEGORY_Furniture': ['mean'],
 'NAME_GOODS_CATEGORY_Gardening': ['mean'],
 'NAME_GOODS_CATEGORY_Homewares': ['mean'],
 'NAME_GOODS_CATEGORY_Insurance': ['mean'],
 'NAME_GOODS_CATEGORY_Jewelry': ['mean'],
 'NAME_GOODS_CATEGORY_Medical Supplies': ['mean'],
 'NAME_GOODS_CATEGORY_Medicine': ['mean'],
 'NAME_GOODS_CATEGORY_Mobile': ['mean'],
 'NAME_GOODS_CATEGORY_Office Appliances': ['mean'],
 'NAME_GOODS_CATEGORY_Other': ['mean'],
 'NAME_GOODS_CATEGORY_Photo / Cinema Equipment': ['mean'],
 'NAME_GOODS_CATEGORY_Sport and Leisure': ['mean'],
 'NAME_GOODS_CATEGORY_Tourism': ['mean'],
 'NAME_GOODS_CATEGORY_Vehicles': ['mean'],
 'NAME_GOODS_CATEGORY_Weapon': ['mean'],
 'NAME_GOODS_CATEGORY_XNA': ['mean'],
 'NAME_GOODS_CATEGORY_nan': ['mean'],
 'NAME_PORTFOLIO_Cards': ['mean'],
 'NAME_PORTFOLIO_Cars': ['mean'],
 'NAME_PORTFOLIO_Cash': ['mean'],
 'NAME_PORTFOLIO_POS': ['mean'],
 'NAME_PORTFOLIO_XNA': ['mean'],
 'NAME_PORTFOLIO_nan': ['mean'],
 'NAME_PRODUCT_TYPE_XNA': ['mean'],
 'NAME_PRODUCT_TYPE_walk-in': ['mean'],
 'NAME_PRODUCT_TYPE_x-sell': ['mean'],
 'NAME_PRODUCT_TYPE_nan': ['mean'],
 'CHANNEL_TYPE_AP+ (Cash loan)': ['mean'],
 'CHANNEL_TYPE_Car dealer': ['mean'],
 'CHANNEL_TYPE_Channel of corporate sales': ['mean'],
 'CHANNEL_TYPE_Contact center': ['mean'],
 'CHANNEL_TYPE_Country-wide': ['mean'],
 'CHANNEL_TYPE_Credit and cash offices': ['mean'],
 'CHANNEL_TYPE_Regional / Local': ['mean'],
 'CHANNEL_TYPE_Stone': ['mean'],
 'CHANNEL_TYPE_nan': ['mean'],
 'NAME_SELLER_INDUSTRY_Auto technology': ['mean'],
 'NAME_SELLER_INDUSTRY_Clothing': ['mean'],
 'NAME_SELLER_INDUSTRY_Connectivity': ['mean'],
 'NAME_SELLER_INDUSTRY_Construction': ['mean'],
 'NAME_SELLER_INDUSTRY_Consumer electronics': ['mean'],
 'NAME_SELLER_INDUSTRY_Furniture': ['mean'],
 'NAME_SELLER_INDUSTRY_Industry': ['mean'],
 'NAME_SELLER_INDUSTRY_Jewelry': ['mean'],
 'NAME_SELLER_INDUSTRY_MLM partners': ['mean'],
 'NAME_SELLER_INDUSTRY_Tourism': ['mean'],
 'NAME_SELLER_INDUSTRY_XNA': ['mean'],
 'NAME_SELLER_INDUSTRY_nan': ['mean'],
 'NAME_YIELD_GROUP_XNA': ['mean'],
 'NAME_YIELD_GROUP_high': ['mean'],
 'NAME_YIELD_GROUP_low_action': ['mean'],
 'NAME_YIELD_GROUP_low_normal': ['mean'],
 'NAME_YIELD_GROUP_middle': ['mean'],
 'NAME_YIELD_GROUP_nan': ['mean'],
 'PRODUCT_COMBINATION_Card Street': ['mean'],
 'PRODUCT_COMBINATION_Card X-Sell': ['mean'],
 'PRODUCT_COMBINATION_Cash': ['mean'],
 'PRODUCT_COMBINATION_Cash Street: high': ['mean'],
 'PRODUCT_COMBINATION_Cash Street: low': ['mean'],
 'PRODUCT_COMBINATION_Cash Street: middle': ['mean'],
 'PRODUCT_COMBINATION_Cash X-Sell: high': ['mean'],
 'PRODUCT_COMBINATION_Cash X-Sell: low': ['mean'],
 'PRODUCT_COMBINATION_Cash X-Sell: middle': ['mean'],
 'PRODUCT_COMBINATION_POS household with interest': ['mean'],
 'PRODUCT_COMBINATION_POS household without interest': ['mean'],
 'PRODUCT_COMBINATION_POS industry with interest': ['mean'],
 'PRODUCT_COMBINATION_POS industry without interest': ['mean'],
 'PRODUCT_COMBINATION_POS mobile with interest': ['mean'],
 'PRODUCT_COMBINATION_POS mobile without interest': ['mean'],
 'PRODUCT_COMBINATION_POS other with interest': ['mean'],
 'PRODUCT_COMBINATION_POS others without interest': ['mean'],
 'PRODUCT_COMBINATION_nan': ['mean'],
 'CHURN_PREV_0': ['mean'],
 'CHURN_PREV_1': ['mean'],
 'CHURN_PREV_NaN': ['mean'],
 'CHURN_PREV_nan': ['mean']}

In [25]:
grouped = prev_app.groupby('SK_ID_CURR')
prev_agg=grouped.agg({**num_aggregations, **cat_aggregations})

In [26]:
prev_agg.shape   
prev_agg.columns
prev_agg.head()

           AMT_ANNUITY                         AMT_APPLICATION            \
                   min        max         mean             min       max
SK_ID_CURR
0             2250.000  11180.385   6659.13750         25200.0  120658.5
1             2250.000  25996.365  12909.10500             0.0  337500.0
2             2457.675  24577.425   9705.64500         16420.5  225000.0
3             3404.520   6750.000   4883.83875             0.0  135000.0
4             8957.430   8957.430   8957.43000         47250.0   47250.0

                         AMT_CREDIT                         APP_CREDIT_PERC  \
                    mean        min       max          mean             min
SK_ID_CURR
0           78399.000000    21928.5  120658.5  77853.750000        1.000000
1           68303.571429        0.0  384277.5  74634.428571        0.878272
2           85230.123750    14170.5  239850.0  87738.750000        0.938086
3           41482.500000        0.0  135000.0  43401.000000        0.904489
4           47250.000000    44631.0   44631.0  44631.000000        1.058681

            ... PRODUCT_COMBINATION_POS industry without interest  \
            ...                                              mean
SK_ID_CURR  ...
0           ...                                              0.00
1           ...                                              0.00
2           ...                                              0.25
3           ...                                              0.00
4           ...                                              0.00

           PRODUCT_COMBINATION_POS mobile with interest  \
                                                   mean
SK_ID_CURR
0                                                  0.00
1                                                  0.00
2                                                  0.25
3                                                  0.00
4                                                  0.00

           PRODUCT_COMBINATION_POS mobile without interest  \
                                                      mean
SK_ID_CURR
0                                                      0.0
1                                                      0.0
2                                                      0.0
3                                                      0.0
4                                                      0.0

           PRODUCT_COMBINATION_POS other with interest  \
                                                  mean
SK_ID_CURR
0                                                  0.0
1                                                  0.0
2                                                  0.0
3                                                  0.0
4                                                  0.0

           PRODUCT_COMBINATION_POS others without interest  \
                                                      mean
SK_ID_CURR
0                                                      0.0
1                                                      0.0
2                                                      0.0
3                                                      0.0
4                                                      0.0

           PRODUCT_COMBINATION_nan CHURN_PREV_0 CHURN_PREV_1 CHURN_PREV_NaN  \
                              mean         mean         mean           mean
SK_ID_CURR
0                              0.0     0.166667     0.666667       0.166667
1                              0.0     0.000000     0.428571       0.571429
2                              0.0     0.000000     1.000000       0.000000
3                              0.0     0.000000     0.666667       0.333333
4                              0.0     0.000000     1.000000       0.000000

           CHURN_PREV_nan
                     mean
SK_ID_CURR
0                     0.0
1                     0.0
2                     0.0
3                     0.0
4                     0.0

[5 rows x 187 columns]

In [27]:
prev_agg.columns = pd.Index(['PREV_' + e[0] + "_" + e[1].upper() for e in prev_agg.columns.tolist()])

In [28]:
prev_agg.shape

(291057, 187)

Groupby status

In [29]:
approved = prev_app[prev_app['NAME_CONTRACT_STATUS_Approved'] == 1]
approved_agg = approved.groupby('SK_ID_CURR').agg(num_aggregations)

In [30]:
approved_agg.columns
approved_agg.head()

           AMT_ANNUITY                         AMT_APPLICATION            \
                   min        max         mean             min       max
SK_ID_CURR
0             2250.000  11180.385   7008.85800         25200.0  120658.5
1             2250.000  25996.365  12909.10500         45000.0  337500.0
2             2457.675  24577.425   9705.64500         16420.5  225000.0
3             3404.520   6750.000   4883.83875         29205.0  135000.0
4             8957.430   8957.430   8957.43000         47250.0   47250.0

                         AMT_CREDIT                      APP_CREDIT_PERC  ...  \
                    mean        min       max       mean             min  ...
SK_ID_CURR                                                                ...
0            72857.70000    21928.5  120658.5   72203.40        1.000000  ...
1           159375.00000    45000.0  384277.5  174147.00        0.878272  ...
2            85230.12375    14170.5  239850.0   87738.75        0.938086  ...
3            62223.75000    31774.5  135000.0   65101.50        0.904489  ...
4            47250.00000    44631.0   44631.0   44631.00        1.058681  ...

           AMT_GOODS_PRICE               RATE_DOWN_PAYMENT            \
                       max          mean               min       max
SK_ID_CURR
0                 120658.5   72857.70000          0.000000  0.185440
1                 337500.0  159375.00000          0.101381  0.101381
2                 225000.0   85230.12375          0.101379  0.186103
3                 135000.0   62223.75000          0.000000  0.000000
4                  47250.0   47250.00000          0.104262  0.104262

                     DAYS_DECISION               CNT_PAYMENT
                mean           min max      mean        mean   sum
SK_ID_CURR
0           0.046360             0   1  0.800000    8.000000  40.0
1           0.101381             0   1  0.333333   15.333333  46.0
2           0.129705             0   0  0.000000    9.500000  38.0
3           0.000000             0   1  0.500000    8.500000  34.0
4           0.104262             0   0  0.000000    6.000000   6.0

[5 rows x 27 columns]

In [31]:


approved_agg.columns = pd.Index(['APPROVED_' + e[0] + "_" + e[1].upper() for e in approved_agg.columns.tolist()])

In [32]:
approved_agg.shape

(290065, 27)

In [33]:
prev_agg = prev_agg.join(approved_agg,         
                         how='left',           
                         on='SK_ID_CURR')

In [34]:
prev_agg.shape     
prev_agg.head()

,PREV_AMT_ANNUITY_MIN,PREV_AMT_ANNUITY_MAX,PREV_AMT_ANNUITY_MEAN,PREV_AMT_APPLICATION_MIN,PREV_AMT_APPLICATION_MAX,PREV_AMT_APPLICATION_MEAN,PREV_AMT_CREDIT_MIN,PREV_AMT_CREDIT_MAX,PREV_AMT_CREDIT_MEAN,PREV_APP_CREDIT_PERC_MIN,...,APPROVED_AMT_GOODS_PRICE_MAX,APPROVED_AMT_GOODS_PRICE_MEAN,APPROVED_RATE_DOWN_PAYMENT_MIN,APPROVED_RATE_DOWN_PAYMENT_MAX,APPROVED_RATE_DOWN_PAYMENT_MEAN,APPROVED_DAYS_DECISION_MIN,APPROVED_DAYS_DECISION_MAX,APPROVED_DAYS_DECISION_MEAN,APPROVED_CNT_PAYMENT_MEAN,APPROVED_CNT_PAYMENT_SUM
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
0,2250.000,11180.385,6659.13750,25200.0,120658.5,78399.000000,21928.5,120658.5,77853.750000,1.000000,...,120658.5,72857.70000,0.000000,0.185440,0.046360,0.0,1.0,0.800000,8.000000,40.0
1,2250.000,25996.365,12909.10500,0.0,337500.0,68303.571429,0.0,384277.5,74634.428571,0.878272,...,337500.0,159375.00000,0.101381,0.101381,0.101381,0.0,1.0,0.333333,15.333333,46.0
2,2457.675,24577.425,9705.64500,16420.5,225000.0,85230.123750,14170.5,239850.0,87738.750000,0.938086,...,225000.0,85230.12375,0.101379,0.186103,0.129705,0.0,0.0,0.000000,9.500000,38.0
3,3404.520,6750.000,4883.83875,0.0,135000.0,41482.500000,0.0,135000.0,43401.000000,0.904489,...,135000.0,62223.75000,0.000000,0.000000,0.000000,0.0,1.0,0.500000,8.500000,34.0
4,8957.430,8957.430,8957.43000,47250.0,47250.0,47250.000000,44631.0,44631.0,44631.000000,1.058681,...,47250.0,47250.00000,0.104262,0.104262,0.104262,0.0,0.0,0.000000,6.000000,6.0

In [35]:
#For refused status

In [36]:
refused = prev_app[prev_app['NAME_CONTRACT_STATUS_Refused'] == 1]
refused_agg = refused.groupby('SK_ID_CURR').agg(num_aggregations)

In [37]:
refused_agg.shape

(100294, 27)

In [38]:
refused_agg.columns = pd.Index(['REFUSED_' + e[0] + "_" + e[1].upper() for e in refused_agg.columns.tolist()])

In [39]:
prev_agg = prev_agg.join(                    
                         refused_agg,         
                         how='left',
                         on='SK_ID_CURR'
                        )

In [40]:
prev_agg.shape

(291057, 241)

,PREV_AMT_ANNUITY_MIN,PREV_AMT_ANNUITY_MAX,PREV_AMT_ANNUITY_MEAN,PREV_AMT_APPLICATION_MIN,PREV_AMT_APPLICATION_MAX,PREV_AMT_APPLICATION_MEAN,PREV_AMT_CREDIT_MIN,PREV_AMT_CREDIT_MAX,PREV_AMT_CREDIT_MEAN,PREV_APP_CREDIT_PERC_MIN,...,REFUSED_AMT_GOODS_PRICE_MAX,REFUSED_AMT_GOODS_PRICE_MEAN,REFUSED_RATE_DOWN_PAYMENT_MIN,REFUSED_RATE_DOWN_PAYMENT_MAX,REFUSED_RATE_DOWN_PAYMENT_MEAN,REFUSED_DAYS_DECISION_MIN,REFUSED_DAYS_DECISION_MAX,REFUSED_DAYS_DECISION_MEAN,REFUSED_CNT_PAYMENT_MEAN,REFUSED_CNT_PAYMENT_SUM
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
0,2250.000,11180.385,6659.137500,25200.0,120658.5,78399.000000,21928.5,120658.5,77853.750000,1.000000,...,106105.5,106105.5,0.0,0.0,0.0,1.0,1.0,1.0,24.0,24.0
1,2250.000,25996.365,12909.105000,0.0,337500.0,68303.571429,0.0,384277.5,74634.428571,0.878272,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2457.675,24577.425,9705.645000,16420.5,225000.0,85230.123750,14170.5,239850.0,87738.750000,0.938086,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3404.520,6750.000,4883.838750,0.0,135000.0,41482.500000,0.0,135000.0,43401.000000,0.904489,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8957.430,8957.430,8957.430000,47250.0,47250.0,47250.000000,44631.0,44631.0,44631.000000,1.058681,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307505,2250.000,13949.100,6897.585000,31455.0,126891.0,79915.500000,27054.0,126891.0,78343.875000,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307506,2903.625,17043.120,11164.905000,13783.5,182592.0,107453.250000,14467.5,182592.0,113787.000000,0.904480,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307508,8553.105,45000.000,30770.105625,0.0,864000.0,325077.300000,0.0,966645.0,437631.300000,0.000000,...,864000.0,802500.0,NaN,NaN,NaN,1.0,1.0,1.0,36.0,108.0
307509,3780.675,16044.075,9864.630000,20250.0,229500.0,121269.000000,20250.0,248130.0,119979.000000,0.924918,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307510,20699.910,20699.910,20699.910000,192811.5,192811.5,192811.500000,186318.0,186318.0,186318.000000,1.034852,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
prev_agg.to_csv("/kaggle/working/new_prev_app.csv")

In [45]:
!ls

new_prev_app.csv

<a href="new_prev_app.csv"> Download File </a>